In [45]:
import polars as pl
import math
from pathlib import Path

pl.Config.set_tbl_cols(-1)
pl.Config.set_tbl_rows(20)
pl.Config.set_tbl_width_chars(250)

polars.config.Config

In [46]:
import polars as pl
from pathlib import Path
from datetime import timedelta

In [47]:
GTFS = Path("raw/processed_gtfs")
RT = Path("raw")
 
# ---------------------------------------------------
# Read files
# ---------------------------------------------------
 
routes = pl.read_parquet(GTFS / "routes.parquet")
trips = pl.read_parquet(GTFS / "trips.parquet")
stops = pl.read_parquet(GTFS / "stops.parquet")
stop_times = pl.read_parquet(GTFS / "stop_times.parquet")
 
trip_updates = pl.read_parquet(RT / "trip_updates/2026-07-01.parquet")
vehicle_positions = pl.read_parquet(RT / "vehicle_positions/2026-07-01.parquet")
 
print("Loaded")

Loaded

In [48]:
def gtfs_to_seconds(col):
    p = pl.col(col).str.split(":")
    return (
        p.list.get(0).cast(pl.Int32) * 3600
        + p.list.get(1).cast(pl.Int32) * 60
        + p.list.get(2).cast(pl.Int32)
    )
 
stop_times = stop_times.with_columns(
    pl.col("stop_sequence").cast(pl.UInt32),
    pl.col("stop_id").cast(pl.Utf8),
    gtfs_to_seconds("arrival_time").alias("scheduled_arrival"),
    gtfs_to_seconds("departure_time").alias("scheduled_departure"),
)
 
stops = stops.with_columns([
    pl.col("stop_id").cast(pl.Utf8),

    # pl.col("stop_lat")
    #   .str.strip_chars()
    #   .cast(pl.Float64),

    # pl.col("stop_lon")
    #   .str.strip_chars()
    #   .cast(pl.Float64),
])

In [49]:

trip_updates = (
    trip_updates
    .sort("feed_timestamp")
    .group_by(["trip_id", "start_date", "stop_sequence"])
    .last()
)

In [50]:
if "schedule_relationship" in trip_updates.columns:
    trip_updates = trip_updates.filter(pl.col("schedule_relationship") == 0)

In [51]:
trip_updates = trip_updates.with_columns(
    pl.from_epoch("arrival_time", time_unit="s").alias("event_time")
)
 
vehicle_positions = vehicle_positions.with_columns(
    pl.from_epoch("timestamp", time_unit="s").alias("vehicle_time")
)

In [52]:
TRIP_ID_PATTERN = r'^[A-Z]{2}_([A-Z0-9]+)-(\w+?)-(\d+)_([A-Z0-9+]+)_(\d+)$'
 
def parse_trip_id(df: pl.DataFrame) -> pl.DataFrame:
    return df.with_columns([
        pl.col("trip_id").str.extract(TRIP_ID_PATTERN, 2).alias("_service_day"),
        pl.col("trip_id").str.extract(TRIP_ID_PATTERN, 3).alias("_origin_secs"),
        pl.col("trip_id").str.extract(TRIP_ID_PATTERN, 5).alias("_trip_num"),
    ])
 
trips_parsed = parse_trip_id(trips)
tu_parsed = parse_trip_id(trip_updates)
 
# 1) direct trip_id match
direct = tu_parsed.join(
    trips_parsed.select(["trip_id", "route_id", "direction_id", "shape_id", "service_id"]),
    on="trip_id", how="inner", suffix="_static",
)

In [53]:
unmatched = tu_parsed.join(direct.select("trip_id").unique(), on="trip_id", how="anti")
fallback = unmatched.join(
    trips_parsed.select([
        "trip_id", "route_id", "direction_id", "shape_id", "service_id",
        "_service_day", "_origin_secs", "_trip_num",
    ]).rename({"trip_id": "_static_trip_id"}),
    on=["route_id", "_service_day", "_origin_secs", "_trip_num"],
    how="inner",
    suffix="_static",
).with_columns(
    pl.col("_static_trip_id").alias("trip_id")   # use the STATIC trip_id downstream
).drop("_static_trip_id")
 
n_direct, n_fallback, n_total = direct.height, fallback.height, tu_parsed.height
print(f"[join] direct match: {n_direct:,} | fallback match: {n_fallback:,} | "
      f"total: {(n_direct + n_fallback) / n_total:.1%} of {n_total:,} rows")
 
direct = direct.drop(["_service_day", "_origin_secs", "_trip_num"])
fallback = fallback.drop(["_service_day", "_origin_secs", "_trip_num"])

[join] direct match: 70,053 | fallback match: 0 | total: 100.0% of 70,053 rows

In [54]:
direct = (
    direct.drop(["route_id", "direction_id"])
          .rename({"route_id_static": "route_id", "direction_id_static": "direction_id"})
)
fallback = fallback.drop("direction_id").rename({"direction_id_static": "direction_id"})
 
matched = pl.concat([direct, fallback.select(direct.columns)])

In [55]:
data = (
    matched
    .join(
        stop_times.select([
            "trip_id", "stop_sequence", "stop_id",
            "scheduled_arrival", "scheduled_departure",
        ]),
        on=["trip_id", "stop_sequence"],
        how="inner",   # inner now: every row here already has a resolved static trip_id,
                        # so a missing stop_times row means bad data, not an expected gap
    )
    .join(
        stops.select(["stop_id", "stop_lat", "stop_lon"]),
        on="stop_id",
        how="left",
    )
)
 
print(data.shape)

(70053, 22)

In [56]:
def haversine_expr(lat1, lon1, lat2, lon2) -> pl.Expr:
    R = 6371000.0
    lat1r, lat2r = lat1.radians(), lat2.radians()
    dlat = (lat2 - lat1).radians()
    dlon = (lon2 - lon1).radians()
    a = (dlat / 2).sin() ** 2 + lat1r.cos() * lat2r.cos() * (dlon / 2).sin() ** 2
    return 2 * R * a.sqrt().arcsin()
 
vehicle_positions = vehicle_positions.sort(["vehicle_id", "vehicle_time"])
vehicle_positions = vehicle_positions.with_columns([
    pl.col("latitude").shift(1).over("vehicle_id").alias("_prev_lat"),
    pl.col("longitude").shift(1).over("vehicle_id").alias("_prev_lon"),
    pl.col("vehicle_time").shift(1).over("vehicle_id").alias("_prev_time"),
])
vehicle_positions = vehicle_positions.with_columns(
    haversine_expr(pl.col("_prev_lat"), pl.col("_prev_lon"), pl.col("latitude"), pl.col("longitude")).alias("_dist_m")
)
vehicle_positions = vehicle_positions.with_columns(
    (
        pl.col("_dist_m")
        / (pl.col("vehicle_time") - pl.col("_prev_time")).dt.total_seconds().clip(lower_bound=1)
    ).alias("speed_mps")
)

In [57]:
vp = vehicle_positions.select([
    "vehicle_id", "vehicle_time", "latitude", "longitude", "bearing", "speed_mps",
])
 
data = data.sort(["vehicle_id", "event_time"])
vp = vp.sort(["vehicle_id", "vehicle_time"])
 
data = data.join_asof(
    vp,
    left_on="event_time",
    right_on="vehicle_time",
    by="vehicle_id",
    strategy="backward",
    tolerance=timedelta(minutes=2),
)

C:\Users\ishan\AppData\Local\Temp\ipykernel_28116\3507643840.py:8: UserWarning: Sortedness of columns cannot be checked when 'by' groups provided
  data = data.join_asof(

In [58]:
data = (
    data
    .sort(["trip_id", "stop_sequence"])
    .with_columns(
        pl.col("arrival_time").shift(-1).over("trip_id").alias("next_arrival_time")
    )
    .with_columns(
        (pl.col("next_arrival_time") - pl.col("arrival_time")).alias("travel_time")
    )
)
 
data = data.filter(
    (pl.col("travel_time") > 0) & (pl.col("travel_time") < 1800)   # 30 min cap
)

In [59]:
# data = data.with_columns([
#     pl.col("event_time").dt.hour().alias("hour"),
#     pl.col("event_time").dt.weekday().alias("weekday"),
#     pl.col("event_time").dt.month().alias("month"),
# ])
 
# data = data.with_columns([
#     (
#         (pl.col("hour").is_between(7, 9)) |
#         (pl.col("hour").is_between(16, 18))
#     ).cast(pl.Int8).alias("is_peak")
# ])

data = data.with_columns(
    pl.col("event_time")
      .dt.replace_time_zone("UTC")
      .dt.convert_time_zone("America/New_York")
      .alias("event_time_local")
)
 
data = data.with_columns([
    pl.col("event_time_local").dt.hour().alias("hour"),
    pl.col("event_time_local").dt.weekday().alias("weekday"),
    pl.col("event_time_local").dt.month().alias("month"),
])
 
data = data.with_columns([
    (
        (pl.col("hour").is_between(7, 9)) |
        (pl.col("hour").is_between(16, 18))
    ).cast(pl.Int8).alias("is_peak")
])

In [60]:
data = data.with_columns([
    (
        pl.col("scheduled_arrival")
        - pl.col("scheduled_departure").shift(1).over("trip_id")
    ).alias("scheduled_segment_time"),
 
    (
        pl.col("stop_sequence") / pl.col("stop_sequence").max().over("trip_id")
    ).alias("trip_progress"),
])

In [61]:
segment_network = pl.read_parquet("processed/segment_network.parquet")
 
# dtype fix: segment_network's stop_id/next_stop_id are Int64 (straight
# from stop_times.txt), but `data`'s stop_id was cast to Utf8 earlier for
# the RT join - cast both sides to match before joining.
segment_network = segment_network.with_columns([
    pl.col("stop_id").cast(pl.Utf8),
    pl.col("next_stop_id").cast(pl.Utf8),
])

In [62]:
data = (
    data
    .sort(["trip_id", "stop_sequence"])
    .with_columns(
        pl.col("stop_id").shift(-1).over("trip_id").alias("next_stop_id")
    )
)
 
# %%
n_before = data.height
 
data = data.join(
    segment_network.select([
        "shape_id", "stop_id", "next_stop_id",
        "segment_length", "scheduled_travel_time",
    ]).rename({"scheduled_travel_time": "segment_scheduled_travel_time"}),
    on=["shape_id", "stop_id", "next_stop_id"],
    how="left",
)
 
print(f"rows before: {n_before:,} | after segment join: {data.height:,}")
print("null segment_length rows:", data.filter(pl.col("segment_length").is_null()).height)

rows before: 67,196 | after segment join: 67,196
null segment_length rows: 2949

In [63]:
data = data.with_columns(
    (pl.col("segment_length") / pl.col("segment_scheduled_travel_time").clip(lower_bound=1))
    .alias("scheduled_segment_speed_mps")
)

In [64]:
data = data.sort(["trip_id", "stop_sequence"])
check = data.select([
    "trip_id", "stop_sequence", "scheduled_segment_time", "segment_scheduled_travel_time",
]).with_columns(
    # bring segment_scheduled_travel_time from row k up to align with
    # scheduled_segment_time at row k+1 (both now describe segment k->k+1)
    pl.col("segment_scheduled_travel_time").shift(1).over("trip_id").alias("segment_scheduled_travel_time_aligned")
).drop_nulls(subset=["scheduled_segment_time", "segment_scheduled_travel_time_aligned"])
 
diff = (check["scheduled_segment_time"] - check["segment_scheduled_travel_time_aligned"]).abs()
print("median abs diff (aligned):", diff.median())
print("rows with diff > 30s (aligned):", (diff > 30).sum(), "/", check.height)
 
# expected: last stop of each trip has null segment_length/next_stop_id -
# should be roughly one per trip, not a bug
n_null_segment = data.filter(pl.col("segment_length").is_null()).height
n_trips = data["trip_id"].n_unique()
print(f"null segment_length rows: {n_null_segment:,} vs trip count: {n_trips:,} (should be close)")

median abs diff (aligned): 20.0
rows with diff > 30s (aligned): 21580 / 64247
null segment_length rows: 2,949 vs trip count: 1,314 (should be close)

In [65]:

import requests
from datetime import datetime
 
STATION_LAT, STATION_LON = 40.7829, -73.9654  # Central Park
 
dates_needed = data["start_date"].unique().sort().to_list()
start_date = str(dates_needed[0])
end_date = str(dates_needed[-1])
start_fmt = f"{start_date[:4]}-{start_date[4:6]}-{start_date[6:8]}"
end_fmt = f"{end_date[:4]}-{end_date[4:6]}-{end_date[6:8]}"
 
print(f"Fetching weather for {start_fmt} to {end_fmt}")
 
resp = requests.get(
    "https://archive-api.open-meteo.com/v1/archive",
    params={
        "latitude": STATION_LAT,
        "longitude": STATION_LON,
        "start_date": start_fmt,
        "end_date": end_fmt,
        "hourly": "temperature_2m,precipitation,rain,snowfall,"
                  "windspeed_10m,weathercode",
        "timezone": "America/New_York",
    },
    timeout=30,
)
resp.raise_for_status()
weather_json = resp.json()["hourly"]
 
weather = pl.DataFrame({
    "weather_time_str": weather_json["time"],
    "temperature_c": weather_json["temperature_2m"],
    "precipitation_mm": weather_json["precipitation"],
    "rain_mm": weather_json["rain"],
    "snowfall_cm": weather_json["snowfall"],
    "windspeed_kmh": weather_json["windspeed_10m"],
    "weathercode": weather_json["weathercode"],
})
 
weather = weather.with_columns(
    pl.col("weather_time_str").str.strptime(pl.Datetime, "%Y-%m-%dT%H:%M").alias("weather_time")
).with_columns([
    pl.col("weather_time").dt.strftime("%Y%m%d").alias("start_date"),  # keep as str - matches data's dtype
    pl.col("weather_time").dt.hour().alias("hour"),
])
 
print(weather.shape)
print(weather.head())

Fetching weather for 2026-06-30 to 2026-07-01
(48, 10)
shape: (5, 10)
┌──────────────────┬───────────────┬──────────────────┬─────────┬─────────────┬───────────────┬─────────────┬─────────────────────┬────────────┬──────┐
│ weather_time_str ┆ temperature_c ┆ precipitation_mm ┆ rain_mm ┆ snowfall_cm ┆ windspeed_kmh ┆ weathercode ┆ weather_time        ┆ start_date ┆ hour │
│ ---              ┆ ---           ┆ ---              ┆ ---     ┆ ---         ┆ ---           ┆ ---         ┆ ---                 ┆ ---        ┆ ---  │
│ str              ┆ f64           ┆ f64              ┆ f64     ┆ f64         ┆ f64           ┆ i64         ┆ datetime[μs]        ┆ str        ┆ i8   │
╞══════════════════╪═══════════════╪══════════════════╪═════════╪═════════════╪═══════════════╪═════════════╪═════════════════════╪════════════╪══════╡
│ 2026-06-30T00:00 ┆ 24.6          ┆ 0.0              ┆ 0.0     ┆ 0.0         ┆ 5.7           ┆ 1           ┆ 2026-06-30 00:00:00 ┆ 20260630   ┆ 0    │
│ 2026-06-30T01:00 ┆ 24.1          ┆ 0.0              ┆ 0.0     ┆ 0.0         ┆ 5.1           ┆ 2           ┆ 2026-06-30 01:00:00 ┆ 20260630   ┆ 1    │
│ 2026-06-30T02:00 ┆ 23.1          ┆ 0.0              ┆ 0.0     ┆ 0.0         ┆ 4.8           ┆ 1           ┆ 2026-06-30 02:00:00 ┆ 20260630   ┆ 2    │
│ 2026-06-30T03:00 ┆ 22.9          ┆ 0.0              ┆ 0.0     ┆ 0.0         ┆ 5.7           ┆ 2           ┆ 2026-06-30 03:00:00 ┆ 20260630   ┆ 3    │
│ 2026-06-30T04:00 ┆ 22.4          ┆ 0.0              ┆ 0.0     ┆ 0.0         ┆ 5.7           ┆ 3           ┆ 2026-06-30 04:00:00 ┆ 20260630   ┆ 4    │
└──────────────────┴───────────────┴──────────────────┴─────────┴─────────────┴───────────────┴─────────────┴─────────────────────┴────────────┴──────┘

In [66]:
# %%
# ---------------------------------------------------------------------
# Join weather onto data by (start_date, hour) - both now NYC-local
# ---------------------------------------------------------------------
 
n_before = data.height
 
data = data.join(
    weather.select([
        "start_date", "hour", "temperature_c", "precipitation_mm",
        "rain_mm", "snowfall_cm", "windspeed_kmh", "weathercode",
    ]),
    on=["start_date", "hour"],
    how="left",
)
 
print(f"rows before: {n_before:,} | after weather join: {data.height:,}")
print("null weather rows:", data.filter(pl.col("temperature_c").is_null()).height)

rows before: 67,196 | after weather join: 67,196
null weather rows: 0

In [67]:
data = data.with_columns([
    (pl.col("precipitation_mm") > 0.1).cast(pl.Int8).alias("is_raining"),
    (pl.col("snowfall_cm") > 0.0).cast(pl.Int8).alias("is_snowing"),
    # WMO weather codes 45 (fog) / 48 (depositing rime fog) as a
    # low-visibility proxy - the archive API doesn't expose visibility
    # directly (ERA5 reanalysis has no such variable; that's a
    # forecast-API-only field), so this is the closest available signal.
    pl.col("weathercode").is_in([45, 48]).cast(pl.Int8).alias("is_fog"),
])

In [68]:
# 1. UPSTREAM DELAY
# ---------------------------------------------------------------------
# scheduled_arrival is seconds-since-midnight (local, naive), while
# arrival_time (RT) is an absolute UTC epoch - not directly comparable
# yet. Convert scheduled_arrival to an absolute epoch first, anchored on
# start_date in America/New_York (same pattern used for the weather join).
 
data = data.with_columns(
    pl.col("start_date").str.strptime(pl.Date, "%Y%m%d").alias("service_date")
)
 
data = data.with_columns(
    (
        pl.col("service_date").cast(pl.Datetime)
          .dt.replace_time_zone("America/New_York")
        + pl.duration(seconds=pl.col("scheduled_arrival"))
    ).dt.epoch(time_unit="s").alias("scheduled_arrival_epoch")
)
 
data = data.with_columns(
    (pl.col("arrival_time") - pl.col("scheduled_arrival_epoch")).alias("delay_seconds")
)

In [69]:
# ---------------------------------------------------------------------
# Load + reshape ridership CSV - route + hour granularity
# ---------------------------------------------------------------------
ridership_raw = pl.read_csv(
    "MTA_Bus_Hourly_Ridership_Mar_July.csv",
    schema_overrides={"ridership": pl.Utf8, "transfers": pl.Utf8},
)

# ridership/transfers arrive as strings with thousands separators
# (e.g. "1,131") - strip commas before casting to Int64
ridership_raw = ridership_raw.with_columns(
    pl.col("transit_timestamp")
      .str.strptime(pl.Datetime, "%m/%d/%Y %I:%M:%S %p")
      .alias("_ts"),
    pl.col("ridership").str.replace_all(",", "").cast(pl.Int64),
    pl.col("transfers").str.replace_all(",", "").cast(pl.Int64),
).with_columns([
    pl.col("_ts").dt.date().alias("service_date"),
    pl.col("_ts").dt.hour().alias("hour"),
])

# collapse both fare_class_category and payment_method - one total per
# (route, date, hour)
ridership_hourly = (
    ridership_raw
    .group_by(["bus_route", "service_date", "hour"])
    .agg([
        pl.col("ridership").sum(),
        pl.col("transfers").sum(),
    ])
)

print(ridership_hourly.shape)
print(ridership_hourly.head(10))

(16320, 5)
shape: (10, 5)
┌───────────┬──────────────┬──────┬───────────┬───────────┐
│ bus_route ┆ service_date ┆ hour ┆ ridership ┆ transfers │
│ ---       ┆ ---          ┆ ---  ┆ ---       ┆ ---       │
│ str       ┆ date         ┆ i8   ┆ i64       ┆ i64       │
╞═══════════╪══════════════╪══════╪═══════════╪═══════════╡
│ M15       ┆ 2026-03-20   ┆ 4    ┆ 100       ┆ 21        │
│ M1        ┆ 2026-06-27   ┆ 22   ┆ 82        ┆ 13        │
│ M2        ┆ 2026-05-10   ┆ 21   ┆ 98        ┆ 10        │
│ M1        ┆ 2026-07-07   ┆ 9    ┆ 488       ┆ 129       │
│ M4        ┆ 2026-04-10   ┆ 8    ┆ 775       ┆ 195       │
│ M101      ┆ 2026-05-09   ┆ 16   ┆ 498       ┆ 116       │
│ M101      ┆ 2026-06-01   ┆ 11   ┆ 770       ┆ 209       │
│ M15       ┆ 2026-07-09   ┆ 22   ┆ 363       ┆ 68        │
│ M1        ┆ 2026-03-11   ┆ 22   ┆ 68        ┆ 7         │
│ M4        ┆ 2026-04-08   ┆ 11   ┆ 521       ┆ 111       │
└───────────┴──────────────┴──────┴───────────┴───────────┘

In [70]:
# ---------------------------------------------------------------------
# Join onto `data` by (route_id, service_date, hour).
# NOTE: this ridership file only covers 5 routes (M1, M2, M4, M15, M101).
# route_id naming is verified before joining - if your GTFS route_id has
# an agency prefix (e.g. "MTA NYCT_M1") rather than the bare "M1" used in
# the ridership file, normalize one side before joining.
# ---------------------------------------------------------------------
sample_route_ids = data.select("route_id").unique().sort("route_id").head(10)
print("sample route_id values in `data`:", sample_route_ids["route_id"].to_list())
print("route values in ridership file:", ridership_hourly["bus_route"].unique().sort().to_list())

# If the printed lists above don't share the same format (e.g. one has a
# prefix like "MTA NYCT_"), normalize here before the join, e.g.:
# data = data.with_columns(pl.col("route_id").str.extract(r"([A-Z]+\d+)$", 1).alias("route_id"))

n_before = data.height

data = data.join(
    ridership_hourly,
    left_on=["route_id", "service_date", "hour"],
    right_on=["bus_route", "service_date", "hour"],
    how="left",
).with_columns([
    pl.col("ridership").fill_null(0),
    pl.col("transfers").fill_null(0),
])

print(f"rows before: {n_before:,} | after ridership join: {data.height:,}")
print("routes with zero-filled ridership (not in ridership file, or no match):",
      data.filter(pl.col("ridership") == 0).select("route_id").unique().height)

sample route_id values in `data`: ['M1', 'M101', 'M15', 'M2', 'M4']
route values in ridership file: ['M1', 'M101', 'M15', 'M2', 'M4']
rows before: 67,196 | after ridership join: 67,196
routes with zero-filled ridership (not in ridership file, or no match): 0

In [71]:
print(data.select(
    pl.col("delay_seconds").min().alias("min"),
    pl.col("delay_seconds").max().alias("max"),
    pl.col("delay_seconds").median().alias("median"),
))

shape: (1, 3)
┌───────┬───────┬────────┐
│ min   ┆ max   ┆ median │
│ ---   ┆ ---   ┆ ---    │
│ i64   ┆ i64   ┆ f64    │
╞═══════╪═══════╪════════╡
│ -1263 ┆ 13450 ┆ 67.0   │
└───────┴───────┴────────┘

In [72]:
data = data.sort(["trip_id", "stop_sequence"])
data = data.with_columns(
    pl.col("delay_seconds").shift(1).over("trip_id").alias("upstream_delay_seconds")
)

In [73]:
# %%
# ---------------------------------------------------------------------
# 3. HEADWAY TO PRECEDING BUS (same route + direction + stop)
# ---------------------------------------------------------------------
# For each (route_id, direction_id, stop_id), sort arrivals by time and
# take the gap to the PREVIOUS bus that hit the same stop - this is a
# same-route self-join across TRIPS, not within a single trip.
 
headway_base = (
    data.select(["route_id", "direction_id", "stop_id", "trip_id", "arrival_time"])
    .unique()
    .sort(["route_id", "direction_id", "stop_id", "arrival_time"])
)
 
headway_base = headway_base.with_columns(
    pl.col("arrival_time")
      .shift(1)
      .over(["route_id", "direction_id", "stop_id"])
      .alias("_prev_bus_arrival")
)
headway_base = headway_base.with_columns(
    (pl.col("arrival_time") - pl.col("_prev_bus_arrival")).alias("headway_seconds")
)

In [74]:
data = data.join(
    headway_base.select(["route_id", "direction_id", "stop_id", "trip_id", "arrival_time", "headway_seconds"]),
    on=["route_id", "direction_id", "stop_id", "trip_id", "arrival_time"],
    how="left",
)

In [75]:
print(data.select(
    pl.col("headway_seconds").min().alias("min"),
    pl.col("headway_seconds").max().alias("max"),
    pl.col("headway_seconds").median().alias("median"),
))
print("null headway rows (first bus of the day at that stop):",
      data.filter(pl.col("headway_seconds").is_null()).height)

shape: (1, 3)
┌─────┬───────┬────────┐
│ min ┆ max   ┆ median │
│ --- ┆ ---   ┆ ---    │
│ i64 ┆ i64   ┆ f64    │
╞═════╪═══════╪════════╡
│ 0   ┆ 49277 ┆ 638.0  │
└─────┴───────┴────────┘
null headway rows (first bus of the day at that stop): 692

In [76]:
calendar_df = pl.read_parquet("calendar_dataset.parquet")
calendar_df = calendar_df.with_columns(
    pl.col("service_date").str.strptime(pl.Date, "%Y-%m-%d")
)

calendar_df = calendar_df.select([
    "service_date",
    "is_weekend",
    "is_federal_holiday",
    "is_school_day",
    "major_event_count",
]).with_columns(
    (pl.col("major_event_count") > 0).alias("has_major_event")
)
 
n_before = data.height
 
data = data.join(calendar_df, on="service_date", how="left")
 
print(f"rows before: {n_before:,} | after calendar join: {data.height:,}")
print("null calendar rows (service_date outside 2026-03-01 to 2026-07-17):",
      data.filter(pl.col("is_federal_holiday").is_null()).height)

rows before: 67,196 | after calendar join: 67,196
null calendar rows (service_date outside 2026-03-01 to 2026-07-17): 0

In [77]:
data

shape: (67_196, 61)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ tri ┆ sta ┆ sto ┆ fee ┆ fet ┆ sta ┆ sch ┆ veh ┆ tri ┆ sto ┆ arr ┆ dep ┆ eve ┆ rou ┆ dir ┆ sha ┆ ser ┆ sto ┆ sch ┆ sch ┆ sto ┆ sto ┆ veh ┆ lat ┆ lon ┆ bea ┆ spe ┆ nex ┆ tra ┆ eve ┆ hou ┆ wee ┆ mon ┆ is_ ┆ sch ┆ tri ┆ nex ┆ seg ┆ seg ┆ sch ┆ tem ┆ pre ┆ rai ┆ sno ┆ win ┆ wea ┆ is_ ┆ is_ ┆ is_ ┆ ser ┆ sch ┆ del ┆ rid ┆ tra ┆ ups ┆ hea ┆ is_ ┆ is_ ┆ is_ ┆ maj ┆ has │
│ p_i ┆ rt_ ┆ p_s ┆ d_t ┆ ch_ ┆ rt_ ┆ edu ┆ icl ┆ p_t ┆ p_i ┆ iva ┆ art ┆ nt_ ┆ te_ ┆ ect ┆ pe_ ┆ vic ┆ p_i ┆ edu ┆ edu ┆ p_l ┆ p_l ┆ icl ┆ itu ┆ git ┆ rin ┆ ed_ ┆ t_a ┆ vel ┆ nt_ ┆ r   ┆ kda ┆ th  ┆ pea ┆ edu ┆ p_p ┆ t_s ┆ men ┆ men ┆ edu ┆ per ┆ cip ┆ n_m ┆ wfa ┆ dsp ┆ the ┆ rai ┆ sno ┆ fog ┆ vic ┆ edu ┆ ay_ ┆ ers ┆ nsf ┆ tre ┆ dwa ┆ wee ┆ fed ┆ sch ┆ or_ ┆ _ma │
│ d   ┆ dat ┆ equ ┆ ime ┆ tim ┆ tim ┆ le_ ┆ e_i ┆ ime ┆ d   ┆ l_t ┆ ure ┆ tim ┆ id  ┆ ion ┆ id  ┆ e_i ┆ d_r ┆ led ┆ led ┆ at  ┆ on  ┆ e_t ┆ de  ┆ ude ┆ g   ┆ mps ┆ rri ┆ _ti ┆ tim ┆ --- ┆ y   ┆ --- ┆ k   ┆ led ┆ rog ┆ top ┆ t_l ┆ t_s ┆ led ┆ atu ┆ ita ┆ m   ┆ ll_ ┆ eed ┆ rco ┆ nin ┆ win ┆ --- ┆ e_d ┆ led ┆ sec ┆ hip ┆ ers ┆ am_ ┆ y_s ┆ ken ┆ era ┆ ool ┆ eve ┆ jor │
│ --- ┆ e   ┆ enc ┆ sta ┆ est ┆ e   ┆ rel ┆ d   ┆ sta ┆ --- ┆ ime ┆ _ti ┆ e   ┆ --- ┆ _id ┆ --- ┆ d   ┆ igh ┆ _ar ┆ _de ┆ --- ┆ --- ┆ ime ┆ --- ┆ --- ┆ --- ┆ --- ┆ val ┆ me  ┆ e_l ┆ i8  ┆ --- ┆ i8  ┆ --- ┆ _se ┆ res ┆ _id ┆ eng ┆ che ┆ _se ┆ re_ ┆ tio ┆ --- ┆ cm  ┆ _km ┆ de  ┆ g   ┆ g   ┆ i8  ┆ ate ┆ _ar ┆ ond ┆ --- ┆ --- ┆ del ┆ eco ┆ d   ┆ l_h ┆ _da ┆ nt_ ┆ _ev │
│ str ┆ --- ┆ e   ┆ mp  ┆ amp ┆ --- ┆ ati ┆ --- ┆ mp  ┆ str ┆ --- ┆ me  ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ t   ┆ riv ┆ par ┆ f64 ┆ f64 ┆ --- ┆ f32 ┆ f32 ┆ f32 ┆ f64 ┆ _ti ┆ --- ┆ oca ┆     ┆ i8  ┆     ┆ i8  ┆ gme ┆ s   ┆ --- ┆ th  ┆ dul ┆ gme ┆ c   ┆ n_m ┆ f64 ┆ --- ┆ h   ┆ --- ┆ --- ┆ --- ┆     ┆ --- ┆ riv ┆ s   ┆ i64 ┆ i64 ┆ ay_ ┆ nds ┆ --- ┆ oli ┆ y   ┆ cou ┆ ent │
│     ┆ str ┆ --- ┆ --- ┆ --- ┆ str ┆ ons ┆ str ┆ --- ┆     ┆ i64 ┆ --- ┆ dat ┆     ┆ i64 ┆     ┆ str ┆ --- ┆ al  ┆ tur ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆ me  ┆ i64 ┆ l   ┆     ┆     ┆     ┆     ┆ nt_ ┆ --- ┆ str ┆ --- ┆ ed_ ┆ nt_ ┆ --- ┆ m   ┆     ┆ f64 ┆ --- ┆ i64 ┆ i8  ┆ i8  ┆     ┆ dat ┆ al_ ┆ --- ┆     ┆     ┆ sec ┆ --- ┆ boo ┆ day ┆ --- ┆ nt  ┆ --- │
│     ┆     ┆ u32 ┆ u64 ┆ dat ┆     ┆ hip ┆     ┆ u64 ┆     ┆     ┆ i64 ┆ eti ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ e   ┆     ┆     ┆ eti ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ tim ┆ f64 ┆     ┆ f64 ┆ tra ┆ spe ┆ f64 ┆ --- ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆ e   ┆ epo ┆ i64 ┆     ┆     ┆ ond ┆ i64 ┆ l   ┆ --- ┆ boo ┆ --- ┆ boo │
│     ┆     ┆     ┆     ┆ eti ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆ --- ┆     ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆ dat ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ vel ┆ ed_ ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ch  ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ boo ┆ l   ┆ u32 ┆ l   │
│     ┆     ┆     ┆     ┆ me[ ┆     ┆ i32 ┆     ┆     ┆     ┆     ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆     ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆     ┆ eti ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ _ti ┆ mps ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ l   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ μs, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆ i32 ┆     ┆     ┆     ┆ me  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ UTC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ μs, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ ]   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ame ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ric ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a/N ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ew_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Yor ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ k]  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ MV_ ┆ 202 ┆ 70  ┆ 178 ┆ 202 ┆     ┆ 0   ┆ MTA ┆ 178 ┆ 400 ┆ 178 ┆ 178 ┆ 202 ┆ M4  ┆ 0   ┆ M04 ┆ MV_ ┆ 400 ┆ 718 ┆ 718 ┆ 40. ┆ -73 ┆ 202 ┆ 40. ┆ -73 ┆ 67. ┆ nul ┆ 178 ┆ 86  ┆ 202 ┆ 20  ┆ 2   ┆ 6   ┆ 0   ┆ nul ┆ 0.9 ┆ 400 ┆ 153 ┆ 35  ┆ 4.3 ┆ 31. ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 9.5 ┆ 2   ┆ 0   ┆ 0   ┆ 0   ┆ 202 ┆ 178 ┆ 193 ┆ 267 ┆ 45  ┆ nul ┆ nul ┆ fal ┆ fal ┆ fal ┆ 0   ┆ fal │
│ C6- ┆ 606 ┆     ┆ 286 ┆ 6-0 ┆     ┆     ┆ NYC ┆ 286 ┆ 629 ┆ 286 ┆ 286 ┆ 6-0 ┆     ┆     ┆ 092 ┆ C6- ┆ 629 ┆ 25  ┆ 25  ┆ 847 ┆ .93 ┆ 6-0 ┆ 847 ┆ .93 ┆ 574 ┆ l   ┆ 286 ┆     ┆ 6-0 ┆     ┆     ┆     ┆     ┆ l   ┆ 210 ┆ 630 ┆ .41 ┆     ┆ 833 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6-0 ┆ 286 ┆     ┆     ┆     ┆ l   ┆ l   ┆ se  ┆ se  ┆ se  ┆     ┆ se  │
│ Wee ┆ 30  ┆     ┆ 400 ┆ 7-0 ┆     ┆     ┆ T_9 ┆ 399 ┆     ┆ 401 ┆ 401 ┆ 7-0 ┆     ┆     ┆ 3   ┆ Wee ┆     ┆     ┆     ┆ 906 ┆ 940 ┆ 6-3 ┆ 366 ┆ 971 ┆ 135 ┆     ┆ 410 ┆     ┆ 6-3 ┆     ┆     ┆     ┆     ┆     ┆ 53  ┆     ┆ 805 ┆     ┆ 73  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6-3 ┆ 382 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ kda ┆     ┆     ┆ 3   ┆ 1   ┆     ┆     ┆ 760 ┆ 4   ┆     ┆ 8   ┆ 8   ┆ 1   ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆ 7   ┆ 0   ┆     ┆ 3   ┆     ┆     ┆ 4   ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ y-1 ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆ 23: ┆     ┆     ┆     ┆     ┆     ┆     ┆ 20: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 109 ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 59: ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 00_ ┆     ┆     ┆     ┆ 28. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 18  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 54  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 18  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ M4_ ┆     ┆     ┆     ┆ 366 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ EDT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 447 ┆     ┆     ┆     ┆ 841 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ UTC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ MV_ ┆ 202 ┆ 71  ┆ 178 ┆ 202 ┆     ┆ 0   ┆ MTA ┆ 178 ┆ 400 ┆ 178 ┆ 178 ┆ 202 ┆ M4  ┆ 0   ┆ M04 ┆ MV_ ┆ 400 ┆ 718 ┆ 718 ┆ 40. ┆ -73 ┆ 202 ┆ 40. ┆ -73 ┆ 61. ┆ 0.5 ┆ 178 ┆ 77  ┆ 202 ┆ 20  ┆ 2   ┆ 6   ┆ 0   ┆ 44  ┆ 0.9 ┆ 400 ┆ 230 ┆ 52  ┆ 4.4 ┆ 31. ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 9.5 ┆ 2   ┆ 0   ┆ 0   ┆ 0   ┆ 202 ┆ 178 ┆ 235 ┆ 267 ┆ 45  ┆ 193 ┆ nul ┆ fal ┆ fal ┆ fal ┆ 0   ┆ fal │
│ C6- ┆ 606 ┆     ┆ 286 ┆ 6-0 ┆     ┆     ┆ NYC ┆ 286 ┆ 630 ┆ 286 ┆ 286 ┆ 6-0 ┆     ┆     ┆ 092 ┆ C6- ┆ 630 ┆ 69  ┆ 69  ┆ 849 ┆ .93 ┆ 6-0 ┆ 849 ┆ .93 ┆ 927 ┆ 783 ┆ 286 ┆     ┆ 6-0 ┆     ┆     ┆     ┆     ┆     ┆ 342 ┆ 631 ┆ .31 ┆     ┆ 291 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6-0 ┆ 286 ┆     ┆     ┆     ┆     ┆ l   ┆ se  ┆ se  ┆ se  ┆     ┆ se  │
│ Wee ┆ 30  ┆     ┆ 410 ┆ 7-0 ┆     ┆     ┆ T_9 ┆ 408 ┆     ┆ 410 ┆ 410 ┆ 7-0 ┆     ┆     ┆ 3   ┆ Wee ┆     ┆     ┆     ┆ 229 ┆ 893 ┆ 7-0 ┆ 068 ┆ 907 ┆ 513 ┆ 04  ┆ 418 ┆     ┆ 6-3 ┆     ┆     ┆     ┆     ┆     ┆ 11  ┆     ┆ 597 ┆     ┆ 53  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6-3 ┆ 386 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ kda ┆     ┆     ┆ 7   ┆ 1   ┆     ┆     ┆ 760 ┆ 4   ┆     ┆ 4   ┆ 4   ┆ 1   ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆ 2   ┆ 1   ┆     ┆ 2   ┆     ┆     ┆ 1   ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ y-1 ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆ 20: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 109 ┆     ┆     ┆     ┆ 01: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 01: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 01: ┆     ┆     ┆     ┆     ┆     ┆     ┆ 01: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 00_ ┆     ┆     ┆     ┆ 58. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 44  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 24  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 44  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ M4_ ┆     ┆     ┆     ┆ 841 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ EDT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 447 ┆     ┆     ┆     ┆ 053 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ UTC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ MV_ ┆ 202 ┆ 72  ┆ 178 ┆ 202 ┆     ┆ 0   ┆ MTA ┆ 178 ┆ 400 ┆ 178 ┆ 178 ┆ 202 ┆ M4  ┆ 0   ┆ M04 ┆ MV_ ┆ 400 ┆ 719 ┆ 719 ┆ 40. ┆ -73 ┆ 202 ┆ 40. ┆ -73 ┆ 69. ┆ 0.4 ┆ 178 ┆ 57  ┆ 202 ┆ 20  ┆ 2   ┆ 6   ┆ 0   ┆ 65  ┆ 0.9 ┆ 400 ┆ 137 ┆ 31  ┆ 4.4 ┆ 31. ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 9.5 ┆ 2   ┆ 0   ┆ 0   ┆ 0   ┆ 202 ┆ 178 ┆ 247 ┆ 267 ┆ 45  ┆ 235 ┆ nul ┆ fal ┆ fal ┆ fal ┆ 0   ┆ fal │
│ C6- ┆ 606 ┆     ┆ 286 ┆ 6-0 ┆     ┆     ┆ NYC ┆ 286 ┆ 631 ┆ 286 ┆ 286 ┆ 6-0 ┆     ┆     ┆ 092 ┆ C6- ┆ 631 ┆ 34  ┆ 34  ┆ 851 ┆ .93 ┆ 6-0 ┆ 851 ┆ .93 ┆ 819 ┆ 703 ┆ 286 ┆     ┆ 6-0 ┆     ┆     ┆     ┆     ┆     ┆ 473 ┆ 632 ┆ .22 ┆     ┆ 266 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6-0 ┆ 286 ┆     ┆     ┆     ┆     ┆ l   ┆ se  ┆ se  ┆ se  ┆     ┆ se  │
│ Wee ┆ 30  ┆     ┆ 418 ┆ 7-0 ┆     ┆     ┆ T_9 ┆ 417 ┆     ┆ 418 ┆ 418 ┆ 7-0 ┆     ┆     ┆ 3   ┆ Wee ┆     ┆     ┆     ┆ 202 ┆ 807 ┆ 7-0 ┆ 707 ┆ 798 ┆ 817 ┆ 03  ┆ 423 ┆     ┆ 6-3 ┆     ┆     ┆     ┆     ┆     ┆ 68  ┆     ┆ 478 ┆     ┆ 06  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6-3 ┆ 393 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ kda ┆     ┆     ┆ 0   ┆ 1   ┆     ┆     ┆ 760 ┆ 4   ┆     ┆ 1   ┆ 1   ┆ 1   ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆ 8   ┆ 1   ┆     ┆ 1   ┆     ┆     ┆ 8   ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ y-1 ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆ 20: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 109 ┆     ┆     ┆     ┆ 03: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 03: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 02: ┆     ┆     ┆     ┆     ┆     ┆     ┆ 03: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 00_ ┆     ┆     ┆     ┆ 28. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 01  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 54  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 01  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ M4_ ┆     ┆     ┆     ┆ 367 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ EDT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 447 ┆     ┆     ┆     ┆ 952 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ UTC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ MV_ ┆ 202 ┆ 73  ┆ 178 ┆ 202 ┆     ┆ 0   ┆ MTA ┆ 178 ┆ 400 ┆ 178 ┆ 178 ┆ 202 ┆ M4  ┆ 0   ┆ M04 ┆ MV_ ┆ 400 ┆ 719 ┆ 719 ┆ 40. ┆ -73 ┆ 202 ┆ 40. ┆ -73 ┆ 72. ┆ 1.5 ┆ 178 ┆ 37  ┆ 202 ┆ 20  ┆ 2   ┆ 6   ┆ 0   ┆ 39  ┆ 0.9 ┆ 400 ┆ 141 ┆ 32  ┆ 4.4 ┆ 31. ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 9.5 ┆ 2   ┆ 0   ┆ 0   ┆ 0   ┆ 202 ┆ 178 ┆ 265 ┆ 267 ┆ 45  ┆ 247 ┆ nul ┆ fal ┆ fal ┆ fal ┆ 0   ┆ fal │
│ C6- ┆ 606 ┆     ┆ 286 ┆ 6-0 ┆     ┆     ┆ NYC ┆ 286 ┆ 632 ┆ 286 ┆ 286 ┆ 6-0 ┆     ┆     ┆ 092 ┆ C6- ┆ 632 ┆ 73  ┆ 73  ┆ 852 ┆ .93 ┆ 6-0 ┆ 852 ┆ .93 ┆ 790 ┆ 284 ┆ 286 ┆     ┆ 6-0 ┆     ┆     ┆     ┆     ┆     ┆ 605 ┆ 633 ┆ .95 ┆     ┆ 361 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6-0 ┆ 286 ┆     ┆     ┆     ┆     ┆ l   ┆ se  ┆ se  ┆ se  ┆     ┆ se  │
│ Wee ┆ 30  ┆     ┆ 425 ┆ 7-0 ┆     ┆     ┆ T_9 ┆ 423 ┆     ┆ 423 ┆ 423 ┆ 7-0 ┆     ┆     ┆ 3   ┆ Wee ┆     ┆     ┆     ┆ 396 ┆ 765 ┆ 7-0 ┆ 718 ┆ 763 ┆ 443 ┆ 95  ┆ 427 ┆     ┆ 6-3 ┆     ┆     ┆     ┆     ┆     ┆ 26  ┆     ┆ 774 ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6-3 ┆ 397 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ kda ┆     ┆     ┆ 3   ┆ 1   ┆     ┆     ┆ 760 ┆ 4   ┆     ┆ 8   ┆ 8   ┆ 1   ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆ 4   ┆ 1   ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ y-1 ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆ 20: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [78]:
data.shape

(67196, 61)

In [79]:
data.null_count()

shape: (1, 61)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ tri ┆ sta ┆ sto ┆ fee ┆ fet ┆ sta ┆ sch ┆ veh ┆ tri ┆ sto ┆ arr ┆ dep ┆ eve ┆ rou ┆ dir ┆ sha ┆ ser ┆ sto ┆ sch ┆ sch ┆ sto ┆ sto ┆ veh ┆ lat ┆ lon ┆ bea ┆ spe ┆ nex ┆ tra ┆ eve ┆ hou ┆ wee ┆ mon ┆ is_ ┆ sch ┆ tri ┆ nex ┆ seg ┆ seg ┆ sch ┆ tem ┆ pre ┆ rai ┆ sno ┆ win ┆ wea ┆ is_ ┆ is_ ┆ is_ ┆ ser ┆ sch ┆ del ┆ rid ┆ tra ┆ ups ┆ hea ┆ is_ ┆ is_ ┆ is_ ┆ maj ┆ has │
│ p_i ┆ rt_ ┆ p_s ┆ d_t ┆ ch_ ┆ rt_ ┆ edu ┆ icl ┆ p_t ┆ p_i ┆ iva ┆ art ┆ nt_ ┆ te_ ┆ ect ┆ pe_ ┆ vic ┆ p_i ┆ edu ┆ edu ┆ p_l ┆ p_l ┆ icl ┆ itu ┆ git ┆ rin ┆ ed_ ┆ t_a ┆ vel ┆ nt_ ┆ r   ┆ kda ┆ th  ┆ pea ┆ edu ┆ p_p ┆ t_s ┆ men ┆ men ┆ edu ┆ per ┆ cip ┆ n_m ┆ wfa ┆ dsp ┆ the ┆ rai ┆ sno ┆ fog ┆ vic ┆ edu ┆ ay_ ┆ ers ┆ nsf ┆ tre ┆ dwa ┆ wee ┆ fed ┆ sch ┆ or_ ┆ _ma │
│ d   ┆ dat ┆ equ ┆ ime ┆ tim ┆ tim ┆ le_ ┆ e_i ┆ ime ┆ d   ┆ l_t ┆ ure ┆ tim ┆ id  ┆ ion ┆ id  ┆ e_i ┆ d_r ┆ led ┆ led ┆ at  ┆ on  ┆ e_t ┆ de  ┆ ude ┆ g   ┆ mps ┆ rri ┆ _ti ┆ tim ┆ --- ┆ y   ┆ --- ┆ k   ┆ led ┆ rog ┆ top ┆ t_l ┆ t_s ┆ led ┆ atu ┆ ita ┆ m   ┆ ll_ ┆ eed ┆ rco ┆ nin ┆ win ┆ --- ┆ e_d ┆ led ┆ sec ┆ hip ┆ ers ┆ am_ ┆ y_s ┆ ken ┆ era ┆ ool ┆ eve ┆ jor │
│ --- ┆ e   ┆ enc ┆ sta ┆ est ┆ e   ┆ rel ┆ d   ┆ sta ┆ --- ┆ ime ┆ _ti ┆ e   ┆ --- ┆ _id ┆ --- ┆ d   ┆ igh ┆ _ar ┆ _de ┆ --- ┆ --- ┆ ime ┆ --- ┆ --- ┆ --- ┆ --- ┆ val ┆ me  ┆ e_l ┆ u32 ┆ --- ┆ u32 ┆ --- ┆ _se ┆ res ┆ _id ┆ eng ┆ che ┆ _se ┆ re_ ┆ tio ┆ --- ┆ cm  ┆ _km ┆ de  ┆ g   ┆ g   ┆ u32 ┆ ate ┆ _ar ┆ ond ┆ --- ┆ --- ┆ del ┆ eco ┆ d   ┆ l_h ┆ _da ┆ nt_ ┆ _ev │
│ u32 ┆ --- ┆ e   ┆ mp  ┆ amp ┆ --- ┆ ati ┆ --- ┆ mp  ┆ u32 ┆ --- ┆ me  ┆ --- ┆ u32 ┆ --- ┆ u32 ┆ --- ┆ t   ┆ riv ┆ par ┆ u32 ┆ u32 ┆ --- ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ _ti ┆ --- ┆ oca ┆     ┆ u32 ┆     ┆ u32 ┆ gme ┆ s   ┆ --- ┆ th  ┆ dul ┆ gme ┆ c   ┆ n_m ┆ u32 ┆ --- ┆ h   ┆ --- ┆ --- ┆ --- ┆     ┆ --- ┆ riv ┆ s   ┆ u32 ┆ u32 ┆ ay_ ┆ nds ┆ --- ┆ oli ┆ y   ┆ cou ┆ ent │
│     ┆ u32 ┆ --- ┆ --- ┆ --- ┆ u32 ┆ ons ┆ u32 ┆ --- ┆     ┆ u32 ┆ --- ┆ u32 ┆     ┆ u32 ┆     ┆ u32 ┆ --- ┆ al  ┆ tur ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆ me  ┆ u32 ┆ l   ┆     ┆     ┆     ┆     ┆ nt_ ┆ --- ┆ u32 ┆ --- ┆ ed_ ┆ nt_ ┆ --- ┆ m   ┆     ┆ u32 ┆ --- ┆ u32 ┆ u32 ┆ u32 ┆     ┆ u32 ┆ al_ ┆ --- ┆     ┆     ┆ sec ┆ --- ┆ u32 ┆ day ┆ --- ┆ nt  ┆ --- │
│     ┆     ┆ u32 ┆ u32 ┆ u32 ┆     ┆ hip ┆     ┆ u32 ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ tim ┆ u32 ┆     ┆ u32 ┆ tra ┆ spe ┆ u32 ┆ --- ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆ epo ┆ u32 ┆     ┆     ┆ ond ┆ u32 ┆     ┆ --- ┆ u32 ┆ --- ┆ u32 │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ vel ┆ ed_ ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ch  ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ u32 ┆     ┆ u32 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ _ti ┆ mps ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆ me  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 623 ┆ 623 ┆ 623 ┆ 623 ┆ 628 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 131 ┆ 0   ┆ 131 ┆ 294 ┆ 294 ┆ 294 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 131 ┆ 692 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆ 4   ┆ 9   ┆ 9   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [80]:
features = [
    "route_id",
    "direction_id",
    "shape_id",
    "service_id",
 
    "stop_sequence",
    "trip_progress",
 
    "hour",
    "weekday",
    "month",
    "is_peak",
 
    "scheduled_arrival",
    "scheduled_departure",
    "scheduled_segment_time",
 
    "stop_lat",
    "stop_lon",
 
    "latitude",
    "longitude",
    "bearing",
    "temperature_c",
    "precipitation_mm",
    "snowfall_cm",
    "windspeed_kmh",
    "is_raining",
    "is_snowing",
    "is_fog",
    "weathercode",
    "segment_length",
    "scheduled_segment_speed_mps",
    "upstream_delay_seconds",
    "speed_mps",
    "headway_seconds",
    "is_weekend",
    "is_federal_holiday",
    "is_school_day",
    "has_major_event",

    
    "ridership",
    "transfers",
]
target = "travel_time"
id_cols = ["trip_id", "start_date"]
 
print(data.columns)
 
# %%
model_ready = data.select(id_cols + features + [target]).drop_nulls(subset=features + [target])
 
print(model_ready.shape)
print(model_ready.null_count())
print(model_ready.head())

['trip_id', 'start_date', 'stop_sequence', 'feed_timestamp', 'fetch_timestamp', 'start_time', 'schedule_relationship', 'vehicle_id', 'trip_timestamp', 'stop_id', 'arrival_time', 'departure_time', 'event_time', 'route_id', 'direction_id', 'shape_id', 'service_id', 'stop_id_right', 'scheduled_arrival', 'scheduled_departure', 'stop_lat', 'stop_lon', 'vehicle_time', 'latitude', 'longitude', 'bearing', 'speed_mps', 'next_arrival_time', 'travel_time', 'event_time_local', 'hour', 'weekday', 'month', 'is_peak', 'scheduled_segment_time', 'trip_progress', 'next_stop_id', 'segment_length', 'segment_scheduled_travel_time', 'scheduled_segment_speed_mps', 'temperature_c', 'precipitation_mm', 'rain_mm', 'snowfall_cm', 'windspeed_kmh', 'weathercode', 'is_raining', 'is_snowing', 'is_fog', 'service_date', 'scheduled_arrival_epoch', 'delay_seconds', 'ridership', 'transfers', 'upstream_delay_seconds', 'headway_seconds', 'is_weekend', 'is_federal_holiday', 'is_school_day', 'major_event_count', 'has_major_event']
(56764, 40)
shape: (1, 40)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┬───────┬───────┬───────┐
│ tri ┆ sta ┆ rou ┆ dir ┆ sha ┆ ser ┆ sto ┆ tri ┆ hou ┆ wee ┆ mon ┆ is_ ┆ sch ┆ sch ┆ sch ┆ sto ┆ sto ┆ lat ┆ lon ┆ bea ┆ tem ┆ pre ┆ sno ┆ win ┆ is_ ┆ is_ ┆ is_ ┆ wea ┆ seg ┆ sch ┆ ups ┆ spe ┆ hea ┆ is_ ┆ is_ ┆ is_ ┆ has_ma ┆ rider ┆ trans ┆ trave │
│ p_i ┆ rt_ ┆ te_ ┆ ect ┆ pe_ ┆ vic ┆ p_s ┆ p_p ┆ r   ┆ kda ┆ th  ┆ pea ┆ edu ┆ edu ┆ edu ┆ p_l ┆ p_l ┆ itu ┆ git ┆ rin ┆ per ┆ cip ┆ wfa ┆ dsp ┆ rai ┆ sno ┆ fog ┆ the ┆ men ┆ edu ┆ tre ┆ ed_ ┆ dwa ┆ wee ┆ fed ┆ sch ┆ jor_ev ┆ ship  ┆ fers  ┆ l_tim │
│ d   ┆ dat ┆ id  ┆ ion ┆ id  ┆ e_i ┆ equ ┆ rog ┆ --- ┆ y   ┆ --- ┆ k   ┆ led ┆ led ┆ led ┆ at  ┆ on  ┆ de  ┆ ude ┆ g   ┆ atu ┆ ita ┆ ll_ ┆ eed ┆ nin ┆ win ┆ --- ┆ rco ┆ t_l ┆ led ┆ am_ ┆ mps ┆ y_s ┆ ken ┆ era ┆ ool ┆ ent    ┆ ---   ┆ ---   ┆ e     │
│ --- ┆ e   ┆ --- ┆ _id ┆ --- ┆ d   ┆ enc ┆ res ┆ u32 ┆ --- ┆ u32 ┆ --- ┆ _ar ┆ _de ┆ _se ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ re_ ┆ tio ┆ cm  ┆ _km ┆ g   ┆ g   ┆ u32 ┆ de  ┆ eng ┆ _se ┆ del ┆ --- ┆ eco ┆ d   ┆ l_h ┆ _da ┆ ---    ┆ u32   ┆ u32   ┆ ---   │
│ u32 ┆ --- ┆ u32 ┆ --- ┆ u32 ┆ --- ┆ e   ┆ s   ┆     ┆ u32 ┆     ┆ u32 ┆ riv ┆ par ┆ gme ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ c   ┆ n_m ┆ --- ┆ h   ┆ --- ┆ --- ┆     ┆ --- ┆ th  ┆ gme ┆ ay_ ┆ u32 ┆ nds ┆ --- ┆ oli ┆ y   ┆ u32    ┆       ┆       ┆ u32   │
│     ┆ u32 ┆     ┆ u32 ┆     ┆ u32 ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ al  ┆ tur ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ m   ┆ u32 ┆ --- ┆ u32 ┆ u32 ┆     ┆ u32 ┆ --- ┆ nt_ ┆ sec ┆     ┆ --- ┆ u32 ┆ day ┆ --- ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ u32 ┆     ┆     ┆     ┆     ┆ --- ┆ e   ┆ tim ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆ u32 ┆ spe ┆ ond ┆     ┆ u32 ┆     ┆ --- ┆ u32 ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed_ ┆ s   ┆     ┆     ┆     ┆ u32 ┆     ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mps ┆ --- ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╪═══════╪═══════╪═══════╡
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0      ┆ 0     ┆ 0     ┆ 0     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴────────┴───────┴───────┴───────┘
shape: (5, 40)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┬───────┬───────┬───────┐
│ tri ┆ sta ┆ rou ┆ dir ┆ sha ┆ ser ┆ sto ┆ tri ┆ hou ┆ wee ┆ mon ┆ is_ ┆ sch ┆ sch ┆ sch ┆ sto ┆ sto ┆ lat ┆ lon ┆ bea ┆ tem ┆ pre ┆ sno ┆ win ┆ is_ ┆ is_ ┆ is_ ┆ wea ┆ seg ┆ sch ┆ ups ┆ spe ┆ hea ┆ is_ ┆ is_ ┆ is_ ┆ has_ma ┆ rider ┆ trans ┆ trave │
│ p_i ┆ rt_ ┆ te_ ┆ ect ┆ pe_ ┆ vic ┆ p_s ┆ p_p ┆ r   ┆ kda ┆ th  ┆ pea ┆ edu ┆ edu ┆ edu ┆ p_l ┆ p_l ┆ itu ┆ git ┆ rin ┆ per ┆ cip ┆ wfa ┆ dsp ┆ rai ┆ sno ┆ fog ┆ the ┆ men ┆ edu ┆ tre ┆ ed_ ┆ dwa ┆ wee ┆ fed ┆ sch ┆ jor_ev ┆ ship  ┆ fers  ┆ l_tim │
│ d   ┆ dat ┆ id  ┆ ion ┆ id  ┆ e_i ┆ equ ┆ rog ┆ --- ┆ y   ┆ --- ┆ k   ┆ led ┆ led ┆ led ┆ at  ┆ on  ┆ de  ┆ ude ┆ g   ┆ atu ┆ ita ┆ ll_ ┆ eed ┆ nin ┆ win ┆ --- ┆ rco ┆ t_l ┆ led ┆ am_ ┆ mps ┆ y_s ┆ ken ┆ era ┆ ool ┆ ent    ┆ ---   ┆ ---   ┆ e     │
│ --- ┆ e   ┆ --- ┆ _id ┆ --- ┆ d   ┆ enc ┆ res ┆ i8  ┆ --- ┆ i8  ┆ --- ┆ _ar ┆ _de ┆ _se ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ re_ ┆ tio ┆ cm  ┆ _km ┆ g   ┆ g   ┆ i8  ┆ de  ┆ eng ┆ _se ┆ del ┆ --- ┆ eco ┆ d   ┆ l_h ┆ _da ┆ ---    ┆ i64   ┆ i64   ┆ ---   │
│ str ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ e   ┆ s   ┆     ┆ i8  ┆     ┆ i8  ┆ riv ┆ par ┆ gme ┆ f64 ┆ f64 ┆ f32 ┆ f32 ┆ f32 ┆ c   ┆ n_m ┆ --- ┆ h   ┆ --- ┆ --- ┆     ┆ --- ┆ th  ┆ gme ┆ ay_ ┆ f64 ┆ nds ┆ --- ┆ oli ┆ y   ┆ bool   ┆       ┆       ┆ i64   │
│     ┆ str ┆     ┆ i64 ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ al  ┆ tur ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ m   ┆ f64 ┆ --- ┆ i8  ┆ i8  ┆     ┆ i64 ┆ --- ┆ nt_ ┆ sec ┆     ┆ --- ┆ boo ┆ day ┆ --- ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ f64 ┆     ┆     ┆     ┆     ┆ --- ┆ e   ┆ tim ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆ f64 ┆ spe ┆ ond ┆     ┆ i64 ┆ l   ┆ --- ┆ boo ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆ --- ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed_ ┆ s   ┆     ┆     ┆     ┆ boo ┆ l   ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mps ┆ --- ┆     ┆     ┆     ┆ l   ┆     ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╪═══════╪═══════╪═══════╡
│ MV_ ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 41  ┆ 0.9 ┆ 20  ┆ 2   ┆ 6   ┆ 0   ┆ 716 ┆ 716 ┆ 70  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 47. ┆ 31. ┆ 0.0 ┆ 0.0 ┆ 9.5 ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 168 ┆ 3.0 ┆ 608 ┆ 72. ┆ 8   ┆ fal ┆ fal ┆ fal ┆ false  ┆ 226   ┆ 35    ┆ 40    │
│ C6- ┆ 606 ┆     ┆     ┆ 009 ┆ C6- ┆     ┆ 111 ┆     ┆     ┆     ┆     ┆ 22  ┆ 22  ┆     ┆ 832 ┆ .93 ┆ 833 ┆ .93 ┆ 511 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .38 ┆ 615 ┆     ┆ 608 ┆     ┆ se  ┆ se  ┆ se  ┆        ┆       ┆       ┆       │
│ Wee ┆ 30  ┆     ┆     ┆ 2   ┆ Wee ┆     ┆ 11  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 912 ┆ 946 ┆ 019 ┆ 944 ┆ 364 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 363 ┆ 21  ┆     ┆ 229 ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-1 ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 117 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 00_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ M3_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 326 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ MV_ ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 42  ┆ 0.9 ┆ 20  ┆ 2   ┆ 6   ┆ 0   ┆ 716 ┆ 716 ┆ 48  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 65. ┆ 31. ┆ 0.0 ┆ 0.0 ┆ 9.5 ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 142 ┆ 3.0 ┆ 586 ┆ 8.5 ┆ 9   ┆ fal ┆ fal ┆ fal ┆ false  ┆ 226   ┆ 35    ┆ 5     │
│ C6- ┆ 606 ┆     ┆     ┆ 009 ┆ C6- ┆     ┆ 333 ┆     ┆     ┆     ┆     ┆ 70  ┆ 70  ┆     ┆ 834 ┆ .93 ┆ 835 ┆ .93 ┆ 207 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .31 ┆ 279 ┆     ┆ 923 ┆     ┆ se  ┆ se  ┆ se  ┆        ┆       ┆       ┆       │
│ Wee ┆ 30  ┆     ┆     ┆ 2   ┆ Wee ┆     ┆ 33  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 045 ┆ 813 ┆ 564 ┆ 743 ┆ 558 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 313 ┆ 39  ┆     ┆ 68  ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-1 ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 117 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 00_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ M3_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 326 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ MV_ ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 43  ┆ 0.9 ┆ 20  ┆ 2   ┆ 6   ┆ 0   ┆ 717 ┆ 717 ┆ 41  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 65. ┆ 31. ┆ 0.0 ┆ 0.0 ┆ 9.5 ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 166 ┆ 3.0 ┆ 578 ┆ 8.5 ┆ 5   ┆ fal ┆ fal ┆ fal ┆ false  ┆ 226   ┆ 35    ┆ 56    │
│ C6- ┆ 606 ┆     ┆     ┆ 009 ┆ C6- ┆     ┆ 555 ┆     ┆     ┆     ┆     ┆ 11  ┆ 11  ┆     ┆ 835 ┆ .93 ┆ 835 ┆ .93 ┆ 207 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .57 ┆ 286 ┆     ┆ 923 ┆     ┆ se  ┆ se  ┆ se  ┆        ┆       ┆       ┆       │
│ Wee ┆ 30  ┆     ┆     ┆ 2   ┆ Wee ┆     ┆ 56  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 242 ┆ 749 ┆ 564 ┆ 743 ┆ 558 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 416 ┆ 21  ┆     ┆ 68  ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-1 ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 117 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 00_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ M3_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 326 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ MV_ ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 44  ┆ 0.9 ┆ 20  ┆ 2   ┆ 6   ┆ 0   ┆ 717 ┆ 717 ┆ 47  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 65. ┆ 31. ┆ 0.0 ┆ 0.0 ┆ 9.5 ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 204 ┆ 3.0 ┆ 542 ┆ 2.4 ┆ 8   ┆ fal ┆ fal ┆ fal ┆ false  ┆ 226   ┆ 35    ┆ 90    │
│ C6- ┆ 606 ┆     ┆     ┆ 009 ┆ C6- ┆     ┆ 777 ┆     ┆     ┆     ┆     ┆ 58  ┆ 58  ┆     ┆ 836 ┆ .93 ┆ 836 ┆ .93 ┆ 556 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .71 ┆ 105 ┆     ┆ 770 ┆     ┆ se  ┆ se  ┆ se  ┆        ┆       ┆       ┆       │
│ Wee ┆ 30  ┆     ┆     ┆ 2   ┆ Wee ┆     ┆ 78  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 657 ┆ 685 ┆ 197 ┆ 714 ┆ 046 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 453 ┆ 08  ┆     ┆ 02  ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-1 ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 117 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 00_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ M3_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 326 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ MV_ ┆ 202 ┆ M4  ┆ 0   ┆ M04 ┆ MV_ ┆ 70  ┆ 0.9 ┆ 20  ┆ 2   ┆ 6   ┆ 0   ┆ 723 ┆ 723 ┆ 35  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 72. ┆ 31. ┆ 0.0 ┆ 0.0 ┆ 9.5 ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 153 ┆ 4.3 ┆ -19 ┆ 8.3 ┆ 100 ┆ fal ┆ fal ┆ fal ┆ false  ┆ 267   ┆ 45    ┆ 130   │
│ C6- ┆ 606 ┆     ┆     ┆ 092 ┆ C6- ┆     ┆ 210 ┆     ┆     ┆     ┆     ┆ 05  ┆ 05  ┆     ┆ 847 ┆ .93 ┆ 848 ┆ .93 ┆ 299 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .41 ┆ 833 ┆ 6   ┆ 643 ┆     ┆ se  ┆ se  ┆ se  ┆        ┆       ┆       ┆       │
│ Wee ┆ 30  ┆     ┆     ┆ 3   ┆ Wee ┆     ┆ 53  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 906 ┆ 940 ┆ 469 ┆ 930 ┆ 576 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 805 ┆ 73  ┆     ┆ 08  ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-1 ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 117 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 00_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ M5_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 528 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴────────┴───────┴───────┴───────┘

In [81]:
model_ready.columns

['trip_id',
 'start_date',
 'route_id',
 'direction_id',
 'shape_id',
 'service_id',
 'stop_sequence',
 'trip_progress',
 'hour',
 'weekday',
 'month',
 'is_peak',
 'scheduled_arrival',
 'scheduled_departure',
 'scheduled_segment_time',
 'stop_lat',
 'stop_lon',
 'latitude',
 'longitude',
 'bearing',
 'temperature_c',
 'precipitation_mm',
 'snowfall_cm',
 'windspeed_kmh',
 'is_raining',
 'is_snowing',
 'is_fog',
 'weathercode',
 'segment_length',
 'scheduled_segment_speed_mps',
 'upstream_delay_seconds',
 'speed_mps',
 'headway_seconds',
 'is_weekend',
 'is_federal_holiday',
 'is_school_day',
 'has_major_event',
 'ridership',
 'transfers',
 'travel_time']

In [82]:
model_ready

shape: (56_764, 40)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┬───────┬───────┬───────┐
│ tri ┆ sta ┆ rou ┆ dir ┆ sha ┆ ser ┆ sto ┆ tri ┆ hou ┆ wee ┆ mon ┆ is_ ┆ sch ┆ sch ┆ sch ┆ sto ┆ sto ┆ lat ┆ lon ┆ bea ┆ tem ┆ pre ┆ sno ┆ win ┆ is_ ┆ is_ ┆ is_ ┆ wea ┆ seg ┆ sch ┆ ups ┆ spe ┆ hea ┆ is_ ┆ is_ ┆ is_ ┆ has_ma ┆ rider ┆ trans ┆ trave │
│ p_i ┆ rt_ ┆ te_ ┆ ect ┆ pe_ ┆ vic ┆ p_s ┆ p_p ┆ r   ┆ kda ┆ th  ┆ pea ┆ edu ┆ edu ┆ edu ┆ p_l ┆ p_l ┆ itu ┆ git ┆ rin ┆ per ┆ cip ┆ wfa ┆ dsp ┆ rai ┆ sno ┆ fog ┆ the ┆ men ┆ edu ┆ tre ┆ ed_ ┆ dwa ┆ wee ┆ fed ┆ sch ┆ jor_ev ┆ ship  ┆ fers  ┆ l_tim │
│ d   ┆ dat ┆ id  ┆ ion ┆ id  ┆ e_i ┆ equ ┆ rog ┆ --- ┆ y   ┆ --- ┆ k   ┆ led ┆ led ┆ led ┆ at  ┆ on  ┆ de  ┆ ude ┆ g   ┆ atu ┆ ita ┆ ll_ ┆ eed ┆ nin ┆ win ┆ --- ┆ rco ┆ t_l ┆ led ┆ am_ ┆ mps ┆ y_s ┆ ken ┆ era ┆ ool ┆ ent    ┆ ---   ┆ ---   ┆ e     │
│ --- ┆ e   ┆ --- ┆ _id ┆ --- ┆ d   ┆ enc ┆ res ┆ i8  ┆ --- ┆ i8  ┆ --- ┆ _ar ┆ _de ┆ _se ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ re_ ┆ tio ┆ cm  ┆ _km ┆ g   ┆ g   ┆ i8  ┆ de  ┆ eng ┆ _se ┆ del ┆ --- ┆ eco ┆ d   ┆ l_h ┆ _da ┆ ---    ┆ i64   ┆ i64   ┆ ---   │
│ str ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ e   ┆ s   ┆     ┆ i8  ┆     ┆ i8  ┆ riv ┆ par ┆ gme ┆ f64 ┆ f64 ┆ f32 ┆ f32 ┆ f32 ┆ c   ┆ n_m ┆ --- ┆ h   ┆ --- ┆ --- ┆     ┆ --- ┆ th  ┆ gme ┆ ay_ ┆ f64 ┆ nds ┆ --- ┆ oli ┆ y   ┆ bool   ┆       ┆       ┆ i64   │
│     ┆ str ┆     ┆ i64 ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ al  ┆ tur ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ m   ┆ f64 ┆ --- ┆ i8  ┆ i8  ┆     ┆ i64 ┆ --- ┆ nt_ ┆ sec ┆     ┆ --- ┆ boo ┆ day ┆ --- ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ f64 ┆     ┆     ┆     ┆     ┆ --- ┆ e   ┆ tim ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆ f64 ┆ spe ┆ ond ┆     ┆ i64 ┆ l   ┆ --- ┆ boo ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆ --- ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed_ ┆ s   ┆     ┆     ┆     ┆ boo ┆ l   ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mps ┆ --- ┆     ┆     ┆     ┆ l   ┆     ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╪═══════╪═══════╪═══════╡
│ MV_ ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 41  ┆ 0.9 ┆ 20  ┆ 2   ┆ 6   ┆ 0   ┆ 716 ┆ 716 ┆ 70  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 47. ┆ 31. ┆ 0.0 ┆ 0.0 ┆ 9.5 ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 168 ┆ 3.0 ┆ 608 ┆ 72. ┆ 8   ┆ fal ┆ fal ┆ fal ┆ false  ┆ 226   ┆ 35    ┆ 40    │
│ C6- ┆ 606 ┆     ┆     ┆ 009 ┆ C6- ┆     ┆ 111 ┆     ┆     ┆     ┆     ┆ 22  ┆ 22  ┆     ┆ 832 ┆ .93 ┆ 833 ┆ .93 ┆ 511 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .38 ┆ 615 ┆     ┆ 608 ┆     ┆ se  ┆ se  ┆ se  ┆        ┆       ┆       ┆       │
│ Wee ┆ 30  ┆     ┆     ┆ 2   ┆ Wee ┆     ┆ 11  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 912 ┆ 946 ┆ 019 ┆ 944 ┆ 364 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 363 ┆ 21  ┆     ┆ 229 ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-1 ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 117 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 00_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ M3_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 326 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ MV_ ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 42  ┆ 0.9 ┆ 20  ┆ 2   ┆ 6   ┆ 0   ┆ 716 ┆ 716 ┆ 48  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 65. ┆ 31. ┆ 0.0 ┆ 0.0 ┆ 9.5 ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 142 ┆ 3.0 ┆ 586 ┆ 8.5 ┆ 9   ┆ fal ┆ fal ┆ fal ┆ false  ┆ 226   ┆ 35    ┆ 5     │
│ C6- ┆ 606 ┆     ┆     ┆ 009 ┆ C6- ┆     ┆ 333 ┆     ┆     ┆     ┆     ┆ 70  ┆ 70  ┆     ┆ 834 ┆ .93 ┆ 835 ┆ .93 ┆ 207 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .31 ┆ 279 ┆     ┆ 923 ┆     ┆ se  ┆ se  ┆ se  ┆        ┆       ┆       ┆       │
│ Wee ┆ 30  ┆     ┆     ┆ 2   ┆ Wee ┆     ┆ 33  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 045 ┆ 813 ┆ 564 ┆ 743 ┆ 558 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 313 ┆ 39  ┆     ┆ 68  ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-1 ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 117 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 00_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ M3_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 326 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ MV_ ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 43  ┆ 0.9 ┆ 20  ┆ 2   ┆ 6   ┆ 0   ┆ 717 ┆ 717 ┆ 41  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 65. ┆ 31. ┆ 0.0 ┆ 0.0 ┆ 9.5 ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 166 ┆ 3.0 ┆ 578 ┆ 8.5 ┆ 5   ┆ fal ┆ fal ┆ fal ┆ false  ┆ 226   ┆ 35    ┆ 56    │
│ C6- ┆ 606 ┆     ┆     ┆ 009 ┆ C6- ┆     ┆ 555 ┆     ┆     ┆     ┆     ┆ 11  ┆ 11  ┆     ┆ 835 ┆ .93 ┆ 835 ┆ .93 ┆ 207 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .57 ┆ 286 ┆     ┆ 923 ┆     ┆ se  ┆ se  ┆ se  ┆        ┆       ┆       ┆       │
│ Wee ┆ 30  ┆     ┆     ┆ 2   ┆ Wee ┆     ┆ 56  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 242 ┆ 749 ┆ 564 ┆ 743 ┆ 558 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 416 ┆ 21  ┆     ┆ 68  ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-1 ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 117 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 00_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ M3_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 326 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ MV_ ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 44  ┆ 0.9 ┆ 20  ┆ 2   ┆ 6   ┆ 0   ┆ 717 ┆ 717 ┆ 47  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 65. ┆ 31. ┆ 0.0 ┆ 0.0 ┆ 9.5 ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 204 ┆ 3.0 ┆ 542 ┆ 2.4 ┆ 8   ┆ fal ┆ fal ┆ fal ┆ false  ┆ 226   ┆ 35    ┆ 90    │
│ C6- ┆ 606 ┆     ┆     ┆ 009 ┆ C6- ┆     ┆ 777 ┆     ┆     ┆     ┆     ┆ 58  ┆ 58  ┆     ┆ 836 ┆ .93 ┆ 836 ┆ .93 ┆ 556 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .71 ┆ 105 ┆     ┆ 770 ┆     ┆ se  ┆ se  ┆ se  ┆        ┆       ┆       ┆       │
│ Wee ┆ 30  ┆     ┆     ┆ 2   ┆ Wee ┆     ┆ 78  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 657 ┆ 685 ┆ 197 ┆ 714 ┆ 046 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 453 ┆ 08  ┆     ┆ 02  ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-1 ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 117 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 00_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ M3_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 326 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ MV_ ┆ 202 ┆ M4  ┆ 0   ┆ M04 ┆ MV_ ┆ 70  ┆ 0.9 ┆ 20  ┆ 2   ┆ 6   ┆ 0   ┆ 723 ┆ 723 ┆ 35  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 72. ┆ 31. ┆ 0.0 ┆ 0.0 ┆ 9.5 ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 153 ┆ 4.3 ┆ -19 ┆ 8.3 ┆ 100 ┆ fal ┆ fal ┆ fal ┆ false  ┆ 267   ┆ 45    ┆ 130   │
│ C6- ┆ 606 ┆     ┆     ┆ 092 ┆ C6- ┆     ┆ 210 ┆     ┆     ┆     ┆     ┆ 05  ┆ 05  ┆     ┆ 847 ┆ .93 ┆ 848 ┆ .93 ┆ 299 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .41 ┆ 833 ┆ 6   ┆ 643 ┆     ┆ se  ┆ se  ┆ se  ┆        ┆       ┆       ┆       │
│ Wee ┆ 30  ┆     ┆     ┆ 3   ┆ Wee ┆     ┆ 53  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 906 ┆ 940 ┆ 469 ┆ 930 ┆ 576 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 805 ┆ 73  ┆     ┆ 08  ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-1 ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 117 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 00_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ M5_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 528 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ MV_ ┆ 202 ┆ M4  ┆ 0   ┆ M04 ┆ MV_ ┆ 71  ┆ 0.9 ┆ 20  ┆ 2   ┆ 6   ┆ 0   ┆ 723 ┆ 723 ┆ 44  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 61. ┆ 31. ┆ 0.0 ┆ 0.0 ┆ 9.5 ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 230 ┆ 4.4 ┆ -18 ┆ 74. ┆ 144 ┆ fal ┆ fal ┆ fal ┆ false  ┆ 267   ┆ 45    ┆ 53    │
│ C6- ┆ 606 ┆     ┆     ┆ 092 ┆ C6- ┆     ┆ 342 ┆     ┆     ┆     ┆     ┆ 49  ┆ 49  ┆     ┆ 849 ┆ .93 ┆ 849 ┆ .93 ┆ 488 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .31 ┆ 291 ┆ 7   ┆ 105 ┆     ┆ se  ┆ se  ┆ se  ┆        ┆       ┆       ┆       │
│ Wee ┆ 30  ┆     ┆     ┆ 3   ┆ Wee ┆     ┆ 11  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 229 ┆ 893 ┆ 243 ┆ 897 ┆ 754 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 597 ┆ 53  ┆     ┆ 947 ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-1 ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 117 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 00_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ M5_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 528 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ MV_ ┆ 202 ┆ M4  ┆ 0   ┆ M04 ┆ MV_ ┆ 72  ┆ 0.9 ┆ 20  ┆ 2   ┆ 6   ┆ 0   ┆ 724 ┆ 724 ┆ 65  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 69. ┆ 31. ┆ 0.0 ┆ 0.0 ┆ 9.5 ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 137 ┆ 4.4 ┆ -10 ┆ 7.4 ┆ 120 ┆ fal ┆ fal ┆ fal ┆ false  ┆ 267   ┆ 45    ┆ 40    │
│ C6- ┆ 606 ┆     ┆     ┆ 092 ┆ C6- ┆     ┆ 473 ┆     ┆     ┆     ┆     ┆ 14  ┆ 14  ┆     ┆ 851 ┆ .93 ┆ 851 ┆ .93 ┆ 483 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .22 ┆ 266 ┆ 1   ┆ 450 ┆     ┆ se  ┆ se  ┆ se  ┆        ┆       ┆       ┆       │
│ Wee ┆ 30  ┆     ┆     ┆ 3   ┆ Wee ┆     ┆ 68  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 202 ┆ 807 ┆ 097 ┆ 821 ┆ 452 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 478 ┆ 06  ┆     ┆ 31  ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-1 ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 117 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 00_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ M5_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 528 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ MV_ ┆ 202 ┆ M4  ┆ 0   ┆ M04 ┆ MV_ ┆ 73  ┆ 0.9 ┆ 20  ┆ 2   ┆ 6   ┆ 0   ┆ 724 ┆ 724 ┆ 39  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 72. ┆ 31. ┆ 0.0 ┆ 0.0 ┆ 9.5 ┆ 0   ┆ 0   ┆ 0   ┆ 2   ┆ 141 ┆ 4.4 ┆ -11 ┆ 2.8 ┆ 103 ┆ fal ┆ fal ┆ fal ┆ false  ┆ 267   ┆ 45    ┆ 32    │
│ C6- ┆ 606 ┆     ┆     ┆ 092 ┆ C6- ┆     ┆ 605 ┆     ┆     ┆     ┆     ┆ 53  ┆ 53  ┆     ┆ 852 ┆ .93 ┆ 852 ┆ .93 ┆ 790 ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .95 ┆ 361 ┆ 3   ┆ 812 ┆     ┆ se  ┆ se  ┆ se  ┆        ┆       ┆       ┆       │
│ Wee ┆ 30  ┆     ┆     ┆ 3   ┆ Wee ┆     ┆ 26  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 396 ┆ 765 ┆ 47  ┆ 770 ┆ 443 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 774 ┆ 8   ┆     ┆ 24  ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │

In [83]:
print(model_ready.describe())

shape: (9, 41)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┐
│ sta ┆ tri ┆ sta ┆ rou ┆ dir ┆ sha ┆ ser ┆ sto ┆ tri ┆ hou ┆ wee ┆ mon ┆ is_ ┆ sch ┆ sch ┆ sch ┆ sto ┆ sto ┆ lat ┆ lon ┆ bea ┆ tem ┆ pre ┆ sno ┆ win ┆ is_ ┆ is_ ┆ is_ ┆ wea ┆ seg ┆ sch ┆ ups ┆ spe ┆ hea ┆ is_ ┆ is_ ┆ is_ ┆ has ┆ rid ┆ tra ┆ travel │
│ tis ┆ p_i ┆ rt_ ┆ te_ ┆ ect ┆ pe_ ┆ vic ┆ p_s ┆ p_p ┆ r   ┆ kda ┆ th  ┆ pea ┆ edu ┆ edu ┆ edu ┆ p_l ┆ p_l ┆ itu ┆ git ┆ rin ┆ per ┆ cip ┆ wfa ┆ dsp ┆ rai ┆ sno ┆ fog ┆ the ┆ men ┆ edu ┆ tre ┆ ed_ ┆ dwa ┆ wee ┆ fed ┆ sch ┆ _ma ┆ ers ┆ nsf ┆ _time  │
│ tic ┆ d   ┆ dat ┆ id  ┆ ion ┆ id  ┆ e_i ┆ equ ┆ rog ┆ --- ┆ y   ┆ --- ┆ k   ┆ led ┆ led ┆ led ┆ at  ┆ on  ┆ de  ┆ ude ┆ g   ┆ atu ┆ ita ┆ ll_ ┆ eed ┆ nin ┆ win ┆ --- ┆ rco ┆ t_l ┆ led ┆ am_ ┆ mps ┆ y_s ┆ ken ┆ era ┆ ool ┆ jor ┆ hip ┆ ers ┆ ---    │
│ --- ┆ --- ┆ e   ┆ --- ┆ _id ┆ --- ┆ d   ┆ enc ┆ res ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ _ar ┆ _de ┆ _se ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ re_ ┆ tio ┆ cm  ┆ _km ┆ g   ┆ g   ┆ f64 ┆ de  ┆ eng ┆ _se ┆ del ┆ --- ┆ eco ┆ d   ┆ l_h ┆ _da ┆ _ev ┆ --- ┆ --- ┆ f64    │
│ str ┆ str ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ e   ┆ s   ┆     ┆ f64 ┆     ┆ f64 ┆ riv ┆ par ┆ gme ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ c   ┆ n_m ┆ --- ┆ h   ┆ --- ┆ --- ┆     ┆ --- ┆ th  ┆ gme ┆ ay_ ┆ f64 ┆ nds ┆ --- ┆ oli ┆ y   ┆ ent ┆ f64 ┆ f64 ┆        │
│     ┆     ┆ str ┆     ┆ f64 ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ al  ┆ tur ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ m   ┆ f64 ┆ --- ┆ f64 ┆ f64 ┆     ┆ f64 ┆ --- ┆ nt_ ┆ sec ┆     ┆ --- ┆ f64 ┆ day ┆ --- ┆ --- ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆ --- ┆ e   ┆ tim ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆ f64 ┆ spe ┆ ond ┆     ┆ f64 ┆     ┆ --- ┆ f64 ┆ f64 ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed_ ┆ s   ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mps ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╡
│ cou ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 567 ┆ 56764. │
│ nt  ┆ 64  ┆ 64  ┆ 64  ┆ 64. ┆ 64  ┆ 64  ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 64. ┆ 0      │
│     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆        │
│ nul ┆ 0   ┆ 0   ┆ 0   ┆ 0.0 ┆ 0   ┆ 0   ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0    │
│ l_c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│ oun ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│ mea ┆ nul ┆ nul ┆ nul ┆ 0.4 ┆ nul ┆ nul ┆ 30. ┆ 0.5 ┆ 12. ┆ 2.8 ┆ 6.8 ┆ 0.3 ┆ 515 ┆ 515 ┆ 93. ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 152 ┆ 29. ┆ 0.0 ┆ 0.0 ┆ 9.4 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 8.2 ┆ 247 ┆ 4.1 ┆ 143 ┆ 14. ┆ 865 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 503 ┆ 108 ┆ 93.841 │
│ n   ┆ l   ┆ l   ┆ l   ┆ 877 ┆ l   ┆ l   ┆ 694 ┆ 137 ┆ 871 ┆ 479 ┆ 479 ┆ 376 ┆ 95. ┆ 95. ┆ 567 ┆ 787 ┆ .95 ┆ 787 ┆ .95 ┆ .12 ┆ 611 ┆ 276 ┆     ┆ 214 ┆ 660 ┆     ┆     ┆ 236 ┆ .24 ┆ 805 ┆ .69 ┆ 539 ┆ .07 ┆     ┆     ┆     ┆     ┆ .24 ┆ .43 ┆ 995    │
│     ┆     ┆     ┆     ┆ 39  ┆     ┆     ┆ 648 ┆ 11  ┆ 767 ┆ 67  ┆ 67  ┆ 44  ┆ 764 ┆ 764 ┆ 331 ┆ 47  ┆ 871 ┆ 476 ┆ 869 ┆ 980 ┆ 435 ┆ 95  ┆     ┆ 77  ┆ 81  ┆     ┆     ┆ 45  ┆ 527 ┆ 8   ┆ 787 ┆ 509 ┆ 226 ┆     ┆     ┆     ┆     ┆ 275 ┆ 395 ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 358 ┆ 358 ┆     ┆     ┆ 7   ┆     ┆ 4   ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆ 2   ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆ 9   ┆ 5   ┆        │
│ std ┆ nul ┆ nul ┆ nul ┆ 0.4 ┆ nul ┆ nul ┆ 18. ┆ 0.2 ┆ 5.9 ┆ 0.3 ┆ 0.3 ┆ 0.4 ┆ 208 ┆ 208 ┆ 62. ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 95. ┆ 3.6 ┆ 0.0 ┆ 0.0 ┆ 2.1 ┆ 0.2 ┆ 0.0 ┆ 0.0 ┆ 17. ┆ 138 ┆ 1.4 ┆ 495 ┆ 26. ┆ 172 ┆ nul ┆ nul ┆ nul ┆ nul ┆ 264 ┆ 61. ┆ 76.481 │
│     ┆ l   ┆ l   ┆ l   ┆ 998 ┆ l   ┆ l   ┆ 169 ┆ 762 ┆ 817 ┆ 590 ┆ 590 ┆ 729 ┆ 84. ┆ 84. ┆ 597 ┆ 367 ┆ 180 ┆ 367 ┆ 180 ┆ 910 ┆ 442 ┆ 803 ┆     ┆ 928 ┆ 484 ┆     ┆     ┆ 045 ┆ .14 ┆ 209 ┆ .50 ┆ 705 ┆ 9.5 ┆ l   ┆ l   ┆ l   ┆ l   ┆ .47 ┆ 905 ┆ 774    │
│     ┆     ┆     ┆     ┆ 54  ┆     ┆     ┆ 236 ┆ 94  ┆ 41  ┆ 56  ┆ 56  ┆ 1   ┆ 560 ┆ 560 ┆ 49  ┆ 94  ┆ 52  ┆ 79  ┆ 79  ┆ 622 ┆ 54  ┆ 68  ┆     ┆ 39  ┆ 25  ┆     ┆     ┆ 505 ┆ 864 ┆ 75  ┆ 964 ┆ 804 ┆ 311 ┆     ┆     ┆     ┆     ┆ 464 ┆ 777 ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 634 ┆ 634 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆ 1   ┆     ┆ 88  ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆        │
│ min ┆ MV_ ┆ 202 ┆ M1  ┆ 0.0 ┆ M01 ┆ MV_ ┆ 2.0 ┆ 0.0 ┆ 0.0 ┆ 2.0 ┆ 6.0 ┆ 0.0 ┆ 124 ┆ 124 ┆ 12. ┆ 40. ┆ -74 ┆ 40. ┆ -74 ┆ 0.0 ┆ 23. ┆ 0.0 ┆ 0.0 ┆ 4.8 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 61. ┆ 0.8 ┆ -12 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 3.0 ┆ 0.0 ┆ 1.0    │
│     ┆ C6- ┆ 606 ┆     ┆     ┆ 000 ┆ C6- ┆     ┆ 256 ┆     ┆     ┆     ┆     ┆ 1.0 ┆ 1.0 ┆ 0   ┆ 703 ┆ .01 ┆ 701 ┆ .01 ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 833 ┆ 326 ┆ 63. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ Wee ┆ 30  ┆     ┆     ┆ 3   ┆ Wee ┆     ┆ 41  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 036 ┆ 083 ┆ 55  ┆ 284 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 169 ┆ 85  ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ y-1 ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ 117 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ 00_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ M3_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ 326 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│ 25% ┆ nul ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ 15. ┆ 0.2 ┆ 8.0 ┆ 3.0 ┆ 7.0 ┆ 0.0 ┆ 342 ┆ 342 ┆ 57. ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 53. ┆ 25. ┆ 0.0 ┆ 0.0 ┆ 8.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 162 ┆ 3.0 ┆ -71 ┆ 1.4 ┆ 359 ┆ nul ┆ nul ┆ nul ┆ nul ┆ 290 ┆ 59. ┆ 49.0   │
│     ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆ 0   ┆ 763 ┆     ┆     ┆     ┆     ┆ 60. ┆ 60. ┆ 0   ┆ 758 ┆ .97 ┆ 758 ┆ .97 ┆ 972 ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .16 ┆ 952 ┆ .0  ┆ 459 ┆ .0  ┆ l   ┆ l   ┆ l   ┆ l   ┆ .0  ┆ 0   ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 16  ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆ 663 ┆ 202 ┆ 892 ┆ 194 ┆ 626 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 300 ┆ 99  ┆     ┆ 38  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│ 50% ┆ nul ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ 29. ┆ 0.5 ┆ 13. ┆ 3.0 ┆ 7.0 ┆ 0.0 ┆ 522 ┆ 522 ┆ 78. ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 157 ┆ 30. ┆ 0.0 ┆ 0.0 ┆ 9.8 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 2.0 ┆ 216 ┆ 3.9 ┆ 64. ┆ 3.9 ┆ 639 ┆ nul ┆ nul ┆ nul ┆ nul ┆ 560 ┆ 122 ┆ 79.0   │
│     ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆ 0   ┆ 151 ┆ 0   ┆     ┆     ┆     ┆ 00. ┆ 00. ┆ 0   ┆ 790 ┆ .95 ┆ 790 ┆ .95 ┆ .33 ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .69 ┆ 957 ┆ 0   ┆ 221 ┆ .0  ┆ l   ┆ l   ┆ l   ┆ l   ┆ .0  ┆ .0  ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 52  ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆ 304 ┆ 475 ┆ 375 ┆ 462 ┆ 160 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 267 ┆ 76  ┆     ┆ 01  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│ 75% ┆ nul ┆ nul ┆ nul ┆ 1.0 ┆ nul ┆ nul ┆ 44. ┆ 0.7 ┆ 18. ┆ 3.0 ┆ 7.0 ┆ 1.0 ┆ 679 ┆ 679 ┆ 108 ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 233 ┆ 32. ┆ 0.0 ┆ 0.0 ┆ 11. ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 3.0 ┆ 272 ┆ 5.0 ┆ 255 ┆ 7.9 ┆ 100 ┆ nul ┆ nul ┆ nul ┆ nul ┆ 723 ┆ 156 ┆ 115.0  │
│     ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆ 0   ┆ 551 ┆ 0   ┆     ┆     ┆     ┆ 23. ┆ 23. ┆ .0  ┆ 815 ┆ .94 ┆ 815 ┆ .94 ┆ .97 ┆ 7   ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆ .32 ┆ 619 ┆ .0  ┆ 173 ┆ 3.0 ┆ l   ┆ l   ┆ l   ┆ l   ┆ .0  ┆ .0  ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 02  ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆ 549 ┆ 399 ┆ 632 ┆ 407 ┆ 262 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 853 ┆ 14  ┆     ┆ 24  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆ 7   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│ max ┆ OH_ ┆ 202 ┆ M4  ┆ 1.0 ┆ M15 ┆ OH_ ┆ 77. ┆ 0.9 ┆ 23. ┆ 3.0 ┆ 7.0 ┆ 1.0 ┆ 951 ┆ 951 ┆ 336 ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 355 ┆ 35. ┆ 0.4 ┆ 0.0 ┆ 13. ┆ 1.0 ┆ 0.0 ┆ 0.0 ┆ 51. ┆ 992 ┆ 15. ┆ 134 ┆ 437 ┆ 489 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 104 ┆ 274 ┆ 1781.0 │
│     ┆ C6- ┆ 607 ┆     ┆     ┆ 006 ┆ C6- ┆ 0   ┆ 871 ┆ 0   ┆     ┆     ┆     ┆ 34. ┆ 34. ┆ 0.0 ┆ 859 ┆ .92 ┆ 861 ┆ .92 ┆ .23 ┆ 4   ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆ 0   ┆ .02 ┆ 320 ┆ 50. ┆ .01 ┆ 46. ┆     ┆     ┆     ┆     ┆ 2.0 ┆ .0  ┆        │
│     ┆ Wee ┆ 01  ┆     ┆     ┆ 7   ┆ Wee ┆     ┆ 79  ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆ 129 ┆ 655 ┆ 446 ┆ 464 ┆ 635 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 088 ┆ 422 ┆ 0   ┆ 489 ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ 4   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ y-S ┆     ┆     ┆     ┆     ┆ y-S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ Don ┆     ┆     ┆     ┆     ┆ Don ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ -BM ┆     ┆     ┆     ┆     ┆ -BM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ -14 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ 180 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ 0_M ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴────────┘

In [84]:
model_ready.group_by("route_id").len().sort("len", descending=True)

shape: (5, 2)
┌──────────┬───────┐
│ route_id ┆ len   │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ M4       ┆ 14015 │
│ M101     ┆ 12422 │
│ M15      ┆ 11066 │
│ M1       ┆ 10671 │
│ M2       ┆ 8590  │
└──────────┴───────┘

In [85]:
model_ready.select([
    pl.col("scheduled_arrival").min().alias("min"),
    pl.col("scheduled_arrival").max().alias("max"),
    pl.col("scheduled_arrival").mean().alias("mean"),
])

shape: (1, 3)
┌──────┬───────┬──────────────┐
│ min  ┆ max   ┆ mean         │
│ ---  ┆ ---   ┆ ---          │
│ i32  ┆ i32   ┆ f64          │
╞══════╪═══════╪══════════════╡
│ 1241 ┆ 95134 ┆ 51595.764358 │
└──────┴───────┴──────────────┘

In [86]:
print(
    trip_updates.group_by("route_id").len().sort("len", descending=True)
)

print(
    matched.group_by("route_id").len().sort("len", descending=True)
)

print(
    model_ready.group_by("route_id").len().sort("len", descending=True)
)

shape: (5, 2)
┌──────────┬───────┐
│ route_id ┆ len   │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ M4       ┆ 16698 │
│ M101     ┆ 15665 │
│ M15      ┆ 14044 │
│ M1       ┆ 13106 │
│ M2       ┆ 10540 │
└──────────┴───────┘
shape: (5, 2)
┌──────────┬───────┐
│ route_id ┆ len   │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ M4       ┆ 16698 │
│ M101     ┆ 15665 │
│ M15      ┆ 14044 │
│ M1       ┆ 13106 │
│ M2       ┆ 10540 │
└──────────┴───────┘
shape: (5, 2)
┌──────────┬───────┐
│ route_id ┆ len   │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ M4       ┆ 14015 │
│ M101     ┆ 12422 │
│ M15      ┆ 11066 │
│ M1       ┆ 10671 │
│ M2       ┆ 8590  │
└──────────┴───────┘

In [87]:
model_ready.write_parquet("raw/processed_gtfs/baseline_dataset.parquet")
print("written")

written