In [38]:
import polars as pl
import math
from pathlib import Path
from datetime import date
from datetime import timedelta

pl.Config.set_tbl_cols(-1)
pl.Config.set_tbl_rows(20)
pl.Config.set_tbl_width_chars(250)

polars.config.Config

In [ ]:
GTFS = Path("raw/processed_gtfs")
RT = Path("raw")
 
# ---------------------------------------------------
# Read files
# ---------------------------------------------------

routes = pl.read_parquet(GTFS / "routes.parquet")
trips = pl.read_parquet(GTFS / "trips.parquet")
stops = pl.read_parquet(GTFS / "stops.parquet")
stop_times = pl.read_parquet(GTFS / "stop_times.parquet")

# trip_updates = pl.read_parquet(RT / "trip_updates/2026-03-12.parquet")
# vehicle_positions = pl.read_parquet(RT / "vehicle_positions/2026-03-12.parquet")
 
print("Loaded")

Loaded

In [ ]:
# %%
# =====================================================================
# REPLACES your current single-date trip_updates/vehicle_positions read
# cell. Auto-detects every date available in BOTH folders within your
# target range, so it stays correct as more days get fetched later -
# no need to hand-maintain a date list.
# =====================================================================

RT = Path("raw")
DATE_START = date(2026, 3, 3)
DATE_END = date(2026, 7, 3)


def available_dates(dir_path: Path) -> set[str]:
    return {p.stem for p in dir_path.glob("*.parquet")}


tu_dates = available_dates(RT / "trip_updates")
vp_dates = available_dates(RT / "vehicle_positions")
both_dates = tu_dates & vp_dates

usable_dates = sorted(
    d for d in both_dates
    if DATE_START.isoformat() <= d <= DATE_END.isoformat()
)
print(f"trip_updates dates found: {len(tu_dates)} | vehicle_positions dates found: {len(vp_dates)}")
print(f"usable dates (present in both, within range): {len(usable_dates)}")

missing = [
    (DATE_START + __import__("datetime").timedelta(days=i)).isoformat()
    for i in range((DATE_END - DATE_START).days + 1)
]
missing = sorted(set(missing) - set(usable_dates))
if missing:
    print(f"NOTE: {len(missing)} days in range have no usable RT data yet "
          f"(missing from one or both feeds) - proceeding with what's available.")
    print("first few missing:", missing[:10])

trip_updates = pl.concat([
    pl.read_parquet(RT / "trip_updates" / f"{d}.parquet") for d in usable_dates
])
vehicle_positions = pl.concat([
    pl.read_parquet(RT / "vehicle_positions" / f"{d}.parquet") for d in usable_dates
])

print(f"trip_updates: {trip_updates.shape} | vehicle_positions: {vehicle_positions.shape}")

In [41]:
def gtfs_to_seconds(col):
    p = pl.col(col).str.split(":")
    return (
        p.list.get(0).cast(pl.Int32) * 3600
        + p.list.get(1).cast(pl.Int32) * 60
        + p.list.get(2).cast(pl.Int32)
    )
 
stop_times = stop_times.with_columns(
    pl.col("stop_sequence").cast(pl.UInt32),
    pl.col("stop_id").cast(pl.Utf8),
    gtfs_to_seconds("arrival_time").alias("scheduled_arrival"),
    gtfs_to_seconds("departure_time").alias("scheduled_departure"),
)
 
stops = stops.with_columns([
    pl.col("stop_id").cast(pl.Utf8),

    # pl.col("stop_lat")
    #   .str.strip_chars()
    #   .cast(pl.Float64),

    # pl.col("stop_lon")
    #   .str.strip_chars()
    #   .cast(pl.Float64),
])

In [42]:

trip_updates = (
    trip_updates
    .sort("feed_timestamp")
    .group_by(["trip_id", "start_date", "stop_sequence"])
    .last()
)

In [43]:
if "schedule_relationship" in trip_updates.columns:
    trip_updates = trip_updates.filter(pl.col("schedule_relationship") == 0)

In [44]:
trip_updates = trip_updates.with_columns(
    pl.from_epoch("arrival_time", time_unit="s").alias("event_time")
)
 
vehicle_positions = vehicle_positions.with_columns(
    pl.from_epoch("timestamp", time_unit="s").alias("vehicle_time")
)

In [45]:
TRIP_ID_PATTERN = r'^[A-Z]{2}_([A-Z0-9]+)-(\w+?)-(\d+)_([A-Z0-9+]+)_(\d+)$'
 
def parse_trip_id(df: pl.DataFrame) -> pl.DataFrame:
    return df.with_columns([
        pl.col("trip_id").str.extract(TRIP_ID_PATTERN, 2).alias("_service_day"),
        pl.col("trip_id").str.extract(TRIP_ID_PATTERN, 3).alias("_origin_secs"),
        pl.col("trip_id").str.extract(TRIP_ID_PATTERN, 5).alias("_trip_num"),
    ])
 
trips_parsed = parse_trip_id(trips)
tu_parsed = parse_trip_id(trip_updates)
 
# 1) direct trip_id match
direct = tu_parsed.join(
    trips_parsed.select(["trip_id", "route_id", "direction_id", "shape_id", "service_id"]),
    on="trip_id", how="inner", suffix="_static",
)

In [46]:
unmatched = tu_parsed.join(direct.select("trip_id").unique(), on="trip_id", how="anti")
fallback = unmatched.join(
    trips_parsed.select([
        "trip_id", "route_id", "direction_id", "shape_id", "service_id",
        "_service_day", "_origin_secs", "_trip_num",
    ]).rename({"trip_id": "_static_trip_id"}),
    on=["route_id", "_service_day", "_origin_secs", "_trip_num"],
    how="inner",
    suffix="_static",
).with_columns(
    pl.col("_static_trip_id").alias("trip_id")   # use the STATIC trip_id downstream
).drop("_static_trip_id")
 
n_direct, n_fallback, n_total = direct.height, fallback.height, tu_parsed.height
print(f"[join] direct match: {n_direct:,} | fallback match: {n_fallback:,} | "
      f"total: {(n_direct + n_fallback) / n_total:.1%} of {n_total:,} rows")
 
direct = direct.drop(["_service_day", "_origin_secs", "_trip_num"])
fallback = fallback.drop(["_service_day", "_origin_secs", "_trip_num"])

[join] direct match: 71,266 | fallback match: 0 | total: 100.0% of 71,266 rows

In [47]:
# %%
# =====================================================================
# CALENDAR VALIDITY CHECK - insert right after your existing trip_id
# join (direct + fallback), before the stop_times join. Verifies each
# matched (service_id, start_date) pair is actually a real service day,
# not just a string match - important now that trips/calendar/
# calendar_dates span MULTIPLE rating periods concatenated together.
# =====================================================================
 
calendar = pl.read_parquet("raw/processed_gtfs/calendar.parquet")
calendar_dates = pl.read_parquet("raw/processed_gtfs/calendar_dates.parquet")
 
 
def resolve_service_dates(calendar_df: pl.DataFrame, calendar_dates_df: pl.DataFrame) -> pl.DataFrame:
    from datetime import date as _date, timedelta as _timedelta
    weekday_cols = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]
    rows = []
    for row in calendar_df.iter_rows(named=True):
        start = _date(int(str(row["start_date"])[:4]), int(str(row["start_date"])[4:6]), int(str(row["start_date"])[6:8]))
        end = _date(int(str(row["end_date"])[:4]), int(str(row["end_date"])[4:6]), int(str(row["end_date"])[6:8]))
        d = start
        while d <= end:
            if row[weekday_cols[d.weekday()]] == 1:
                rows.append({"service_id": row["service_id"], "date": int(d.strftime("%Y%m%d"))})
            d += _timedelta(days=1)
    base = pl.DataFrame(rows)
    additions = calendar_dates_df.filter(pl.col("exception_type") == 1).select(["service_id", "date"])
    removals = calendar_dates_df.filter(pl.col("exception_type") == 2).select(["service_id", "date"])
    resolved = pl.concat([base, additions]).unique()
    resolved = resolved.join(removals, on=["service_id", "date"], how="anti")
    return resolved
 
 
service_dates = resolve_service_dates(calendar, calendar_dates)
print(f"resolved {service_dates.height:,} valid (service_id, date) pairs spanning "
      f"{service_dates['date'].min()} - {service_dates['date'].max()}")

resolved 1,190 valid (service_id, date) pairs spanning 20260103 - 20260905

In [48]:
direct = (
    direct.drop(["route_id", "direction_id"])
          .rename({"route_id_static": "route_id", "direction_id_static": "direction_id"})
)
fallback = fallback.drop("direction_id").rename({"direction_id_static": "direction_id"})
 
matched = pl.concat([direct, fallback.select(direct.columns)])

In [49]:
data = (
    matched
    .join(
        stop_times.select([
            "trip_id", "stop_sequence", "stop_id",
            "scheduled_arrival", "scheduled_departure",
        ]),
        on=["trip_id", "stop_sequence"],
        how="inner",   # inner now: every row here already has a resolved static trip_id,
                        # so a missing stop_times row means bad data, not an expected gap
    )
    .join(
        stops.select(["stop_id", "stop_lat", "stop_lon"]),
        on="stop_id",
        how="left",
    )
)
 
print(data.shape)

(71255, 22)

In [50]:
data = data.with_columns(pl.col("start_date").cast(pl.Int64).alias("_start_date_int"))
 
invalid = data.join(
    service_dates.rename({"date": "_start_date_int"}),
    on=["service_id", "_start_date_int"],
    how="anti",
)
print(f"rows with a matched trip_id but an INVALID (service_id, date) pair: {invalid.height:,} "
      f"({invalid.height / max(data.height, 1):.2%} of {data.height:,})")
if invalid.height > 0:
    print("sample of invalid rows (worth checking which rating period they came from):")
    print(invalid.select(["trip_id", "route_id", "service_id", "start_date"]).head(10))
 
data = data.join(
    service_dates.rename({"date": "_start_date_int"}),
    on=["service_id", "_start_date_int"],
    how="semi",
).drop("_start_date_int")
 
print(f"data after calendar validity filter: {data.shape}")

rows with a matched trip_id but an INVALID (service_id, date) pair: 0 (0.00% of 71,255)
data after calendar validity filter: (71255, 22)

In [51]:
def haversine_expr(lat1, lon1, lat2, lon2) -> pl.Expr:
    R = 6371000.0
    lat1r, lat2r = lat1.radians(), lat2.radians()
    dlat = (lat2 - lat1).radians()
    dlon = (lon2 - lon1).radians()
    a = (dlat / 2).sin() ** 2 + lat1r.cos() * lat2r.cos() * (dlon / 2).sin() ** 2
    return 2 * R * a.sqrt().arcsin()
 
vehicle_positions = vehicle_positions.sort(["vehicle_id", "vehicle_time"])
vehicle_positions = vehicle_positions.with_columns([
    pl.col("latitude").shift(1).over("vehicle_id").alias("_prev_lat"),
    pl.col("longitude").shift(1).over("vehicle_id").alias("_prev_lon"),
    pl.col("vehicle_time").shift(1).over("vehicle_id").alias("_prev_time"),
])
vehicle_positions = vehicle_positions.with_columns(
    haversine_expr(pl.col("_prev_lat"), pl.col("_prev_lon"), pl.col("latitude"), pl.col("longitude")).alias("_dist_m")
)
vehicle_positions = vehicle_positions.with_columns(
    (
        pl.col("_dist_m")
        / (pl.col("vehicle_time") - pl.col("_prev_time")).dt.total_seconds().clip(lower_bound=1)
    ).alias("speed_mps")
)

In [52]:
vp = vehicle_positions.select([
    "vehicle_id", "vehicle_time", "latitude", "longitude", "bearing", "speed_mps",
])
 
data = data.sort(["vehicle_id", "event_time"])
vp = vp.sort(["vehicle_id", "vehicle_time"])
 
data = data.join_asof(
    vp,
    left_on="event_time",
    right_on="vehicle_time",
    by="vehicle_id",
    strategy="backward",
    tolerance=timedelta(minutes=2),
)

C:\Users\ishan\AppData\Local\Temp\ipykernel_7684\3507643840.py:8: UserWarning: Sortedness of columns cannot be checked when 'by' groups provided
  data = data.join_asof(

In [53]:
data = (
    data
    .sort(["trip_id", "stop_sequence"])
    .with_columns(
        pl.col("arrival_time").shift(-1).over("trip_id").alias("next_arrival_time")
    )
    .with_columns(
        (pl.col("next_arrival_time") - pl.col("arrival_time")).alias("travel_time")
    )
)
 
data = data.filter(
    (pl.col("travel_time") > 0) & (pl.col("travel_time") < 1800)   # 30 min cap
)

In [54]:
# data = data.with_columns([
#     pl.col("event_time").dt.hour().alias("hour"),
#     pl.col("event_time").dt.weekday().alias("weekday"),
#     pl.col("event_time").dt.month().alias("month"),
# ])
 
# data = data.with_columns([
#     (
#         (pl.col("hour").is_between(7, 9)) |
#         (pl.col("hour").is_between(16, 18))
#     ).cast(pl.Int8).alias("is_peak")
# ])

data = data.with_columns(
    pl.col("event_time")
      .dt.replace_time_zone("UTC")
      .dt.convert_time_zone("America/New_York")
      .alias("event_time_local")
)
 
data = data.with_columns([
    pl.col("event_time_local").dt.hour().alias("hour"),
    pl.col("event_time_local").dt.weekday().alias("weekday"),
    pl.col("event_time_local").dt.month().alias("month"),
])
 
data = data.with_columns([
    (
        (pl.col("hour").is_between(7, 9)) |
        (pl.col("hour").is_between(16, 18))
    ).cast(pl.Int8).alias("is_peak")
])

In [55]:
data = data.with_columns([
    (
        pl.col("scheduled_arrival")
        - pl.col("scheduled_departure").shift(1).over("trip_id")
    ).alias("scheduled_segment_time"),
 
    (
        pl.col("stop_sequence") / pl.col("stop_sequence").max().over("trip_id")
    ).alias("trip_progress"),
])

In [56]:
segment_network = pl.read_parquet("processed/segment_network.parquet")
 
# dtype fix: segment_network's stop_id/next_stop_id are Int64 (straight
# from stop_times.txt), but `data`'s stop_id was cast to Utf8 earlier for
# the RT join - cast both sides to match before joining.
segment_network = segment_network.with_columns([
    pl.col("stop_id").cast(pl.Utf8),
    pl.col("next_stop_id").cast(pl.Utf8),
])

In [57]:
data = (
    data
    .sort(["trip_id", "stop_sequence"])
    .with_columns(
        pl.col("stop_id").shift(-1).over("trip_id").alias("next_stop_id")
    )
)
 
# %%
n_before = data.height
 
data = data.join(
    segment_network.select([
        "shape_id", "stop_id", "next_stop_id",
        "segment_length", "scheduled_travel_time",
    ]).rename({"scheduled_travel_time": "segment_scheduled_travel_time"}),
    on=["shape_id", "stop_id", "next_stop_id"],
    how="left",
)
 
print(f"rows before: {n_before:,} | after segment join: {data.height:,}")
print("null segment_length rows:", data.filter(pl.col("segment_length").is_null()).height)

rows before: 62,783 | after segment join: 62,783
null segment_length rows: 3699

In [58]:
data = data.with_columns(
    (pl.col("segment_length") / pl.col("segment_scheduled_travel_time").clip(lower_bound=1))
    .alias("scheduled_segment_speed_mps")
)

In [59]:
data = data.sort(["trip_id", "stop_sequence"])
check = data.select([
    "trip_id", "stop_sequence", "scheduled_segment_time", "segment_scheduled_travel_time",
]).with_columns(
    # bring segment_scheduled_travel_time from row k up to align with
    # scheduled_segment_time at row k+1 (both now describe segment k->k+1)
    pl.col("segment_scheduled_travel_time").shift(1).over("trip_id").alias("segment_scheduled_travel_time_aligned")
).drop_nulls(subset=["scheduled_segment_time", "segment_scheduled_travel_time_aligned"])
 
diff = (check["scheduled_segment_time"] - check["segment_scheduled_travel_time_aligned"]).abs()
print("median abs diff (aligned):", diff.median())
print("rows with diff > 30s (aligned):", (diff > 30).sum(), "/", check.height)
 
# expected: last stop of each trip has null segment_length/next_stop_id -
# should be roughly one per trip, not a bug
n_null_segment = data.filter(pl.col("segment_length").is_null()).height
n_trips = data["trip_id"].n_unique()
print(f"null segment_length rows: {n_null_segment:,} vs trip count: {n_trips:,} (should be close)")

median abs diff (aligned): 20.0
rows with diff > 30s (aligned): 20552 / 59084
null segment_length rows: 3,699 vs trip count: 1,219 (should be close)

In [60]:

import requests
from datetime import datetime
 
STATION_LAT, STATION_LON = 40.7829, -73.9654  # Central Park
 
dates_needed = data["start_date"].unique().sort().to_list()
start_date = str(dates_needed[0])
end_date = str(dates_needed[-1])
start_fmt = f"{start_date[:4]}-{start_date[4:6]}-{start_date[6:8]}"
end_fmt = f"{end_date[:4]}-{end_date[4:6]}-{end_date[6:8]}"
 
print(f"Fetching weather for {start_fmt} to {end_fmt}")
 
resp = requests.get(
    "https://archive-api.open-meteo.com/v1/archive",
    params={
        "latitude": STATION_LAT,
        "longitude": STATION_LON,
        "start_date": start_fmt,
        "end_date": end_fmt,
        "hourly": "temperature_2m,precipitation,rain,snowfall,"
                  "windspeed_10m,weathercode",
        "timezone": "America/New_York",
    },
    timeout=30,
)
resp.raise_for_status()
weather_json = resp.json()["hourly"]
 
weather = pl.DataFrame({
    "weather_time_str": weather_json["time"],
    "temperature_c": weather_json["temperature_2m"],
    "precipitation_mm": weather_json["precipitation"],
    "rain_mm": weather_json["rain"],
    "snowfall_cm": weather_json["snowfall"],
    "windspeed_kmh": weather_json["windspeed_10m"],
    "weathercode": weather_json["weathercode"],
})
 
weather = weather.with_columns(
    pl.col("weather_time_str").str.strptime(pl.Datetime, "%Y-%m-%dT%H:%M").alias("weather_time")
).with_columns([
    pl.col("weather_time").dt.strftime("%Y%m%d").alias("start_date"),  # keep as str - matches data's dtype
    pl.col("weather_time").dt.hour().alias("hour"),
])
 
print(weather.shape)
print(weather.head())

Fetching weather for 2026-03-11 to 2026-03-12
(48, 10)
shape: (5, 10)
┌──────────────────┬───────────────┬──────────────────┬─────────┬─────────────┬───────────────┬─────────────┬─────────────────────┬────────────┬──────┐
│ weather_time_str ┆ temperature_c ┆ precipitation_mm ┆ rain_mm ┆ snowfall_cm ┆ windspeed_kmh ┆ weathercode ┆ weather_time        ┆ start_date ┆ hour │
│ ---              ┆ ---           ┆ ---              ┆ ---     ┆ ---         ┆ ---           ┆ ---         ┆ ---                 ┆ ---        ┆ ---  │
│ str              ┆ f64           ┆ f64              ┆ f64     ┆ f64         ┆ f64           ┆ i64         ┆ datetime[μs]        ┆ str        ┆ i8   │
╞══════════════════╪═══════════════╪══════════════════╪═════════╪═════════════╪═══════════════╪═════════════╪═════════════════════╪════════════╪══════╡
│ 2026-03-11T00:00 ┆ 16.1          ┆ 0.0              ┆ 0.0     ┆ 0.0         ┆ 8.3           ┆ 0           ┆ 2026-03-11 00:00:00 ┆ 20260311   ┆ 0    │
│ 2026-03-11T01:00 ┆ 15.3          ┆ 0.0              ┆ 0.0     ┆ 0.0         ┆ 7.5           ┆ 0           ┆ 2026-03-11 01:00:00 ┆ 20260311   ┆ 1    │
│ 2026-03-11T02:00 ┆ 14.3          ┆ 0.0              ┆ 0.0     ┆ 0.0         ┆ 6.0           ┆ 0           ┆ 2026-03-11 02:00:00 ┆ 20260311   ┆ 2    │
│ 2026-03-11T03:00 ┆ 13.8          ┆ 0.0              ┆ 0.0     ┆ 0.0         ┆ 5.4           ┆ 0           ┆ 2026-03-11 03:00:00 ┆ 20260311   ┆ 3    │
│ 2026-03-11T04:00 ┆ 13.1          ┆ 0.0              ┆ 0.0     ┆ 0.0         ┆ 5.1           ┆ 2           ┆ 2026-03-11 04:00:00 ┆ 20260311   ┆ 4    │
└──────────────────┴───────────────┴──────────────────┴─────────┴─────────────┴───────────────┴─────────────┴─────────────────────┴────────────┴──────┘

In [61]:
# %%
# ---------------------------------------------------------------------
# Join weather onto data by (start_date, hour) - both now NYC-local
# ---------------------------------------------------------------------
 
n_before = data.height
 
data = data.join(
    weather.select([
        "start_date", "hour", "temperature_c", "precipitation_mm",
        "rain_mm", "snowfall_cm", "windspeed_kmh", "weathercode",
    ]),
    on=["start_date", "hour"],
    how="left",
)
 
print(f"rows before: {n_before:,} | after weather join: {data.height:,}")
print("null weather rows:", data.filter(pl.col("temperature_c").is_null()).height)

rows before: 62,783 | after weather join: 62,783
null weather rows: 0

In [62]:
data = data.with_columns([
    (pl.col("precipitation_mm") > 0.1).cast(pl.Int8).alias("is_raining"),
    (pl.col("snowfall_cm") > 0.0).cast(pl.Int8).alias("is_snowing"),
    # WMO weather codes 45 (fog) / 48 (depositing rime fog) as a
    # low-visibility proxy - the archive API doesn't expose visibility
    # directly (ERA5 reanalysis has no such variable; that's a
    # forecast-API-only field), so this is the closest available signal.
    pl.col("weathercode").is_in([45, 48]).cast(pl.Int8).alias("is_fog"),
])

In [63]:
# 1. UPSTREAM DELAY
# ---------------------------------------------------------------------
# scheduled_arrival is seconds-since-midnight (local, naive), while
# arrival_time (RT) is an absolute UTC epoch - not directly comparable
# yet. Convert scheduled_arrival to an absolute epoch first, anchored on
# start_date in America/New_York (same pattern used for the weather join).
 
data = data.with_columns(
    pl.col("start_date").str.strptime(pl.Date, "%Y%m%d").alias("service_date")
)
 
data = data.with_columns(
    (
        pl.col("service_date").cast(pl.Datetime)
          .dt.replace_time_zone("America/New_York")
        + pl.duration(seconds=pl.col("scheduled_arrival"))
    ).dt.epoch(time_unit="s").alias("scheduled_arrival_epoch")
)
 
data = data.with_columns(
    (pl.col("arrival_time") - pl.col("scheduled_arrival_epoch")).alias("delay_seconds")
)

In [64]:
# ---------------------------------------------------------------------
# Load + reshape ridership CSV - route + hour granularity
# ---------------------------------------------------------------------
ridership_raw = pl.read_csv(
    "MTA_Bus_Hourly_Ridership_Mar_July.csv",
    schema_overrides={"ridership": pl.Utf8, "transfers": pl.Utf8},
)

# ridership/transfers arrive as strings with thousands separators
# (e.g. "1,131") - strip commas before casting to Int64
ridership_raw = ridership_raw.with_columns(
    pl.col("transit_timestamp")
      .str.strptime(pl.Datetime, "%m/%d/%Y %I:%M:%S %p")
      .alias("_ts"),
    pl.col("ridership").str.replace_all(",", "").cast(pl.Int64),
    pl.col("transfers").str.replace_all(",", "").cast(pl.Int64),
).with_columns([
    pl.col("_ts").dt.date().alias("service_date"),
    pl.col("_ts").dt.hour().alias("hour"),
])

# collapse both fare_class_category and payment_method - one total per
# (route, date, hour)
ridership_hourly = (
    ridership_raw
    .group_by(["bus_route", "service_date", "hour"])
    .agg([
        pl.col("ridership").sum(),
        pl.col("transfers").sum(),
    ])
)

print(ridership_hourly.shape)
print(ridership_hourly.head(10))

(16320, 5)
shape: (10, 5)
┌───────────┬──────────────┬──────┬───────────┬───────────┐
│ bus_route ┆ service_date ┆ hour ┆ ridership ┆ transfers │
│ ---       ┆ ---          ┆ ---  ┆ ---       ┆ ---       │
│ str       ┆ date         ┆ i8   ┆ i64       ┆ i64       │
╞═══════════╪══════════════╪══════╪═══════════╪═══════════╡
│ M4        ┆ 2026-04-09   ┆ 23   ┆ 106       ┆ 13        │
│ M101      ┆ 2026-04-06   ┆ 1    ┆ 21        ┆ 3         │
│ M1        ┆ 2026-03-02   ┆ 21   ┆ 119       ┆ 17        │
│ M15       ┆ 2026-04-13   ┆ 1    ┆ 31        ┆ 9         │
│ M2        ┆ 2026-04-20   ┆ 10   ┆ 336       ┆ 86        │
│ M1        ┆ 2026-04-28   ┆ 23   ┆ 29        ┆ 4         │
│ M101      ┆ 2026-05-13   ┆ 9    ┆ 950       ┆ 321       │
│ M2        ┆ 2026-03-18   ┆ 1    ┆ 7         ┆ 1         │
│ M1        ┆ 2026-03-28   ┆ 18   ┆ 364       ┆ 51        │
│ M1        ┆ 2026-03-21   ┆ 14   ┆ 617       ┆ 146       │
└───────────┴──────────────┴──────┴───────────┴───────────┘

In [65]:
# ---------------------------------------------------------------------
# Join onto `data` by (route_id, service_date, hour).
# NOTE: this ridership file only covers 5 routes (M1, M2, M4, M15, M101).
# route_id naming is verified before joining - if your GTFS route_id has
# an agency prefix (e.g. "MTA NYCT_M1") rather than the bare "M1" used in
# the ridership file, normalize one side before joining.
# ---------------------------------------------------------------------
sample_route_ids = data.select("route_id").unique().sort("route_id").head(10)
print("sample route_id values in `data`:", sample_route_ids["route_id"].to_list())
print("route values in ridership file:", ridership_hourly["bus_route"].unique().sort().to_list())

# If the printed lists above don't share the same format (e.g. one has a
# prefix like "MTA NYCT_"), normalize here before the join, e.g.:
# data = data.with_columns(pl.col("route_id").str.extract(r"([A-Z]+\d+)$", 1).alias("route_id"))

n_before = data.height

data = data.join(
    ridership_hourly,
    left_on=["route_id", "service_date", "hour"],
    right_on=["bus_route", "service_date", "hour"],
    how="left",
).with_columns([
    pl.col("ridership").fill_null(0),
    pl.col("transfers").fill_null(0),
])

print(f"rows before: {n_before:,} | after ridership join: {data.height:,}")
print("routes with zero-filled ridership (not in ridership file, or no match):",
      data.filter(pl.col("ridership") == 0).select("route_id").unique().height)

sample route_id values in `data`: ['M1', 'M101', 'M15', 'M2', 'M4']
route values in ridership file: ['M1', 'M101', 'M15', 'M2', 'M4']
rows before: 62,783 | after ridership join: 62,783
routes with zero-filled ridership (not in ridership file, or no match): 0

In [66]:
print(data.select(
    pl.col("delay_seconds").min().alias("min"),
    pl.col("delay_seconds").max().alias("max"),
    pl.col("delay_seconds").median().alias("median"),
))

shape: (1, 3)
┌───────┬──────┬────────┐
│ min   ┆ max  ┆ median │
│ ---   ┆ ---  ┆ ---    │
│ i64   ┆ i64  ┆ f64    │
╞═══════╪══════╪════════╡
│ -1176 ┆ 5533 ┆ 132.0  │
└───────┴──────┴────────┘

In [67]:
data = data.sort(["trip_id", "stop_sequence"])
data = data.with_columns(
    pl.col("delay_seconds").shift(1).over("trip_id").alias("upstream_delay_seconds")
)

In [68]:
# %%
# ---------------------------------------------------------------------
# 3. HEADWAY TO PRECEDING BUS (same route + direction + stop)
# ---------------------------------------------------------------------
# For each (route_id, direction_id, stop_id), sort arrivals by time and
# take the gap to the PREVIOUS bus that hit the same stop - this is a
# same-route self-join across TRIPS, not within a single trip.
 
headway_base = (
    data.select(["route_id", "direction_id", "stop_id", "trip_id", "arrival_time"])
    .unique()
    .sort(["route_id", "direction_id", "stop_id", "arrival_time"])
)
 
headway_base = headway_base.with_columns(
    pl.col("arrival_time")
      .shift(1)
      .over(["route_id", "direction_id", "stop_id"])
      .alias("_prev_bus_arrival")
)
headway_base = headway_base.with_columns(
    (pl.col("arrival_time") - pl.col("_prev_bus_arrival")).alias("headway_seconds")
)

In [69]:
data = data.join(
    headway_base.select(["route_id", "direction_id", "stop_id", "trip_id", "arrival_time", "headway_seconds"]),
    on=["route_id", "direction_id", "stop_id", "trip_id", "arrival_time"],
    how="left",
)

In [70]:
print(data.select(
    pl.col("headway_seconds").min().alias("min"),
    pl.col("headway_seconds").max().alias("max"),
    pl.col("headway_seconds").median().alias("median"),
))
print("null headway rows (first bus of the day at that stop):",
      data.filter(pl.col("headway_seconds").is_null()).height)

shape: (1, 3)
┌─────┬───────┬────────┐
│ min ┆ max   ┆ median │
│ --- ┆ ---   ┆ ---    │
│ i64 ┆ i64   ┆ f64    │
╞═════╪═══════╪════════╡
│ 0   ┆ 58219 ┆ 627.0  │
└─────┴───────┴────────┘
null headway rows (first bus of the day at that stop): 690

In [71]:
calendar_df = pl.read_parquet("calendar_dataset.parquet")
calendar_df = calendar_df.with_columns(
    pl.col("service_date").str.strptime(pl.Date, "%Y-%m-%d")
)

calendar_df = calendar_df.select([
    "service_date",
    "is_weekend",
    "is_federal_holiday",
    "is_school_day",
    "major_event_count",
]).with_columns(
    (pl.col("major_event_count") > 0).alias("has_major_event")
)
 
n_before = data.height
 
data = data.join(calendar_df, on="service_date", how="left")
 
print(f"rows before: {n_before:,} | after calendar join: {data.height:,}")
print("null calendar rows (service_date outside 2026-03-01 to 2026-07-17):",
      data.filter(pl.col("is_federal_holiday").is_null()).height)

rows before: 62,783 | after calendar join: 62,783
null calendar rows (service_date outside 2026-03-01 to 2026-07-17): 0

In [72]:
data

shape: (62_783, 61)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ tri ┆ sta ┆ sto ┆ fee ┆ fet ┆ sta ┆ sch ┆ veh ┆ tri ┆ sto ┆ arr ┆ dep ┆ eve ┆ rou ┆ dir ┆ sha ┆ ser ┆ sto ┆ sch ┆ sch ┆ sto ┆ sto ┆ veh ┆ lat ┆ lon ┆ bea ┆ spe ┆ nex ┆ tra ┆ eve ┆ hou ┆ wee ┆ mon ┆ is_ ┆ sch ┆ tri ┆ nex ┆ seg ┆ seg ┆ sch ┆ tem ┆ pre ┆ rai ┆ sno ┆ win ┆ wea ┆ is_ ┆ is_ ┆ is_ ┆ ser ┆ sch ┆ del ┆ rid ┆ tra ┆ ups ┆ hea ┆ is_ ┆ is_ ┆ is_ ┆ maj ┆ has │
│ p_i ┆ rt_ ┆ p_s ┆ d_t ┆ ch_ ┆ rt_ ┆ edu ┆ icl ┆ p_t ┆ p_i ┆ iva ┆ art ┆ nt_ ┆ te_ ┆ ect ┆ pe_ ┆ vic ┆ p_i ┆ edu ┆ edu ┆ p_l ┆ p_l ┆ icl ┆ itu ┆ git ┆ rin ┆ ed_ ┆ t_a ┆ vel ┆ nt_ ┆ r   ┆ kda ┆ th  ┆ pea ┆ edu ┆ p_p ┆ t_s ┆ men ┆ men ┆ edu ┆ per ┆ cip ┆ n_m ┆ wfa ┆ dsp ┆ the ┆ rai ┆ sno ┆ fog ┆ vic ┆ edu ┆ ay_ ┆ ers ┆ nsf ┆ tre ┆ dwa ┆ wee ┆ fed ┆ sch ┆ or_ ┆ _ma │
│ d   ┆ dat ┆ equ ┆ ime ┆ tim ┆ tim ┆ le_ ┆ e_i ┆ ime ┆ d   ┆ l_t ┆ ure ┆ tim ┆ id  ┆ ion ┆ id  ┆ e_i ┆ d_r ┆ led ┆ led ┆ at  ┆ on  ┆ e_t ┆ de  ┆ ude ┆ g   ┆ mps ┆ rri ┆ _ti ┆ tim ┆ --- ┆ y   ┆ --- ┆ k   ┆ led ┆ rog ┆ top ┆ t_l ┆ t_s ┆ led ┆ atu ┆ ita ┆ m   ┆ ll_ ┆ eed ┆ rco ┆ nin ┆ win ┆ --- ┆ e_d ┆ led ┆ sec ┆ hip ┆ ers ┆ am_ ┆ y_s ┆ ken ┆ era ┆ ool ┆ eve ┆ jor │
│ --- ┆ e   ┆ enc ┆ sta ┆ est ┆ e   ┆ rel ┆ d   ┆ sta ┆ --- ┆ ime ┆ _ti ┆ e   ┆ --- ┆ _id ┆ --- ┆ d   ┆ igh ┆ _ar ┆ _de ┆ --- ┆ --- ┆ ime ┆ --- ┆ --- ┆ --- ┆ --- ┆ val ┆ me  ┆ e_l ┆ i8  ┆ --- ┆ i8  ┆ --- ┆ _se ┆ res ┆ _id ┆ eng ┆ che ┆ _se ┆ re_ ┆ tio ┆ --- ┆ cm  ┆ _km ┆ de  ┆ g   ┆ g   ┆ i8  ┆ ate ┆ _ar ┆ ond ┆ --- ┆ --- ┆ del ┆ eco ┆ d   ┆ l_h ┆ _da ┆ nt_ ┆ _ev │
│ str ┆ --- ┆ e   ┆ mp  ┆ amp ┆ --- ┆ ati ┆ --- ┆ mp  ┆ str ┆ --- ┆ me  ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ t   ┆ riv ┆ par ┆ f64 ┆ f64 ┆ --- ┆ f32 ┆ f32 ┆ f32 ┆ f64 ┆ _ti ┆ --- ┆ oca ┆     ┆ i8  ┆     ┆ i8  ┆ gme ┆ s   ┆ --- ┆ th  ┆ dul ┆ gme ┆ c   ┆ n_m ┆ f64 ┆ --- ┆ h   ┆ --- ┆ --- ┆ --- ┆     ┆ --- ┆ riv ┆ s   ┆ i64 ┆ i64 ┆ ay_ ┆ nds ┆ --- ┆ oli ┆ y   ┆ cou ┆ ent │
│     ┆ str ┆ --- ┆ --- ┆ --- ┆ str ┆ ons ┆ str ┆ --- ┆     ┆ i64 ┆ --- ┆ dat ┆     ┆ i64 ┆     ┆ str ┆ --- ┆ al  ┆ tur ┆     ┆     ┆ dat ┆     ┆     ┆     ┆     ┆ me  ┆ i64 ┆ l   ┆     ┆     ┆     ┆     ┆ nt_ ┆ --- ┆ str ┆ --- ┆ ed_ ┆ nt_ ┆ --- ┆ m   ┆     ┆ f64 ┆ --- ┆ i64 ┆ i8  ┆ i8  ┆     ┆ dat ┆ al_ ┆ --- ┆     ┆     ┆ sec ┆ --- ┆ boo ┆ day ┆ --- ┆ nt  ┆ --- │
│     ┆     ┆ u32 ┆ u64 ┆ dat ┆     ┆ hip ┆     ┆ u64 ┆     ┆     ┆ i64 ┆ eti ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ e   ┆     ┆     ┆ eti ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ tim ┆ f64 ┆     ┆ f64 ┆ tra ┆ spe ┆ f64 ┆ --- ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆ e   ┆ epo ┆ i64 ┆     ┆     ┆ ond ┆ i64 ┆ l   ┆ --- ┆ boo ┆ --- ┆ boo │
│     ┆     ┆     ┆     ┆ eti ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆ --- ┆     ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆ dat ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ vel ┆ ed_ ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ch  ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ boo ┆ l   ┆ u32 ┆ l   │
│     ┆     ┆     ┆     ┆ me[ ┆     ┆ i32 ┆     ┆     ┆     ┆     ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆     ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆     ┆ eti ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ _ti ┆ mps ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ l   ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ μs, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆ i32 ┆     ┆     ┆     ┆ me  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ UTC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ μs, ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ ]   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ame ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ric ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ a/N ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ew_ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Yor ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ k]  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ MV_ ┆ 202 ┆ 2   ┆ 177 ┆ 202 ┆     ┆ 0   ┆ MTA ┆ 177 ┆ 400 ┆ 177 ┆ 177 ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 400 ┆ 243 ┆ 243 ┆ 40. ┆ -73 ┆ 202 ┆ 40. ┆ -73 ┆ 54. ┆ nul ┆ 177 ┆ 48  ┆ 202 ┆ 0   ┆ 4   ┆ 3   ┆ 0   ┆ nul ┆ 0.1 ┆ 404 ┆ 139 ┆ 28  ┆ 4.9 ┆ 17. ┆ 2.2 ┆ 2.2 ┆ 0.0 ┆ 13. ┆ 61  ┆ 1   ┆ 0   ┆ 0   ┆ 202 ┆ 177 ┆ 506 ┆ 60  ┆ 3   ┆ nul ┆ 66  ┆ fal ┆ fal ┆ tru ┆ 0   ┆ fal │
│ A6- ┆ 603 ┆     ┆ 329 ┆ 6-0 ┆     ┆     ┆ NYC ┆ 329 ┆ 242 ┆ 329 ┆ 329 ┆ 6-0 ┆     ┆     ┆ 010 ┆ A6- ┆ 242 ┆ 6   ┆ 6   ┆ 823 ┆ .93 ┆ 6-0 ┆ 823 ┆ .93 ┆ 782 ┆ l   ┆ 329 ┆     ┆ 6-0 ┆     ┆     ┆     ┆     ┆ l   ┆ 818 ┆ 129 ┆ .20 ┆     ┆ 716 ┆ 3   ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ 6-0 ┆ 329 ┆     ┆     ┆     ┆ l   ┆     ┆ se  ┆ se  ┆ e   ┆     ┆ se  │
│ Wee ┆ 12  ┆     ┆ 093 ┆ 3-1 ┆     ┆     ┆ T_9 ┆ 092 ┆     ┆ 094 ┆ 094 ┆ 3-1 ┆     ┆     ┆ 0   ┆ Wee ┆     ┆     ┆     ┆ 169 ┆ 775 ┆ 3-1 ┆ 627 ┆ 752 ┆ 406 ┆     ┆ 099 ┆     ┆ 3-1 ┆     ┆     ┆     ┆     ┆     ┆ 18  ┆     ┆ 504 ┆     ┆ 09  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3-1 ┆ 043 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ kda ┆     ┆     ┆ 1   ┆ 2   ┆     ┆     ┆ 437 ┆ 4   ┆     ┆ 2   ┆ 2   ┆ 2   ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆ 2   ┆ 2   ┆     ┆ 3   ┆     ┆     ┆ 0   ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ y-S ┆     ┆     ┆     ┆ 04: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 04: ┆     ┆     ┆     ┆ y-S ┆     ┆     ┆     ┆     ┆     ┆ 04: ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ Don ┆     ┆     ┆     ┆ 49: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 49: ┆     ┆     ┆     ┆ Don ┆     ┆     ┆     ┆     ┆     ┆ 48: ┆     ┆     ┆     ┆     ┆     ┆     ┆ 49: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ -00 ┆     ┆     ┆     ┆ 03. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 02  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 44  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 02  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 400 ┆     ┆     ┆     ┆ 097 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ EDT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0_M ┆     ┆     ┆     ┆ 898 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 2_2 ┆     ┆     ┆     ┆ UTC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ MV_ ┆ 202 ┆ 3   ┆ 177 ┆ 202 ┆     ┆ 0   ┆ MTA ┆ 177 ┆ 404 ┆ 177 ┆ 177 ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 404 ┆ 246 ┆ 246 ┆ 40. ┆ -73 ┆ 202 ┆ 40. ┆ -73 ┆ 53. ┆ 1.7 ┆ 177 ┆ 13  ┆ 202 ┆ 0   ┆ 4   ┆ 3   ┆ 0   ┆ 31  ┆ 0.2 ┆ 403 ┆ 171 ┆ 34  ┆ 5.0 ┆ 17. ┆ 2.2 ┆ 2.2 ┆ 0.0 ┆ 13. ┆ 61  ┆ 1   ┆ 0   ┆ 0   ┆ 202 ┆ 177 ┆ 523 ┆ 60  ┆ 3   ┆ 506 ┆ 97  ┆ fal ┆ fal ┆ tru ┆ 0   ┆ fal │
│ A6- ┆ 603 ┆     ┆ 329 ┆ 6-0 ┆     ┆     ┆ NYC ┆ 329 ┆ 129 ┆ 329 ┆ 329 ┆ 6-0 ┆     ┆     ┆ 010 ┆ A6- ┆ 129 ┆ 7   ┆ 7   ┆ 824 ┆ .93 ┆ 6-0 ┆ 824 ┆ .93 ┆ 130 ┆ 857 ┆ 329 ┆     ┆ 6-0 ┆     ┆     ┆     ┆     ┆     ┆ 727 ┆ 338 ┆ .64 ┆     ┆ 482 ┆ 3   ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ 6-0 ┆ 329 ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ se  ┆ e   ┆     ┆ se  │
│ Wee ┆ 12  ┆     ┆ 097 ┆ 3-1 ┆     ┆     ┆ T_9 ┆ 095 ┆     ┆ 099 ┆ 099 ┆ 3-1 ┆     ┆     ┆ 0   ┆ Wee ┆     ┆     ┆     ┆ 26  ┆ 694 ┆ 3-1 ┆ 047 ┆ 721 ┆ 104 ┆ 02  ┆ 100 ┆     ┆ 3-1 ┆     ┆     ┆     ┆     ┆     ┆ 27  ┆     ┆ 037 ┆     ┆ 46  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3-1 ┆ 046 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ kda ┆     ┆     ┆ 6   ┆ 2   ┆     ┆     ┆ 437 ┆ 4   ┆     ┆ 0   ┆ 0   ┆ 2   ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆ 3   ┆ 2   ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ y-S ┆     ┆     ┆     ┆ 04: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 04: ┆     ┆     ┆     ┆ y-S ┆     ┆     ┆     ┆     ┆     ┆ 04: ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ Don ┆     ┆     ┆     ┆ 50: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 49: ┆     ┆     ┆     ┆ Don ┆     ┆     ┆     ┆     ┆     ┆ 49: ┆     ┆     ┆     ┆     ┆     ┆     ┆ 49: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ -00 ┆     ┆     ┆     ┆ 02. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 50  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 14  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 50  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 400 ┆     ┆     ┆     ┆ 848 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ EDT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0_M ┆     ┆     ┆     ┆ 928 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 2_2 ┆     ┆     ┆     ┆ UTC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ MV_ ┆ 202 ┆ 4   ┆ 177 ┆ 202 ┆     ┆ 0   ┆ MTA ┆ 177 ┆ 403 ┆ 177 ┆ 177 ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 403 ┆ 250 ┆ 250 ┆ 40. ┆ -73 ┆ 202 ┆ 40. ┆ -73 ┆ 53. ┆ 1.7 ┆ 177 ┆ 43  ┆ 202 ┆ 0   ┆ 4   ┆ 3   ┆ 0   ┆ 37  ┆ 0.3 ┆ 404 ┆ 118 ┆ 23  ┆ 5.1 ┆ 17. ┆ 2.2 ┆ 2.2 ┆ 0.0 ┆ 13. ┆ 61  ┆ 1   ┆ 0   ┆ 0   ┆ 202 ┆ 177 ┆ 499 ┆ 60  ┆ 3   ┆ 523 ┆ 81  ┆ fal ┆ fal ┆ tru ┆ 0   ┆ fal │
│ A6- ┆ 603 ┆     ┆ 329 ┆ 6-0 ┆     ┆     ┆ NYC ┆ 329 ┆ 338 ┆ 329 ┆ 329 ┆ 6-0 ┆     ┆     ┆ 010 ┆ A6- ┆ 338 ┆ 4   ┆ 4   ┆ 825 ┆ .93 ┆ 6-0 ┆ 824 ┆ .93 ┆ 130 ┆ 857 ┆ 329 ┆     ┆ 6-0 ┆     ┆     ┆     ┆     ┆     ┆ 636 ┆ 837 ┆ .23 ┆     ┆ 407 ┆ 3   ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ 6-0 ┆ 329 ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ se  ┆ e   ┆     ┆ se  │
│ Wee ┆ 12  ┆     ┆ 100 ┆ 3-1 ┆     ┆     ┆ T_9 ┆ 098 ┆     ┆ 100 ┆ 100 ┆ 3-1 ┆     ┆     ┆ 0   ┆ Wee ┆     ┆     ┆     ┆ 612 ┆ 595 ┆ 3-1 ┆ 047 ┆ 721 ┆ 104 ┆ 02  ┆ 104 ┆     ┆ 3-1 ┆     ┆     ┆     ┆     ┆     ┆ 36  ┆     ┆ 676 ┆     ┆ 29  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3-1 ┆ 050 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ kda ┆     ┆     ┆ 6   ┆ 2   ┆     ┆     ┆ 437 ┆ 4   ┆     ┆ 3   ┆ 3   ┆ 2   ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆ 5   ┆ 2   ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ y-S ┆     ┆     ┆     ┆ 04: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 04: ┆     ┆     ┆     ┆ y-S ┆     ┆     ┆     ┆     ┆     ┆ 04: ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ Don ┆     ┆     ┆     ┆ 50: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 50: ┆     ┆     ┆     ┆ Don ┆     ┆     ┆     ┆     ┆     ┆ 49: ┆     ┆     ┆     ┆     ┆     ┆     ┆ 50: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ -00 ┆     ┆     ┆     ┆ 32. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 03  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 14  ┆     ┆     ┆     ┆     ┆     ┆     ┆ 03  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 400 ┆     ┆     ┆     ┆ 850 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ EDT ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 0_M ┆     ┆     ┆     ┆ 213 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 2_2 ┆     ┆     ┆     ┆ UTC ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ MV_ ┆ 202 ┆ 5   ┆ 177 ┆ 202 ┆     ┆ 0   ┆ MTA ┆ 177 ┆ 404 ┆ 177 ┆ 177 ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 404 ┆ 253 ┆ 253 ┆ 40. ┆ -73 ┆ 202 ┆ 40. ┆ -73 ┆ 97. ┆ 79. ┆ 177 ┆ 171 ┆ 202 ┆ 0   ┆ 4   ┆ 3   ┆ 0   ┆ 26  ┆ 0.4 ┆ 400 ┆ 779 ┆ 155 ┆ 5.0 ┆ 17. ┆ 2.2 ┆ 2.2 ┆ 0.0 ┆ 13. ┆ 61  ┆ 1   ┆ 0   ┆ 0   ┆ 202 ┆ 177 ┆ 516 ┆ 60  ┆ 3   ┆ 499 ┆ 99  ┆ fal ┆ fal ┆ tru ┆ 0   ┆ fal │
│ A6- ┆ 603 ┆     ┆ 329 ┆ 6-0 ┆     ┆     ┆ NYC ┆ 329 ┆ 837 ┆ 329 ┆ 329 ┆ 6-0 ┆     ┆     ┆ 010 ┆ A6- ┆ 837 ┆ 0   ┆ 0   ┆ 826 ┆ .93 ┆ 6-0 ┆ 827 ┆ .93 ┆ 594 ┆ 063 ┆ 329 ┆     ┆ 6-0 ┆     ┆     ┆     ┆     ┆     ┆ 545 ┆ 248 ┆ .22 ┆     ┆ 272 ┆ 3   ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ 6-0 ┆ 329 ┆     ┆     ┆     ┆     ┆     ┆ se  ┆ se  ┆ e   ┆     ┆ se  │

In [73]:
data.shape

(62783, 61)

In [74]:
data.null_count()

shape: (1, 61)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ tri ┆ sta ┆ sto ┆ fee ┆ fet ┆ sta ┆ sch ┆ veh ┆ tri ┆ sto ┆ arr ┆ dep ┆ eve ┆ rou ┆ dir ┆ sha ┆ ser ┆ sto ┆ sch ┆ sch ┆ sto ┆ sto ┆ veh ┆ lat ┆ lon ┆ bea ┆ spe ┆ nex ┆ tra ┆ eve ┆ hou ┆ wee ┆ mon ┆ is_ ┆ sch ┆ tri ┆ nex ┆ seg ┆ seg ┆ sch ┆ tem ┆ pre ┆ rai ┆ sno ┆ win ┆ wea ┆ is_ ┆ is_ ┆ is_ ┆ ser ┆ sch ┆ del ┆ rid ┆ tra ┆ ups ┆ hea ┆ is_ ┆ is_ ┆ is_ ┆ maj ┆ has │
│ p_i ┆ rt_ ┆ p_s ┆ d_t ┆ ch_ ┆ rt_ ┆ edu ┆ icl ┆ p_t ┆ p_i ┆ iva ┆ art ┆ nt_ ┆ te_ ┆ ect ┆ pe_ ┆ vic ┆ p_i ┆ edu ┆ edu ┆ p_l ┆ p_l ┆ icl ┆ itu ┆ git ┆ rin ┆ ed_ ┆ t_a ┆ vel ┆ nt_ ┆ r   ┆ kda ┆ th  ┆ pea ┆ edu ┆ p_p ┆ t_s ┆ men ┆ men ┆ edu ┆ per ┆ cip ┆ n_m ┆ wfa ┆ dsp ┆ the ┆ rai ┆ sno ┆ fog ┆ vic ┆ edu ┆ ay_ ┆ ers ┆ nsf ┆ tre ┆ dwa ┆ wee ┆ fed ┆ sch ┆ or_ ┆ _ma │
│ d   ┆ dat ┆ equ ┆ ime ┆ tim ┆ tim ┆ le_ ┆ e_i ┆ ime ┆ d   ┆ l_t ┆ ure ┆ tim ┆ id  ┆ ion ┆ id  ┆ e_i ┆ d_r ┆ led ┆ led ┆ at  ┆ on  ┆ e_t ┆ de  ┆ ude ┆ g   ┆ mps ┆ rri ┆ _ti ┆ tim ┆ --- ┆ y   ┆ --- ┆ k   ┆ led ┆ rog ┆ top ┆ t_l ┆ t_s ┆ led ┆ atu ┆ ita ┆ m   ┆ ll_ ┆ eed ┆ rco ┆ nin ┆ win ┆ --- ┆ e_d ┆ led ┆ sec ┆ hip ┆ ers ┆ am_ ┆ y_s ┆ ken ┆ era ┆ ool ┆ eve ┆ jor │
│ --- ┆ e   ┆ enc ┆ sta ┆ est ┆ e   ┆ rel ┆ d   ┆ sta ┆ --- ┆ ime ┆ _ti ┆ e   ┆ --- ┆ _id ┆ --- ┆ d   ┆ igh ┆ _ar ┆ _de ┆ --- ┆ --- ┆ ime ┆ --- ┆ --- ┆ --- ┆ --- ┆ val ┆ me  ┆ e_l ┆ u32 ┆ --- ┆ u32 ┆ --- ┆ _se ┆ res ┆ _id ┆ eng ┆ che ┆ _se ┆ re_ ┆ tio ┆ --- ┆ cm  ┆ _km ┆ de  ┆ g   ┆ g   ┆ u32 ┆ ate ┆ _ar ┆ ond ┆ --- ┆ --- ┆ del ┆ eco ┆ d   ┆ l_h ┆ _da ┆ nt_ ┆ _ev │
│ u32 ┆ --- ┆ e   ┆ mp  ┆ amp ┆ --- ┆ ati ┆ --- ┆ mp  ┆ u32 ┆ --- ┆ me  ┆ --- ┆ u32 ┆ --- ┆ u32 ┆ --- ┆ t   ┆ riv ┆ par ┆ u32 ┆ u32 ┆ --- ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ _ti ┆ --- ┆ oca ┆     ┆ u32 ┆     ┆ u32 ┆ gme ┆ s   ┆ --- ┆ th  ┆ dul ┆ gme ┆ c   ┆ n_m ┆ u32 ┆ --- ┆ h   ┆ --- ┆ --- ┆ --- ┆     ┆ --- ┆ riv ┆ s   ┆ u32 ┆ u32 ┆ ay_ ┆ nds ┆ --- ┆ oli ┆ y   ┆ cou ┆ ent │
│     ┆ u32 ┆ --- ┆ --- ┆ --- ┆ u32 ┆ ons ┆ u32 ┆ --- ┆     ┆ u32 ┆ --- ┆ u32 ┆     ┆ u32 ┆     ┆ u32 ┆ --- ┆ al  ┆ tur ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆ me  ┆ u32 ┆ l   ┆     ┆     ┆     ┆     ┆ nt_ ┆ --- ┆ u32 ┆ --- ┆ ed_ ┆ nt_ ┆ --- ┆ m   ┆     ┆ u32 ┆ --- ┆ u32 ┆ u32 ┆ u32 ┆     ┆ u32 ┆ al_ ┆ --- ┆     ┆     ┆ sec ┆ --- ┆ u32 ┆ day ┆ --- ┆ nt  ┆ --- │
│     ┆     ┆ u32 ┆ u32 ┆ u32 ┆     ┆ hip ┆     ┆ u32 ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ tim ┆ u32 ┆     ┆ u32 ┆ tra ┆ spe ┆ u32 ┆ --- ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆ epo ┆ u32 ┆     ┆     ┆ ond ┆ u32 ┆     ┆ --- ┆ u32 ┆ --- ┆ u32 │
│     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ vel ┆ ed_ ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ch  ┆     ┆     ┆     ┆ s   ┆     ┆     ┆ u32 ┆     ┆ u32 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ _ti ┆ mps ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆ me  ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 373 ┆ 373 ┆ 373 ┆ 373 ┆ 376 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 121 ┆ 0   ┆ 121 ┆ 369 ┆ 369 ┆ 369 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 121 ┆ 690 ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆ 8   ┆ 8   ┆ 8   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆ 9   ┆ 9   ┆ 9   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [75]:
features = [
    "route_id",
    "direction_id",
    "shape_id",
    "service_id",
 
    "stop_sequence",
    "trip_progress",
 
    "hour",
    "weekday",
    "month",
    "is_peak",
 
    "scheduled_arrival",
    "scheduled_departure",
    "scheduled_segment_time",
 
    "stop_lat",
    "stop_lon",
 
    "latitude",
    "longitude",
    "bearing",
    "temperature_c",
    "precipitation_mm",
    "snowfall_cm",
    "windspeed_kmh",
    "is_raining",
    "is_snowing",
    "is_fog",
    "weathercode",
    "segment_length",
    "scheduled_segment_speed_mps",
    "upstream_delay_seconds",
    "speed_mps",
    "headway_seconds",
    "is_weekend",
    "is_federal_holiday",
    "is_school_day",
    "has_major_event",

    
    "ridership",
    "transfers",
]
target = "travel_time"
id_cols = ["trip_id", "start_date"]

print(data.columns)
 
# %%
model_ready = data.select(id_cols + features + [target]).drop_nulls(subset=features + [target])
 
print(model_ready.shape)
print(model_ready.null_count())
print(model_ready.head())

['trip_id', 'start_date', 'stop_sequence', 'feed_timestamp', 'fetch_timestamp', 'start_time', 'schedule_relationship', 'vehicle_id', 'trip_timestamp', 'stop_id', 'arrival_time', 'departure_time', 'event_time', 'route_id', 'direction_id', 'shape_id', 'service_id', 'stop_id_right', 'scheduled_arrival', 'scheduled_departure', 'stop_lat', 'stop_lon', 'vehicle_time', 'latitude', 'longitude', 'bearing', 'speed_mps', 'next_arrival_time', 'travel_time', 'event_time_local', 'hour', 'weekday', 'month', 'is_peak', 'scheduled_segment_time', 'trip_progress', 'next_stop_id', 'segment_length', 'segment_scheduled_travel_time', 'scheduled_segment_speed_mps', 'temperature_c', 'precipitation_mm', 'rain_mm', 'snowfall_cm', 'windspeed_kmh', 'weathercode', 'is_raining', 'is_snowing', 'is_fog', 'service_date', 'scheduled_arrival_epoch', 'delay_seconds', 'ridership', 'transfers', 'upstream_delay_seconds', 'headway_seconds', 'is_weekend', 'is_federal_holiday', 'is_school_day', 'major_event_count', 'has_major_event']
(54720, 40)
shape: (1, 40)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┬───────┬───────┬───────┐
│ tri ┆ sta ┆ rou ┆ dir ┆ sha ┆ ser ┆ sto ┆ tri ┆ hou ┆ wee ┆ mon ┆ is_ ┆ sch ┆ sch ┆ sch ┆ sto ┆ sto ┆ lat ┆ lon ┆ bea ┆ tem ┆ pre ┆ sno ┆ win ┆ is_ ┆ is_ ┆ is_ ┆ wea ┆ seg ┆ sch ┆ ups ┆ spe ┆ hea ┆ is_ ┆ is_ ┆ is_ ┆ has_ma ┆ rider ┆ trans ┆ trave │
│ p_i ┆ rt_ ┆ te_ ┆ ect ┆ pe_ ┆ vic ┆ p_s ┆ p_p ┆ r   ┆ kda ┆ th  ┆ pea ┆ edu ┆ edu ┆ edu ┆ p_l ┆ p_l ┆ itu ┆ git ┆ rin ┆ per ┆ cip ┆ wfa ┆ dsp ┆ rai ┆ sno ┆ fog ┆ the ┆ men ┆ edu ┆ tre ┆ ed_ ┆ dwa ┆ wee ┆ fed ┆ sch ┆ jor_ev ┆ ship  ┆ fers  ┆ l_tim │
│ d   ┆ dat ┆ id  ┆ ion ┆ id  ┆ e_i ┆ equ ┆ rog ┆ --- ┆ y   ┆ --- ┆ k   ┆ led ┆ led ┆ led ┆ at  ┆ on  ┆ de  ┆ ude ┆ g   ┆ atu ┆ ita ┆ ll_ ┆ eed ┆ nin ┆ win ┆ --- ┆ rco ┆ t_l ┆ led ┆ am_ ┆ mps ┆ y_s ┆ ken ┆ era ┆ ool ┆ ent    ┆ ---   ┆ ---   ┆ e     │
│ --- ┆ e   ┆ --- ┆ _id ┆ --- ┆ d   ┆ enc ┆ res ┆ u32 ┆ --- ┆ u32 ┆ --- ┆ _ar ┆ _de ┆ _se ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ re_ ┆ tio ┆ cm  ┆ _km ┆ g   ┆ g   ┆ u32 ┆ de  ┆ eng ┆ _se ┆ del ┆ --- ┆ eco ┆ d   ┆ l_h ┆ _da ┆ ---    ┆ u32   ┆ u32   ┆ ---   │
│ u32 ┆ --- ┆ u32 ┆ --- ┆ u32 ┆ --- ┆ e   ┆ s   ┆     ┆ u32 ┆     ┆ u32 ┆ riv ┆ par ┆ gme ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ u32 ┆ c   ┆ n_m ┆ --- ┆ h   ┆ --- ┆ --- ┆     ┆ --- ┆ th  ┆ gme ┆ ay_ ┆ u32 ┆ nds ┆ --- ┆ oli ┆ y   ┆ u32    ┆       ┆       ┆ u32   │
│     ┆ u32 ┆     ┆ u32 ┆     ┆ u32 ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ al  ┆ tur ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ m   ┆ u32 ┆ --- ┆ u32 ┆ u32 ┆     ┆ u32 ┆ --- ┆ nt_ ┆ sec ┆     ┆ --- ┆ u32 ┆ day ┆ --- ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ u32 ┆     ┆     ┆     ┆     ┆ --- ┆ e   ┆ tim ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆ u32 ┆ spe ┆ ond ┆     ┆ u32 ┆     ┆ --- ┆ u32 ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed_ ┆ s   ┆     ┆     ┆     ┆ u32 ┆     ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mps ┆ --- ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╪═══════╪═══════╪═══════╡
│ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0      ┆ 0     ┆ 0     ┆ 0     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴────────┴───────┴───────┴───────┘
shape: (5, 40)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┬───────┬───────┬───────┐
│ tri ┆ sta ┆ rou ┆ dir ┆ sha ┆ ser ┆ sto ┆ tri ┆ hou ┆ wee ┆ mon ┆ is_ ┆ sch ┆ sch ┆ sch ┆ sto ┆ sto ┆ lat ┆ lon ┆ bea ┆ tem ┆ pre ┆ sno ┆ win ┆ is_ ┆ is_ ┆ is_ ┆ wea ┆ seg ┆ sch ┆ ups ┆ spe ┆ hea ┆ is_ ┆ is_ ┆ is_ ┆ has_ma ┆ rider ┆ trans ┆ trave │
│ p_i ┆ rt_ ┆ te_ ┆ ect ┆ pe_ ┆ vic ┆ p_s ┆ p_p ┆ r   ┆ kda ┆ th  ┆ pea ┆ edu ┆ edu ┆ edu ┆ p_l ┆ p_l ┆ itu ┆ git ┆ rin ┆ per ┆ cip ┆ wfa ┆ dsp ┆ rai ┆ sno ┆ fog ┆ the ┆ men ┆ edu ┆ tre ┆ ed_ ┆ dwa ┆ wee ┆ fed ┆ sch ┆ jor_ev ┆ ship  ┆ fers  ┆ l_tim │
│ d   ┆ dat ┆ id  ┆ ion ┆ id  ┆ e_i ┆ equ ┆ rog ┆ --- ┆ y   ┆ --- ┆ k   ┆ led ┆ led ┆ led ┆ at  ┆ on  ┆ de  ┆ ude ┆ g   ┆ atu ┆ ita ┆ ll_ ┆ eed ┆ nin ┆ win ┆ --- ┆ rco ┆ t_l ┆ led ┆ am_ ┆ mps ┆ y_s ┆ ken ┆ era ┆ ool ┆ ent    ┆ ---   ┆ ---   ┆ e     │
│ --- ┆ e   ┆ --- ┆ _id ┆ --- ┆ d   ┆ enc ┆ res ┆ i8  ┆ --- ┆ i8  ┆ --- ┆ _ar ┆ _de ┆ _se ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ re_ ┆ tio ┆ cm  ┆ _km ┆ g   ┆ g   ┆ i8  ┆ de  ┆ eng ┆ _se ┆ del ┆ --- ┆ eco ┆ d   ┆ l_h ┆ _da ┆ ---    ┆ i64   ┆ i64   ┆ ---   │
│ str ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ e   ┆ s   ┆     ┆ i8  ┆     ┆ i8  ┆ riv ┆ par ┆ gme ┆ f64 ┆ f64 ┆ f32 ┆ f32 ┆ f32 ┆ c   ┆ n_m ┆ --- ┆ h   ┆ --- ┆ --- ┆     ┆ --- ┆ th  ┆ gme ┆ ay_ ┆ f64 ┆ nds ┆ --- ┆ oli ┆ y   ┆ bool   ┆       ┆       ┆ i64   │
│     ┆ str ┆     ┆ i64 ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ al  ┆ tur ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ m   ┆ f64 ┆ --- ┆ i8  ┆ i8  ┆     ┆ i64 ┆ --- ┆ nt_ ┆ sec ┆     ┆ --- ┆ boo ┆ day ┆ --- ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ f64 ┆     ┆     ┆     ┆     ┆ --- ┆ e   ┆ tim ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆ f64 ┆ spe ┆ ond ┆     ┆ i64 ┆ l   ┆ --- ┆ boo ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆ --- ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed_ ┆ s   ┆     ┆     ┆     ┆ boo ┆ l   ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mps ┆ --- ┆     ┆     ┆     ┆ l   ┆     ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╪═══════╪═══════╪═══════╡
│ MV_ ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 3   ┆ 0.2 ┆ 0   ┆ 4   ┆ 3   ┆ 0   ┆ 246 ┆ 246 ┆ 31  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 53. ┆ 17. ┆ 2.2 ┆ 0.0 ┆ 13. ┆ 1   ┆ 0   ┆ 0   ┆ 61  ┆ 171 ┆ 5.0 ┆ 506 ┆ 1.7 ┆ 97  ┆ fal ┆ fal ┆ tru ┆ false  ┆ 60    ┆ 3     ┆ 13    │
│ A6- ┆ 603 ┆     ┆     ┆ 010 ┆ A6- ┆     ┆ 727 ┆     ┆     ┆     ┆     ┆ 7   ┆ 7   ┆     ┆ 824 ┆ .93 ┆ 824 ┆ .93 ┆ 130 ┆ 3   ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ .64 ┆ 482 ┆     ┆ 857 ┆     ┆ se  ┆ se  ┆ e   ┆        ┆       ┆       ┆       │
│ Wee ┆ 12  ┆     ┆     ┆ 0   ┆ Wee ┆     ┆ 27  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 26  ┆ 694 ┆ 047 ┆ 721 ┆ 104 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 037 ┆ 46  ┆     ┆ 02  ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-S ┆     ┆     ┆     ┆     ┆ y-S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ Don ┆     ┆     ┆     ┆     ┆ Don ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ -00 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 400 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 0_M ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 2_2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ MV_ ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 4   ┆ 0.3 ┆ 0   ┆ 4   ┆ 3   ┆ 0   ┆ 250 ┆ 250 ┆ 37  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 53. ┆ 17. ┆ 2.2 ┆ 0.0 ┆ 13. ┆ 1   ┆ 0   ┆ 0   ┆ 61  ┆ 118 ┆ 5.1 ┆ 523 ┆ 1.7 ┆ 81  ┆ fal ┆ fal ┆ tru ┆ false  ┆ 60    ┆ 3     ┆ 43    │
│ A6- ┆ 603 ┆     ┆     ┆ 010 ┆ A6- ┆     ┆ 636 ┆     ┆     ┆     ┆     ┆ 4   ┆ 4   ┆     ┆ 825 ┆ .93 ┆ 824 ┆ .93 ┆ 130 ┆ 3   ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ .23 ┆ 407 ┆     ┆ 857 ┆     ┆ se  ┆ se  ┆ e   ┆        ┆       ┆       ┆       │
│ Wee ┆ 12  ┆     ┆     ┆ 0   ┆ Wee ┆     ┆ 36  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 612 ┆ 595 ┆ 047 ┆ 721 ┆ 104 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 676 ┆ 29  ┆     ┆ 02  ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-S ┆     ┆     ┆     ┆     ┆ y-S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ Don ┆     ┆     ┆     ┆     ┆ Don ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ -00 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 400 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 0_M ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 2_2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ MV_ ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 5   ┆ 0.4 ┆ 0   ┆ 4   ┆ 3   ┆ 0   ┆ 253 ┆ 253 ┆ 26  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 97. ┆ 17. ┆ 2.2 ┆ 0.0 ┆ 13. ┆ 1   ┆ 0   ┆ 0   ┆ 61  ┆ 779 ┆ 5.0 ┆ 499 ┆ 79. ┆ 99  ┆ fal ┆ fal ┆ tru ┆ false  ┆ 60    ┆ 3     ┆ 171   │
│ A6- ┆ 603 ┆     ┆     ┆ 010 ┆ A6- ┆     ┆ 545 ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆ 826 ┆ .93 ┆ 827 ┆ .93 ┆ 594 ┆ 3   ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ .22 ┆ 272 ┆     ┆ 063 ┆     ┆ se  ┆ se  ┆ e   ┆        ┆       ┆       ┆       │
│ Wee ┆ 12  ┆     ┆     ┆ 0   ┆ Wee ┆     ┆ 45  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 531 ┆ 526 ┆ 339 ┆ 521 ┆ 643 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 457 ┆ 55  ┆     ┆ 506 ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-S ┆     ┆     ┆     ┆     ┆ y-S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ Don ┆     ┆     ┆     ┆     ┆ Don ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ -00 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 400 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 0_M ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 2_2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ MV_ ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 6   ┆ 0.5 ┆ 0   ┆ 4   ┆ 3   ┆ 0   ┆ 270 ┆ 270 ┆ 172 ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 93. ┆ 17. ┆ 2.2 ┆ 0.0 ┆ 13. ┆ 1   ┆ 0   ┆ 0   ┆ 61  ┆ 243 ┆ 5.0 ┆ 516 ┆ 63. ┆ 87  ┆ fal ┆ fal ┆ tru ┆ false  ┆ 60    ┆ 3     ┆ 35    │
│ A6- ┆ 603 ┆     ┆     ┆ 010 ┆ A6- ┆     ┆ 454 ┆     ┆     ┆     ┆     ┆ 2   ┆ 2   ┆     ┆ 830 ┆ .94 ┆ 830 ┆ .94 ┆ 631 ┆ 3   ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ .05 ┆ 636 ┆     ┆ 665 ┆     ┆ se  ┆ se  ┆ e   ┆        ┆       ┆       ┆       │
│ Wee ┆ 12  ┆     ┆     ┆ 0   ┆ Wee ┆     ┆ 55  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 904 ┆ 027 ┆ 944 ┆ 033 ┆ 21  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 746 ┆ 97  ┆     ┆ 023 ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-S ┆     ┆     ┆     ┆     ┆ y-S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ Don ┆     ┆     ┆     ┆     ┆ Don ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ -00 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 400 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 0_M ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 2_2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ MV_ ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 9   ┆ 0.8 ┆ 0   ┆ 4   ┆ 3   ┆ 0   ┆ 282 ┆ 282 ┆ 69  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 65. ┆ 17. ┆ 2.2 ┆ 0.0 ┆ 13. ┆ 1   ┆ 0   ┆ 0   ┆ 61  ┆ 166 ┆ 5.0 ┆ 497 ┆ 11. ┆ 81  ┆ fal ┆ fal ┆ tru ┆ false  ┆ 60    ┆ 3     ┆ 29    │
│ A6- ┆ 603 ┆     ┆     ┆ 010 ┆ A6- ┆     ┆ 181 ┆     ┆     ┆     ┆     ┆ 4   ┆ 4   ┆     ┆ 835 ┆ .93 ┆ 834 ┆ .93 ┆ 148 ┆ 3   ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ .57 ┆ 477 ┆     ┆ 281 ┆     ┆ se  ┆ se  ┆ e   ┆        ┆       ┆       ┆       │
│ Wee ┆ 12  ┆     ┆     ┆ 0   ┆ Wee ┆     ┆ 82  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 242 ┆ 749 ┆ 999 ┆ 769 ┆ 415 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 416 ┆ 02  ┆     ┆ 706 ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │

In [76]:
model_ready.columns

['trip_id',
 'start_date',
 'route_id',
 'direction_id',
 'shape_id',
 'service_id',
 'stop_sequence',
 'trip_progress',
 'hour',
 'weekday',
 'month',
 'is_peak',
 'scheduled_arrival',
 'scheduled_departure',
 'scheduled_segment_time',
 'stop_lat',
 'stop_lon',
 'latitude',
 'longitude',
 'bearing',
 'temperature_c',
 'precipitation_mm',
 'snowfall_cm',
 'windspeed_kmh',
 'is_raining',
 'is_snowing',
 'is_fog',
 'weathercode',
 'segment_length',
 'scheduled_segment_speed_mps',
 'upstream_delay_seconds',
 'speed_mps',
 'headway_seconds',
 'is_weekend',
 'is_federal_holiday',
 'is_school_day',
 'has_major_event',
 'ridership',
 'transfers',
 'travel_time']

In [77]:
model_ready

shape: (54_720, 40)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┬───────┬───────┬───────┐
│ tri ┆ sta ┆ rou ┆ dir ┆ sha ┆ ser ┆ sto ┆ tri ┆ hou ┆ wee ┆ mon ┆ is_ ┆ sch ┆ sch ┆ sch ┆ sto ┆ sto ┆ lat ┆ lon ┆ bea ┆ tem ┆ pre ┆ sno ┆ win ┆ is_ ┆ is_ ┆ is_ ┆ wea ┆ seg ┆ sch ┆ ups ┆ spe ┆ hea ┆ is_ ┆ is_ ┆ is_ ┆ has_ma ┆ rider ┆ trans ┆ trave │
│ p_i ┆ rt_ ┆ te_ ┆ ect ┆ pe_ ┆ vic ┆ p_s ┆ p_p ┆ r   ┆ kda ┆ th  ┆ pea ┆ edu ┆ edu ┆ edu ┆ p_l ┆ p_l ┆ itu ┆ git ┆ rin ┆ per ┆ cip ┆ wfa ┆ dsp ┆ rai ┆ sno ┆ fog ┆ the ┆ men ┆ edu ┆ tre ┆ ed_ ┆ dwa ┆ wee ┆ fed ┆ sch ┆ jor_ev ┆ ship  ┆ fers  ┆ l_tim │
│ d   ┆ dat ┆ id  ┆ ion ┆ id  ┆ e_i ┆ equ ┆ rog ┆ --- ┆ y   ┆ --- ┆ k   ┆ led ┆ led ┆ led ┆ at  ┆ on  ┆ de  ┆ ude ┆ g   ┆ atu ┆ ita ┆ ll_ ┆ eed ┆ nin ┆ win ┆ --- ┆ rco ┆ t_l ┆ led ┆ am_ ┆ mps ┆ y_s ┆ ken ┆ era ┆ ool ┆ ent    ┆ ---   ┆ ---   ┆ e     │
│ --- ┆ e   ┆ --- ┆ _id ┆ --- ┆ d   ┆ enc ┆ res ┆ i8  ┆ --- ┆ i8  ┆ --- ┆ _ar ┆ _de ┆ _se ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ re_ ┆ tio ┆ cm  ┆ _km ┆ g   ┆ g   ┆ i8  ┆ de  ┆ eng ┆ _se ┆ del ┆ --- ┆ eco ┆ d   ┆ l_h ┆ _da ┆ ---    ┆ i64   ┆ i64   ┆ ---   │
│ str ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ e   ┆ s   ┆     ┆ i8  ┆     ┆ i8  ┆ riv ┆ par ┆ gme ┆ f64 ┆ f64 ┆ f32 ┆ f32 ┆ f32 ┆ c   ┆ n_m ┆ --- ┆ h   ┆ --- ┆ --- ┆     ┆ --- ┆ th  ┆ gme ┆ ay_ ┆ f64 ┆ nds ┆ --- ┆ oli ┆ y   ┆ bool   ┆       ┆       ┆ i64   │
│     ┆ str ┆     ┆ i64 ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ al  ┆ tur ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ m   ┆ f64 ┆ --- ┆ i8  ┆ i8  ┆     ┆ i64 ┆ --- ┆ nt_ ┆ sec ┆     ┆ --- ┆ boo ┆ day ┆ --- ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆ u32 ┆ f64 ┆     ┆     ┆     ┆     ┆ --- ┆ e   ┆ tim ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆ f64 ┆ spe ┆ ond ┆     ┆ i64 ┆ l   ┆ --- ┆ boo ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆ --- ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed_ ┆ s   ┆     ┆     ┆     ┆ boo ┆ l   ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mps ┆ --- ┆     ┆     ┆     ┆ l   ┆     ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╪═══════╪═══════╪═══════╡
│ MV_ ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 3   ┆ 0.2 ┆ 0   ┆ 4   ┆ 3   ┆ 0   ┆ 246 ┆ 246 ┆ 31  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 53. ┆ 17. ┆ 2.2 ┆ 0.0 ┆ 13. ┆ 1   ┆ 0   ┆ 0   ┆ 61  ┆ 171 ┆ 5.0 ┆ 506 ┆ 1.7 ┆ 97  ┆ fal ┆ fal ┆ tru ┆ false  ┆ 60    ┆ 3     ┆ 13    │
│ A6- ┆ 603 ┆     ┆     ┆ 010 ┆ A6- ┆     ┆ 727 ┆     ┆     ┆     ┆     ┆ 7   ┆ 7   ┆     ┆ 824 ┆ .93 ┆ 824 ┆ .93 ┆ 130 ┆ 3   ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ .64 ┆ 482 ┆     ┆ 857 ┆     ┆ se  ┆ se  ┆ e   ┆        ┆       ┆       ┆       │
│ Wee ┆ 12  ┆     ┆     ┆ 0   ┆ Wee ┆     ┆ 27  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 26  ┆ 694 ┆ 047 ┆ 721 ┆ 104 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 037 ┆ 46  ┆     ┆ 02  ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-S ┆     ┆     ┆     ┆     ┆ y-S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ Don ┆     ┆     ┆     ┆     ┆ Don ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ -00 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 400 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 0_M ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 2_2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ MV_ ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 4   ┆ 0.3 ┆ 0   ┆ 4   ┆ 3   ┆ 0   ┆ 250 ┆ 250 ┆ 37  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 53. ┆ 17. ┆ 2.2 ┆ 0.0 ┆ 13. ┆ 1   ┆ 0   ┆ 0   ┆ 61  ┆ 118 ┆ 5.1 ┆ 523 ┆ 1.7 ┆ 81  ┆ fal ┆ fal ┆ tru ┆ false  ┆ 60    ┆ 3     ┆ 43    │
│ A6- ┆ 603 ┆     ┆     ┆ 010 ┆ A6- ┆     ┆ 636 ┆     ┆     ┆     ┆     ┆ 4   ┆ 4   ┆     ┆ 825 ┆ .93 ┆ 824 ┆ .93 ┆ 130 ┆ 3   ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ .23 ┆ 407 ┆     ┆ 857 ┆     ┆ se  ┆ se  ┆ e   ┆        ┆       ┆       ┆       │
│ Wee ┆ 12  ┆     ┆     ┆ 0   ┆ Wee ┆     ┆ 36  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 612 ┆ 595 ┆ 047 ┆ 721 ┆ 104 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 676 ┆ 29  ┆     ┆ 02  ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-S ┆     ┆     ┆     ┆     ┆ y-S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ Don ┆     ┆     ┆     ┆     ┆ Don ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ -00 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 400 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 0_M ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 2_2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ MV_ ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 5   ┆ 0.4 ┆ 0   ┆ 4   ┆ 3   ┆ 0   ┆ 253 ┆ 253 ┆ 26  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 97. ┆ 17. ┆ 2.2 ┆ 0.0 ┆ 13. ┆ 1   ┆ 0   ┆ 0   ┆ 61  ┆ 779 ┆ 5.0 ┆ 499 ┆ 79. ┆ 99  ┆ fal ┆ fal ┆ tru ┆ false  ┆ 60    ┆ 3     ┆ 171   │
│ A6- ┆ 603 ┆     ┆     ┆ 010 ┆ A6- ┆     ┆ 545 ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆ 826 ┆ .93 ┆ 827 ┆ .93 ┆ 594 ┆ 3   ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ .22 ┆ 272 ┆     ┆ 063 ┆     ┆ se  ┆ se  ┆ e   ┆        ┆       ┆       ┆       │
│ Wee ┆ 12  ┆     ┆     ┆ 0   ┆ Wee ┆     ┆ 45  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 531 ┆ 526 ┆ 339 ┆ 521 ┆ 643 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 457 ┆ 55  ┆     ┆ 506 ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-S ┆     ┆     ┆     ┆     ┆ y-S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ Don ┆     ┆     ┆     ┆     ┆ Don ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ -00 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 400 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 0_M ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 2_2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ MV_ ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 6   ┆ 0.5 ┆ 0   ┆ 4   ┆ 3   ┆ 0   ┆ 270 ┆ 270 ┆ 172 ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 93. ┆ 17. ┆ 2.2 ┆ 0.0 ┆ 13. ┆ 1   ┆ 0   ┆ 0   ┆ 61  ┆ 243 ┆ 5.0 ┆ 516 ┆ 63. ┆ 87  ┆ fal ┆ fal ┆ tru ┆ false  ┆ 60    ┆ 3     ┆ 35    │
│ A6- ┆ 603 ┆     ┆     ┆ 010 ┆ A6- ┆     ┆ 454 ┆     ┆     ┆     ┆     ┆ 2   ┆ 2   ┆     ┆ 830 ┆ .94 ┆ 830 ┆ .94 ┆ 631 ┆ 3   ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ .05 ┆ 636 ┆     ┆ 665 ┆     ┆ se  ┆ se  ┆ e   ┆        ┆       ┆       ┆       │
│ Wee ┆ 12  ┆     ┆     ┆ 0   ┆ Wee ┆     ┆ 55  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 904 ┆ 027 ┆ 944 ┆ 033 ┆ 21  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 746 ┆ 97  ┆     ┆ 023 ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-S ┆     ┆     ┆     ┆     ┆ y-S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ Don ┆     ┆     ┆     ┆     ┆ Don ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ -00 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 400 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 0_M ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 2_2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ MV_ ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 9   ┆ 0.8 ┆ 0   ┆ 4   ┆ 3   ┆ 0   ┆ 282 ┆ 282 ┆ 69  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 65. ┆ 17. ┆ 2.2 ┆ 0.0 ┆ 13. ┆ 1   ┆ 0   ┆ 0   ┆ 61  ┆ 166 ┆ 5.0 ┆ 497 ┆ 11. ┆ 81  ┆ fal ┆ fal ┆ tru ┆ false  ┆ 60    ┆ 3     ┆ 29    │
│ A6- ┆ 603 ┆     ┆     ┆ 010 ┆ A6- ┆     ┆ 181 ┆     ┆     ┆     ┆     ┆ 4   ┆ 4   ┆     ┆ 835 ┆ .93 ┆ 834 ┆ .93 ┆ 148 ┆ 3   ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ .57 ┆ 477 ┆     ┆ 281 ┆     ┆ se  ┆ se  ┆ e   ┆        ┆       ┆       ┆       │
│ Wee ┆ 12  ┆     ┆     ┆ 0   ┆ Wee ┆     ┆ 82  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 242 ┆ 749 ┆ 999 ┆ 769 ┆ 415 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 416 ┆ 02  ┆     ┆ 706 ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-S ┆     ┆     ┆     ┆     ┆ y-S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ Don ┆     ┆     ┆     ┆     ┆ Don ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ -00 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 400 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 0_M ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 2_2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ MV_ ┆ 202 ┆ M2  ┆ 0   ┆ M02 ┆ MV_ ┆ 10  ┆ 0.9 ┆ 0   ┆ 4   ┆ 3   ┆ 0   ┆ 286 ┆ 286 ┆ 36  ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 65. ┆ 17. ┆ 2.2 ┆ 0.0 ┆ 13. ┆ 1   ┆ 0   ┆ 0   ┆ 61  ┆ 204 ┆ 4.9 ┆ 448 ┆ 11. ┆ 80  ┆ fal ┆ fal ┆ tru ┆ false  ┆ 60    ┆ 3     ┆ 44    │
│ A6- ┆ 603 ┆     ┆     ┆ 010 ┆ A6- ┆     ┆ 090 ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆ 836 ┆ .93 ┆ 834 ┆ .93 ┆ 148 ┆ 3   ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ .71 ┆ 930 ┆     ┆ 281 ┆     ┆ se  ┆ se  ┆ e   ┆        ┆       ┆       ┆       │
│ Wee ┆ 12  ┆     ┆     ┆ 0   ┆ Wee ┆     ┆ 91  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 657 ┆ 685 ┆ 999 ┆ 769 ┆ 415 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 453 ┆ 37  ┆     ┆ 706 ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ y-S ┆     ┆     ┆     ┆     ┆ y-S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ Don ┆     ┆     ┆     ┆     ┆ Don ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ -00 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 400 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 0_M ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ 2_2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │
│ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        ┆       ┆       ┆       │

In [78]:
print(model_ready.describe())

shape: (9, 41)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬────────┐
│ sta ┆ tri ┆ sta ┆ rou ┆ dir ┆ sha ┆ ser ┆ sto ┆ tri ┆ hou ┆ wee ┆ mon ┆ is_ ┆ sch ┆ sch ┆ sch ┆ sto ┆ sto ┆ lat ┆ lon ┆ bea ┆ tem ┆ pre ┆ sno ┆ win ┆ is_ ┆ is_ ┆ is_ ┆ wea ┆ seg ┆ sch ┆ ups ┆ spe ┆ hea ┆ is_ ┆ is_ ┆ is_ ┆ has ┆ rid ┆ tra ┆ travel │
│ tis ┆ p_i ┆ rt_ ┆ te_ ┆ ect ┆ pe_ ┆ vic ┆ p_s ┆ p_p ┆ r   ┆ kda ┆ th  ┆ pea ┆ edu ┆ edu ┆ edu ┆ p_l ┆ p_l ┆ itu ┆ git ┆ rin ┆ per ┆ cip ┆ wfa ┆ dsp ┆ rai ┆ sno ┆ fog ┆ the ┆ men ┆ edu ┆ tre ┆ ed_ ┆ dwa ┆ wee ┆ fed ┆ sch ┆ _ma ┆ ers ┆ nsf ┆ _time  │
│ tic ┆ d   ┆ dat ┆ id  ┆ ion ┆ id  ┆ e_i ┆ equ ┆ rog ┆ --- ┆ y   ┆ --- ┆ k   ┆ led ┆ led ┆ led ┆ at  ┆ on  ┆ de  ┆ ude ┆ g   ┆ atu ┆ ita ┆ ll_ ┆ eed ┆ nin ┆ win ┆ --- ┆ rco ┆ t_l ┆ led ┆ am_ ┆ mps ┆ y_s ┆ ken ┆ era ┆ ool ┆ jor ┆ hip ┆ ers ┆ ---    │
│ --- ┆ --- ┆ e   ┆ --- ┆ _id ┆ --- ┆ d   ┆ enc ┆ res ┆ f64 ┆ --- ┆ f64 ┆ --- ┆ _ar ┆ _de ┆ _se ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ re_ ┆ tio ┆ cm  ┆ _km ┆ g   ┆ g   ┆ f64 ┆ de  ┆ eng ┆ _se ┆ del ┆ --- ┆ eco ┆ d   ┆ l_h ┆ _da ┆ _ev ┆ --- ┆ --- ┆ f64    │
│ str ┆ str ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ e   ┆ s   ┆     ┆ f64 ┆     ┆ f64 ┆ riv ┆ par ┆ gme ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ f64 ┆ c   ┆ n_m ┆ --- ┆ h   ┆ --- ┆ --- ┆     ┆ --- ┆ th  ┆ gme ┆ ay_ ┆ f64 ┆ nds ┆ --- ┆ oli ┆ y   ┆ ent ┆ f64 ┆ f64 ┆        │
│     ┆     ┆ str ┆     ┆ f64 ┆     ┆ str ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ al  ┆ tur ┆ nt_ ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ m   ┆ f64 ┆ --- ┆ f64 ┆ f64 ┆     ┆ f64 ┆ --- ┆ nt_ ┆ sec ┆     ┆ --- ┆ f64 ┆ day ┆ --- ┆ --- ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ f64 ┆     ┆     ┆     ┆     ┆ --- ┆ e   ┆ tim ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆ f64 ┆ spe ┆ ond ┆     ┆ f64 ┆     ┆ --- ┆ f64 ┆ f64 ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed_ ┆ s   ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mps ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪════════╡
│ cou ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 547 ┆ 54720. │
│ nt  ┆ 20  ┆ 20  ┆ 20  ┆ 20. ┆ 20  ┆ 20  ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 20. ┆ 0      │
│     ┆     ┆     ┆     ┆ 0   ┆     ┆     ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆        │
│ nul ┆ 0   ┆ 0   ┆ 0   ┆ 0.0 ┆ 0   ┆ 0   ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0    │
│ l_c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│ oun ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│ mea ┆ nul ┆ nul ┆ nul ┆ 0.4 ┆ nul ┆ nul ┆ 30. ┆ 0.5 ┆ 12. ┆ 3.8 ┆ 3.0 ┆ 0.3 ┆ 506 ┆ 506 ┆ 95. ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 153 ┆ 8.8 ┆ 0.5 ┆ 0.0 ┆ 14. ┆ 0.7 ┆ 0.1 ┆ 0.0 ┆ 48. ┆ 248 ┆ 4.1 ┆ 239 ┆ 12. ┆ 863 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.0 ┆ 584 ┆ 125 ┆ 97.539 │
│ n   ┆ l   ┆ l   ┆ l   ┆ 933 ┆ l   ┆ l   ┆ 509 ┆ 137 ┆ 647 ┆ 809 ┆     ┆ 535 ┆ 57. ┆ 57. ┆ 305 ┆ 787 ┆ .95 ┆ 787 ┆ .95 ┆ .21 ┆ 134 ┆ 196 ┆ 288 ┆ 223 ┆ 933 ┆ 737 ┆     ┆ 966 ┆ .36 ┆ 613 ┆ .71 ┆ 947 ┆ .30 ┆     ┆     ┆     ┆     ┆ .99 ┆ .19 ┆ 894    │
│     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆ 284 ┆ 52  ┆ 277 ┆ 94  ┆     ┆ 27  ┆ 920 ┆ 920 ┆ 592 ┆ 447 ┆ 849 ┆ 262 ┆ 861 ┆ 780 ┆ 59  ┆ 91  ┆ 57  ┆ 94  ┆ 48  ┆ 39  ┆     ┆ 173 ┆ 807 ┆ 09  ┆ 695 ┆ 189 ┆ 034 ┆     ┆     ┆     ┆     ┆ 702 ┆ 979 ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 541 ┆ 541 ┆     ┆     ┆ 2   ┆     ┆ 8   ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆ 9   ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆ 1   ┆ 9   ┆        │
│ std ┆ nul ┆ nul ┆ nul ┆ 0.4 ┆ nul ┆ nul ┆ 17. ┆ 0.2 ┆ 5.8 ┆ 0.3 ┆ 0.0 ┆ 0.4 ┆ 206 ┆ 206 ┆ 64. ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 95. ┆ 5.5 ┆ 0.5 ┆ 0.0 ┆ 5.2 ┆ 0.4 ┆ 0.3 ┆ 0.0 ┆ 20. ┆ 138 ┆ 1.4 ┆ 497 ┆ 26. ┆ 167 ┆ nul ┆ nul ┆ nul ┆ nul ┆ 326 ┆ 73. ┆ 86.080 │
│     ┆ l   ┆ l   ┆ l   ┆ 999 ┆ l   ┆ l   ┆ 840 ┆ 741 ┆ 639 ┆ 237 ┆     ┆ 780 ┆ 10. ┆ 10. ┆ 891 ┆ 366 ┆ 179 ┆ 367 ┆ 179 ┆ 697 ┆ 705 ┆ 058 ┆ 733 ┆ 892 ┆ 049 ┆ 788 ┆     ┆ 539 ┆ .33 ┆ 108 ┆ .50 ┆ 297 ┆ 0.2 ┆ l   ┆ l   ┆ l   ┆ l   ┆ .96 ┆ 715 ┆ 287    │
│     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆ 438 ┆ 76  ┆ 17  ┆ 98  ┆     ┆ 69  ┆ 975 ┆ 975 ┆ 907 ┆ 6   ┆ 02  ┆ 31  ┆ 69  ┆ 121 ┆ 62  ┆ 86  ┆ 08  ┆ 36  ┆ 07  ┆ 88  ┆     ┆ 43  ┆ 540 ┆ 06  ┆ 700 ┆ 851 ┆ 810 ┆     ┆     ┆     ┆     ┆ 269 ┆ 953 ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 211 ┆ 211 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆ 4   ┆     ┆ 39  ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│ min ┆ MV_ ┆ 202 ┆ M1  ┆ 0.0 ┆ M01 ┆ MV_ ┆ 2.0 ┆ 0.0 ┆ 0.0 ┆ 3.0 ┆ 3.0 ┆ 0.0 ┆ 144 ┆ 144 ┆ 12. ┆ 40. ┆ -74 ┆ 40. ┆ -74 ┆ 0.0 ┆ 1.6 ┆ 0.0 ┆ 0.0 ┆ 4.1 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 61. ┆ 0.8 ┆ -11 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.0 ┆ 5.0 ┆ 0.0 ┆ 1.0    │
│     ┆ A6- ┆ 603 ┆     ┆     ┆ 008 ┆ A6- ┆     ┆ 259 ┆     ┆     ┆     ┆     ┆ 0.0 ┆ 0.0 ┆ 0   ┆ 703 ┆ .00 ┆ 701 ┆ .01 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 833 ┆ 326 ┆ 76. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ Wee ┆ 11  ┆     ┆     ┆ 9   ┆ Wee ┆     ┆ 74  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 882 ┆ 942 ┆ 55  ┆ 283 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 169 ┆ 85  ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ y-S ┆     ┆     ┆     ┆     ┆ y-S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ Don ┆     ┆     ┆     ┆     ┆ Don ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ -00 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ 400 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ 0_M ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ 2_2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│ 25% ┆ nul ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ 16. ┆ 0.2 ┆ 8.0 ┆ 4.0 ┆ 3.0 ┆ 0.0 ┆ 337 ┆ 337 ┆ 58. ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 53. ┆ 4.6 ┆ 0.2 ┆ 0.0 ┆ 9.8 ┆ 1.0 ┆ 0.0 ┆ 0.0 ┆ 51. ┆ 162 ┆ 3.0 ┆ -31 ┆ 1.4 ┆ 311 ┆ nul ┆ nul ┆ nul ┆ nul ┆ 324 ┆ 72. ┆ 50.0   │
│     ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆ 0   ┆ 777 ┆     ┆     ┆     ┆     ┆ 33. ┆ 33. ┆ 0   ┆ 758 ┆ .97 ┆ 759 ┆ .97 ┆ 972 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ .39 ┆ 777 ┆ .0  ┆ 314 ┆ .0  ┆ l   ┆ l   ┆ l   ┆ l   ┆ .0  ┆ 0   ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 78  ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆ 829 ┆ 129 ┆ 071 ┆ 168 ┆ 626 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 692 ┆ 18  ┆     ┆ 46  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│ 50% ┆ nul ┆ nul ┆ nul ┆ 0.0 ┆ nul ┆ nul ┆ 29. ┆ 0.5 ┆ 13. ┆ 4.0 ┆ 3.0 ┆ 0.0 ┆ 506 ┆ 506 ┆ 79. ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 157 ┆ 6.6 ┆ 0.3 ┆ 0.0 ┆ 15. ┆ 1.0 ┆ 0.0 ┆ 0.0 ┆ 51. ┆ 217 ┆ 3.9 ┆ 127 ┆ 3.7 ┆ 624 ┆ nul ┆ nul ┆ nul ┆ nul ┆ 599 ┆ 126 ┆ 81.0   │
│     ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆ 0   ┆ 131 ┆ 0   ┆     ┆     ┆     ┆ 40. ┆ 40. ┆ 0   ┆ 790 ┆ .95 ┆ 790 ┆ .95 ┆ .55 ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆ 0   ┆ .57 ┆ 886 ┆ .0  ┆ 924 ┆ .0  ┆ l   ┆ l   ┆ l   ┆ l   ┆ .0  ┆ .0  ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 58  ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆ 304 ┆ 445 ┆ 07  ┆ 461 ┆ 246 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 905 ┆ 34  ┆     ┆ 71  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│ 75% ┆ nul ┆ nul ┆ nul ┆ 1.0 ┆ nul ┆ nul ┆ 43. ┆ 0.7 ┆ 17. ┆ 4.0 ┆ 3.0 ┆ 1.0 ┆ 658 ┆ 658 ┆ 111 ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 233 ┆ 14. ┆ 0.8 ┆ 0.0 ┆ 19. ┆ 1.0 ┆ 0.0 ┆ 0.0 ┆ 55. ┆ 274 ┆ 5.0 ┆ 369 ┆ 7.5 ┆ 101 ┆ nul ┆ nul ┆ nul ┆ nul ┆ 806 ┆ 181 ┆ 116.0  │
│     ┆ l   ┆ l   ┆ l   ┆     ┆ l   ┆ l   ┆ 0   ┆ 5   ┆ 0   ┆     ┆     ┆     ┆ 83. ┆ 83. ┆ .0  ┆ 815 ┆ .94 ┆ 815 ┆ .94 ┆ .97 ┆ 6   ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆ 0   ┆ .60 ┆ 040 ┆ .0  ┆ 755 ┆ 2.0 ┆ l   ┆ l   ┆ l   ┆ l   ┆ .0  ┆ .0  ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆ 202 ┆ 420 ┆ 372 ┆ 426 ┆ 262 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 421 ┆ 88  ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆ 7   ┆ 6   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│ max ┆ OH_ ┆ 202 ┆ M4  ┆ 1.0 ┆ M15 ┆ OH_ ┆ 77. ┆ 0.9 ┆ 23. ┆ 4.0 ┆ 3.0 ┆ 1.0 ┆ 951 ┆ 951 ┆ 402 ┆ 40. ┆ -73 ┆ 40. ┆ -73 ┆ 344 ┆ 18. ┆ 4.6 ┆ 0.2 ┆ 23. ┆ 1.0 ┆ 1.0 ┆ 0.0 ┆ 73. ┆ 992 ┆ 15. ┆ 460 ┆ 509 ┆ 520 ┆ 0.0 ┆ 0.0 ┆ 1.0 ┆ 0.0 ┆ 117 ┆ 311 ┆ 1771.0 │
│     ┆ A6- ┆ 603 ┆     ┆     ┆ 005 ┆ A6- ┆ 0   ┆ 871 ┆ 0   ┆     ┆     ┆     ┆ 34. ┆ 34. ┆ 2.0 ┆ 859 ┆ .92 ┆ 862 ┆ .92 ┆ .62 ┆ 9   ┆     ┆ 8   ┆ 1   ┆     ┆     ┆     ┆ 0   ┆ .02 ┆ 320 ┆ 9.0 ┆ .11 ┆ 86. ┆     ┆     ┆     ┆     ┆ 6.0 ┆ .0  ┆        │
│     ┆ Wee ┆ 12  ┆     ┆     ┆ 4   ┆ Wee ┆     ┆ 79  ┆     ┆     ┆     ┆     ┆ 0   ┆ 0   ┆     ┆ 129 ┆ 655 ┆ 011 ┆ 462 ┆ 374 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 088 ┆ 422 ┆     ┆ 681 ┆ 0   ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ kda ┆     ┆     ┆     ┆     ┆ kda ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ 9   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ y-S ┆     ┆     ┆     ┆     ┆ y-S ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ Don ┆     ┆     ┆     ┆     ┆ Don ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ -BM ┆     ┆     ┆     ┆     ┆ -BM ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ -14 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ 180 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ 0_M ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
│     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆        │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴────────┘

In [79]:
model_ready.group_by("route_id").len().sort("len", descending=True)

shape: (5, 2)
┌──────────┬───────┐
│ route_id ┆ len   │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ M4       ┆ 13284 │
│ M101     ┆ 12386 │
│ M15      ┆ 11603 │
│ M1       ┆ 9838  │
│ M2       ┆ 7609  │
└──────────┴───────┘

In [80]:
model_ready.select([
    pl.col("scheduled_arrival").min().alias("min"),
    pl.col("scheduled_arrival").max().alias("max"),
    pl.col("scheduled_arrival").mean().alias("mean"),
])

shape: (1, 3)
┌──────┬───────┬──────────────┐
│ min  ┆ max   ┆ mean         │
│ ---  ┆ ---   ┆ ---          │
│ i32  ┆ i32   ┆ f64          │
╞══════╪═══════╪══════════════╡
│ 1440 ┆ 95134 ┆ 50657.920541 │
└──────┴───────┴──────────────┘

In [81]:
print(
    trip_updates.group_by("route_id").len().sort("len", descending=True)
)

print(
    matched.group_by("route_id").len().sort("len", descending=True)
)

print(
    model_ready.group_by("route_id").len().sort("len", descending=True)
)

shape: (5, 2)
┌──────────┬───────┐
│ route_id ┆ len   │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ M4       ┆ 17256 │
│ M101     ┆ 15820 │
│ M15      ┆ 15022 │
│ M1       ┆ 12767 │
│ M2       ┆ 10401 │
└──────────┴───────┘
shape: (5, 2)
┌──────────┬───────┐
│ route_id ┆ len   │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ M4       ┆ 17256 │
│ M101     ┆ 15820 │
│ M15      ┆ 15022 │
│ M1       ┆ 12767 │
│ M2       ┆ 10401 │
└──────────┴───────┘
shape: (5, 2)
┌──────────┬───────┐
│ route_id ┆ len   │
│ ---      ┆ ---   │
│ str      ┆ u32   │
╞══════════╪═══════╡
│ M4       ┆ 13284 │
│ M101     ┆ 12386 │
│ M15      ┆ 11603 │
│ M1       ┆ 9838  │
│ M2       ┆ 7609  │
└──────────┴───────┘

In [82]:
model_ready.write_parquet("raw/processed_gtfs/baseline_dataset.parquet")
print("written")

written