In [1]:
import polars as pl
import math
from pathlib import Path

pl.Config.set_tbl_cols(-1)
pl.Config.set_tbl_rows(20)
pl.Config.set_tbl_width_chars(250)

polars.config.Config

In [2]:
GTFS = Path("raw/processed_gtfs")

routes = pl.read_parquet(GTFS / "routes.parquet")
trips = pl.read_parquet(GTFS / "trips.parquet")
stop_times = pl.read_parquet(GTFS / "stop_times.parquet")
stops = pl.read_parquet(GTFS / "stops.parquet")
shapes = pl.read_parquet(GTFS / "shapes.parquet")

In [3]:
# ============================================================
# Clean stop coordinates
# ============================================================

stops = stops.with_columns(
    pl.col("stop_lat")
        .str.strip_chars()
        .cast(pl.Float64),

    pl.col("stop_lon")
        .str.strip_chars()
        .cast(pl.Float64)
)

In [4]:
# ============================================================
# GTFS time parser
# Handles times like 25:13:00
# ============================================================

def gtfs_to_seconds(t):

    if t is None:
        return None

    h, m, s = map(int, t.split(":"))

    return h * 3600 + m * 60 + s

In [5]:
# ============================================================
# Convert schedule times
# ============================================================

stop_times = stop_times.with_columns(

    pl.col("arrival_time")
    .map_elements(
        gtfs_to_seconds,
        return_dtype=pl.Int64
    )
    .alias("arrival_seconds"),

    pl.col("departure_time")
    .map_elements(
        gtfs_to_seconds,
        return_dtype=pl.Int64
    )
    .alias("departure_seconds")

)

In [6]:
# ============================================================
# Sort tables
# ============================================================

stop_times = stop_times.sort(
    ["trip_id", "stop_sequence"]
)

shapes = shapes.sort(
    ["shape_id", "shape_pt_sequence"]
)

In [7]:
# ============================================================
# Previous shape point
# ============================================================

shapes = shapes.with_columns(

    pl.col("shape_pt_lat")
    .shift()
    .over("shape_id")
    .alias("prev_lat"),

    pl.col("shape_pt_lon")
    .shift()
    .over("shape_id")
    .alias("prev_lon")

)

In [8]:
# ============================================================
# Compute edge length (Pure Polars)
# ============================================================

R = 6371000.0

lat1 = pl.col("prev_lat") * math.pi / 180
lon1 = pl.col("prev_lon") * math.pi / 180

lat2 = pl.col("shape_pt_lat") * math.pi / 180
lon2 = pl.col("shape_pt_lon") * math.pi / 180

dlat = lat2 - lat1
dlon = lon2 - lon1

a = (
    (dlat / 2).sin().pow(2)
    +
    lat1.cos()
    *
    lat2.cos()
    *
    (dlon / 2).sin().pow(2)
)

c = 2 * pl.arctan2(
    a.sqrt(),
    (1 - a).sqrt()
)

shapes = shapes.with_columns(

    pl.when(
        pl.col("prev_lat").is_null()
    )

    .then(0.0)

    .otherwise(
        R * c
    )

    .alias("edge_length")

)

In [9]:
# ============================================================
# Cumulative distance along every shape
# ============================================================

shapes = shapes.with_columns(

    pl.col("edge_length")
      .cum_sum()
      .over("shape_id")
      .alias("shape_distance")

)

In [10]:
# ============================================================
# Create stop -> shape lookup
# ============================================================

stop_shape = (

    stop_times

    .join(

        trips.select([
            "trip_id",
            "shape_id"
        ]),

        on="trip_id"

    )

    .join(

        stops.select([
            "stop_id",
            "stop_lat",
            "stop_lon"
        ]),

        on="stop_id"

    )

)

In [11]:
# ============================================================
# Join all shape points
# ============================================================

stop_shape = stop_shape.join(

    shapes.select([
        "shape_id",
        "shape_pt_sequence",
        "shape_pt_lat",
        "shape_pt_lon",
        "shape_distance"
    ]),

    on="shape_id"

)

In [12]:
# ============================================================
# Distance stop -> shape point
# Pure Polars
# ============================================================

lat1 = pl.col("stop_lat") * math.pi / 180
lon1 = pl.col("stop_lon") * math.pi / 180

lat2 = pl.col("shape_pt_lat") * math.pi / 180
lon2 = pl.col("shape_pt_lon") * math.pi / 180

dlat = lat2 - lat1
dlon = lon2 - lon1

a = (
    (dlat / 2).sin().pow(2)
    +
    lat1.cos()
    *
    lat2.cos()
    *
    (dlon / 2).sin().pow(2)
)

c = 2 * pl.arctan2(
    a.sqrt(),
    (1 - a).sqrt()
)

stop_shape = stop_shape.with_columns(

    (R * c)

    .alias("distance_to_shape")

)

In [ ]:
# ============================================================
# Keep nearest shape point
# ============================================================

stop_shape_mapping = (

    stop_shape

    .sort("distance_to_shape")

    .group_by([
        "trip_id",
        "stop_id"
    ])

    .first()

    .select([

        "trip_id",

        "shape_id",

        "stop_id",

        "shape_pt_sequence",

        "shape_distance"

    ])

)

In [ ]:
print(stop_shape_mapping.shape)

stop_shape_mapping.head()

(220373, 5)

shape: (5, 5)
┌─────────────────────────────────┬──────────┬─────────┬───────────────────┬────────────────┐
│ trip_id                         ┆ shape_id ┆ stop_id ┆ shape_pt_sequence ┆ shape_distance │
│ ---                             ┆ ---      ┆ ---     ┆ ---               ┆ ---            │
│ str                             ┆ str      ┆ i64     ┆ i64               ┆ f64            │
╞═════════════════════════════════╪══════════╪═════════╪═══════════════════╪════════════════╡
│ UP_C6-Saturday-046300_B6_219    ┆ B60099   ┆ 300654  ┆ 330008            ┆ 12962.736779   │
│ MV_C6-Weekday-059200_M4_428     ┆ M040918  ┆ 400611  ┆ 520002            ┆ 10692.266661   │
│ FB_C6-Sunday-096600_B41_222     ┆ B410154  ┆ 308987  ┆ 180004            ┆ 10974.383551   │
│ FB_C6-Weekday-SDon-123400_B41_… ┆ B410153  ┆ 308348  ┆ 200010            ┆ 5736.850764    │
│ FB_C6-Weekday-SDon-047900_B41_… ┆ B410151  ┆ 308987  ┆ 430004            ┆ 11601.913411   │
└─────────────────────────────────┴──────────┴─────────┴───────────────────┴────────────────┘

In [ ]:
(
    stop_shape_mapping
    .filter(pl.col("trip_id") == "FB_C6-Saturday-066200_B41_230")
    .sort("shape_distance")
    .select([
        "stop_id",
        "shape_distance"
    ])
)

shape: (40, 2)
┌─────────┬────────────────┐
│ stop_id ┆ shape_distance │
│ ---     ┆ ---            │
│ i64     ┆ f64            │
╞═════════╪════════════════╡
│ 307403  ┆ 0.0            │
│ 308051  ┆ 632.461173     │
│ 308845  ┆ 1026.065569    │
│ 306901  ┆ 1209.156087    │
│ 308884  ┆ 1650.611022    │
│ 303295  ┆ 2139.612333    │
│ 308780  ┆ 2397.052739    │
│ 303297  ┆ 2610.013074    │
│ 303300  ┆ 3006.46652     │
│ 303301  ┆ 3208.411232    │
│ …       ┆ …              │
│ 307516  ┆ 9688.26831     │
│ 308557  ┆ 10074.251203   │
│ 303323  ┆ 10247.927863   │
│ 303324  ┆ 10502.273064   │
│ 303338  ┆ 10734.473526   │
│ 303339  ┆ 10971.667732   │
│ 303340  ┆ 11158.525951   │
│ 303341  ┆ 11392.33121    │
│ 307636  ┆ 11663.190067   │
│ 801144  ┆ 12276.79994    │
└─────────┴────────────────┘

In [ ]:
(
    stop_shape_mapping
    .filter(pl.col("trip_id") == "FB_C6-Saturday-066200_B41_230")
    .sort("shape_distance")
    .with_columns(
        (
            pl.col("shape_distance")
            - pl.col("shape_distance").shift(1)
        ).alias("segment_length")
    )
)

shape: (40, 6)
┌───────────────────────────────┬──────────┬─────────┬───────────────────┬────────────────┬────────────────┐
│ trip_id                       ┆ shape_id ┆ stop_id ┆ shape_pt_sequence ┆ shape_distance ┆ segment_length │
│ ---                           ┆ ---      ┆ ---     ┆ ---               ┆ ---            ┆ ---            │
│ str                           ┆ str      ┆ i64     ┆ i64               ┆ f64            ┆ f64            │
╞═══════════════════════════════╪══════════╪═════════╪═══════════════════╪════════════════╪════════════════╡
│ FB_C6-Saturday-066200_B41_230 ┆ B410126  ┆ 307403  ┆ 10001             ┆ 0.0            ┆ null           │
│ FB_C6-Saturday-066200_B41_230 ┆ B410126  ┆ 308051  ┆ 10014             ┆ 632.461173     ┆ 632.461173     │
│ FB_C6-Saturday-066200_B41_230 ┆ B410126  ┆ 308845  ┆ 20012             ┆ 1026.065569    ┆ 393.604396     │
│ FB_C6-Saturday-066200_B41_230 ┆ B410126  ┆ 306901  ┆ 30005             ┆ 1209.156087    ┆ 183.090518     │
│ FB_C6-Saturday-066200_B41_230 ┆ B410126  ┆ 308884  ┆ 40006             ┆ 1650.611022    ┆ 441.454935     │
│ FB_C6-Saturday-066200_B41_230 ┆ B410126  ┆ 303295  ┆ 50009             ┆ 2139.612333    ┆ 489.001311     │
│ FB_C6-Saturday-066200_B41_230 ┆ B410126  ┆ 308780  ┆ 60005             ┆ 2397.052739    ┆ 257.440406     │
│ FB_C6-Saturday-066200_B41_230 ┆ B410126  ┆ 303297  ┆ 70004             ┆ 2610.013074    ┆ 212.960335     │
│ FB_C6-Saturday-066200_B41_230 ┆ B410126  ┆ 303300  ┆ 80007             ┆ 3006.46652     ┆ 396.453445     │
│ FB_C6-Saturday-066200_B41_230 ┆ B410126  ┆ 303301  ┆ 90005             ┆ 3208.411232    ┆ 201.944712     │
│ …                             ┆ …        ┆ …       ┆ …                 ┆ …              ┆ …              │
│ FB_C6-Saturday-066200_B41_230 ┆ B410126  ┆ 307516  ┆ 300011            ┆ 9688.26831     ┆ 393.965643     │
│ FB_C6-Saturday-066200_B41_230 ┆ B410126  ┆ 308557  ┆ 310010            ┆ 10074.251203   ┆ 385.982893     │
│ FB_C6-Saturday-066200_B41_230 ┆ B410126  ┆ 303323  ┆ 320005            ┆ 10247.927863   ┆ 173.67666      │
│ FB_C6-Saturday-066200_B41_230 ┆ B410126  ┆ 303324  ┆ 330008            ┆ 10502.273064   ┆ 254.345201     │
│ FB_C6-Saturday-066200_B41_230 ┆ B410126  ┆ 303338  ┆ 340005            ┆ 10734.473526   ┆ 232.200462     │
│ FB_C6-Saturday-066200_B41_230 ┆ B410126  ┆ 303339  ┆ 350005            ┆ 10971.667732   ┆ 237.194206     │
│ FB_C6-Saturday-066200_B41_230 ┆ B410126  ┆ 303340  ┆ 360004            ┆ 11158.525951   ┆ 186.85822      │
│ FB_C6-Saturday-066200_B41_230 ┆ B410126  ┆ 303341  ┆ 370007            ┆ 11392.33121    ┆ 233.805259     │
│ FB_C6-Saturday-066200_B41_230 ┆ B410126  ┆ 307636  ┆ 380010            ┆ 11663.190067   ┆ 270.858857     │
│ FB_C6-Saturday-066200_B41_230 ┆ B410126  ┆ 801144  ┆ 390008            ┆ 12276.79994    ┆ 613.609873     │
└───────────────────────────────┴──────────┴─────────┴───────────────────┴────────────────┴────────────────┘

In [ ]:
stop_shape_mapping.write_parquet("processed/stop_shape_mapping.parquet")

In [ ]:
segments = (
    stop_times
    .with_columns([

        pl.col("stop_id")
        .shift(-1)
        .over("trip_id")
        .alias("next_stop_id"),

        pl.col("stop_sequence")
        .shift(-1)
        .over("trip_id")
        .alias("next_stop_sequence"),

        pl.col("arrival_seconds")
        .shift(-1)
        .over("trip_id")
        .alias("next_arrival"),

        pl.col("departure_seconds")
        .shift(-1)
        .over("trip_id")
        .alias("next_departure")

    ])
    .filter(
        pl.col("next_stop_id").is_not_null()
    )
)

In [ ]:
segments = segments.with_columns(

    (
        pl.col("next_arrival")
        -
        pl.col("departure_seconds")
    )

    .alias("scheduled_travel_time")

)

In [ ]:
segments = segments.join(

    trips.select([
        "trip_id",
        "route_id",
        "direction_id",
        "shape_id"
    ]),

    on="trip_id",
    how="left"

)

In [ ]:
segments = segments.join(

    stops.select([
        "stop_id",
        "stop_name",
        "stop_lat",
        "stop_lon"
    ]),

    on="stop_id",
    how="left"

)

In [ ]:
segments = segments.rename({

    "stop_name": "start_stop_name",
    "stop_lat": "start_lat",
    "stop_lon": "start_lon"

})

In [ ]:
segments = segments.join(

    stops.select([
        "stop_id",
        "stop_name",
        "stop_lat",
        "stop_lon"
    ]),

    left_on="next_stop_id",
    right_on="stop_id",
    how="left"

)

In [ ]:
segments = segments.rename({

    "stop_name": "end_stop_name",
    "stop_lat": "end_lat",
    "stop_lon": "end_lon"

})

In [ ]:
segments = (
    segments
    .join(
        stop_shape_mapping.select([
            "trip_id",
            "stop_id",
            "shape_distance"
        ]),
        on=["trip_id", "stop_id"],
        how="left"
    )
)

In [ ]:
segments = (
    segments
    .join(
        stop_shape_mapping.select([
            "trip_id",
            "stop_id",
            "shape_distance"
        ]).rename({
            "stop_id": "next_stop_id",
            "shape_distance": "next_shape_distance"
        }),
        on=["trip_id", "next_stop_id"],
        how="left"
    )
)

In [ ]:
segments = segments.with_columns(

    (
        pl.col("next_shape_distance")
        -
        pl.col("shape_distance")
    )
    .abs()
    .alias("segment_length")

)

In [ ]:
segments = segments.with_columns(

    pl.concat_str([

        pl.col("route_id"),

        pl.col("direction_id").cast(pl.String),

        pl.col("shape_id"),

        pl.col("stop_id").cast(pl.String),

        pl.col("next_stop_id").cast(pl.String)

    ], separator="_").alias("segment_id")

)

In [ ]:
segment_network = (

    segments

    .select([

        "segment_id",

        "route_id",
        "direction_id",
        "shape_id",

        "stop_id",
        "next_stop_id",

        "stop_sequence",
        "next_stop_sequence",

        "start_stop_name",
        "end_stop_name",

        "start_lat",
        "start_lon",

        "end_lat",
        "end_lon",

        "shape_distance",
        "next_shape_distance",

        "segment_length",

        "scheduled_travel_time"

    ])

    .unique(subset=["segment_id"])

    .sort([
        "route_id",
        "direction_id",
        "shape_distance"
    ])

)

In [ ]:
segment_schedule = (

    segments

    .select([

        "trip_id",

        "route_id",
        "direction_id",

        "segment_id",

        "departure_seconds",

        "next_arrival",

        "scheduled_travel_time"

    ])

    .sort([
        "trip_id",
        "departure_seconds"
    ])

)

In [ ]:
OUTPUT = Path("processed")

OUTPUT.mkdir(exist_ok=True)

segment_network.write_parquet(
    OUTPUT / "segment_network.parquet"
)

segment_schedule.write_parquet(
    OUTPUT / "segment_schedule.parquet"
)

In [ ]:
segment_network.head()

shape: (5, 18)
┌───────────────┬──────────┬──────────────┬──────────┬─────────┬──────────────┬───────────────┬──────────────┬──────────────┬──────────────┬───────────┬────────────┬───────────┬────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ segment_id    ┆ route_id ┆ direction_id ┆ shape_id ┆ stop_id ┆ next_stop_id ┆ stop_sequence ┆ next_stop_se ┆ start_stop_n ┆ end_stop_nam ┆ start_lat ┆ start_lon  ┆ end_lat   ┆ end_lon    ┆ shape_distan ┆ next_shape_d ┆ segment_leng ┆ scheduled_tr │
│ ---           ┆ ---      ┆ ---          ┆ ---      ┆ ---     ┆ ---          ┆ ---           ┆ quence       ┆ ame          ┆ e            ┆ ---       ┆ ---        ┆ ---       ┆ ---        ┆ ce           ┆ istance      ┆ th           ┆ avel_time    │
│ str           ┆ str      ┆ i64          ┆ str      ┆ i64     ┆ i64          ┆ i64           ┆ ---          ┆ ---          ┆ ---          ┆ f64       ┆ f64        ┆ f64       ┆ f64        ┆ ---          ┆ ---          ┆ ---          ┆ ---          │
│               ┆          ┆              ┆          ┆         ┆              ┆               ┆ i64          ┆ str          ┆ str          ┆           ┆            ┆           ┆            ┆ f64          ┆ f64          ┆ f64          ┆ i64          │
╞═══════════════╪══════════╪══════════════╪══════════╪═════════╪══════════════╪═══════════════╪══════════════╪══════════════╪══════════════╪═══════════╪════════════╪═══════════╪════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ B41_0_B410152 ┆ B41      ┆ 0            ┆ B410152  ┆ 308381  ┆ 303269       ┆ 1             ┆ 2            ┆ E 70         ┆ VETERANS     ┆ 40.619935 ┆ -73.908708 ┆ 40.62002  ┆ -73.910961 ┆ 0.0          ┆ 194.519241   ┆ 194.519241   ┆ 61           │
│ _308381_30326 ┆          ┆              ┆          ┆         ┆              ┆               ┆              ┆ ST/VETERANS  ┆ AV/AVENUE T  ┆           ┆            ┆           ┆            ┆              ┆              ┆              ┆              │
│ 9             ┆          ┆              ┆          ┆         ┆              ┆               ┆              ┆ AV           ┆              ┆           ┆            ┆           ┆            ┆              ┆              ┆              ┆              │
│ B41_0_B410165 ┆ B41      ┆ 0            ┆ B410165  ┆ 308381  ┆ 303269       ┆ 1             ┆ 2            ┆ E 70         ┆ VETERANS     ┆ 40.619935 ┆ -73.908708 ┆ 40.62002  ┆ -73.910961 ┆ 0.0          ┆ 194.519241   ┆ 194.519241   ┆ 55           │
│ _308381_30326 ┆          ┆              ┆          ┆         ┆              ┆               ┆              ┆ ST/VETERANS  ┆ AV/AVENUE T  ┆           ┆            ┆           ┆            ┆              ┆              ┆              ┆              │
│ 9             ┆          ┆              ┆          ┆         ┆              ┆               ┆              ┆ AV           ┆              ┆           ┆            ┆           ┆            ┆              ┆              ┆              ┆              │
│ B41_0_B410135 ┆ B41      ┆ 0            ┆ B410135  ┆ 303215  ┆ 300163       ┆ 1             ┆ 2            ┆ FLATBUSH     ┆ FLATBUSH     ┆ 40.609251 ┆ -73.92154  ┆ 40.611476 ┆ -73.92407  ┆ 0.0          ┆ 326.685685   ┆ 326.685685   ┆ 92           │
│ _303215_30016 ┆          ┆              ┆          ┆         ┆              ┆               ┆              ┆ AV/KINGS     ┆ AV/AVENUE T  ┆           ┆            ┆           ┆            ┆              ┆              ┆              ┆              │
│ 3             ┆          ┆              ┆          ┆         ┆              ┆               ┆              ┆ PLAZA        ┆              ┆           ┆            ┆           ┆            ┆              ┆              ┆              ┆              │
│ B41_0_B410157 ┆ B41      ┆ 0            ┆ B410157  ┆ 308381  ┆ 303269       ┆ 1             ┆ 2            ┆ E 70         ┆ VETERANS     ┆ 40.619935 ┆ -73.908708 ┆ 40.62002  ┆ -73.910961 ┆ 0.0          ┆ 194.519241   ┆ 194.519241   ┆ 44           │
│ _308381_30326 ┆          ┆              ┆          ┆         ┆              ┆               ┆              ┆ ST/VETERANS  ┆ AV/AVENUE T  ┆           ┆            ┆           ┆            ┆              ┆              ┆              ┆              │
│ 9             ┆          ┆              ┆          ┆         ┆              ┆               ┆              ┆ AV           ┆              ┆           ┆            ┆           ┆            ┆              ┆              ┆              ┆              │
│ B41_0_B410151 ┆ B41      ┆ 0            ┆ B410151  ┆ 308381  ┆ 303269       ┆ 1             ┆ 2            ┆ E 70         ┆ VETERANS     ┆ 40.619935 ┆ -73.908708 ┆ 40.62002  ┆ -73.910961 ┆ 0.0          ┆ 194.519241   ┆ 194.519241   ┆ 39           │
│ _308381_30326 ┆          ┆              ┆          ┆         ┆              ┆               ┆              ┆ ST/VETERANS  ┆ AV/AVENUE T  ┆           ┆            ┆           ┆            ┆              ┆              ┆              ┆              │
│ 9             ┆          ┆              ┆          ┆         ┆              ┆               ┆              ┆ AV           ┆              ┆           ┆            ┆           ┆            ┆              ┆              ┆              ┆              │
└───────────────┴──────────┴──────────────┴──────────┴─────────┴──────────────┴───────────────┴──────────────┴──────────────┴──────────────┴───────────┴────────────┴───────────┴────────────┴──────────────┴──────────────┴──────────────┴──────────────┘

In [ ]:
segment_schedule.head()

shape: (5, 7)
┌───────────────────────────────┬──────────┬──────────────┬─────────────────────────────┬───────────────────┬──────────────┬───────────────────────┐
│ trip_id                       ┆ route_id ┆ direction_id ┆ segment_id                  ┆ departure_seconds ┆ next_arrival ┆ scheduled_travel_time │
│ ---                           ┆ ---      ┆ ---          ┆ ---                         ┆ ---               ┆ ---          ┆ ---                   │
│ str                           ┆ str      ┆ i64          ┆ str                         ┆ i64               ┆ i64          ┆ i64                   │
╞═══════════════════════════════╪══════════╪══════════════╪═════════════════════════════╪═══════════════════╪══════════════╪═══════════════════════╡
│ FB_C6-Saturday-003500_B41_201 ┆ B41      ┆ 0            ┆ B41_0_B410153_303215_300163 ┆ 2100              ┆ 2166         ┆ 66                    │
│ FB_C6-Saturday-003500_B41_201 ┆ B41      ┆ 0            ┆ B41_0_B410153_300163_303218 ┆ 2166              ┆ 2232         ┆ 66                    │
│ FB_C6-Saturday-003500_B41_201 ┆ B41      ┆ 0            ┆ B41_0_B410153_303218_303219 ┆ 2232              ┆ 2281         ┆ 49                    │
│ FB_C6-Saturday-003500_B41_201 ┆ B41      ┆ 0            ┆ B41_0_B410153_303219_306273 ┆ 2281              ┆ 2330         ┆ 49                    │
│ FB_C6-Saturday-003500_B41_201 ┆ B41      ┆ 0            ┆ B41_0_B410153_306273_303222 ┆ 2330              ┆ 2400         ┆ 70                    │
└───────────────────────────────┴──────────┴──────────────┴─────────────────────────────┴───────────────────┴──────────────┴───────────────────────┘

In [ ]:
shape_points = (
    shapes
    .select([
        "shape_id",
        "shape_pt_sequence",
        "shape_pt_lat",
        "shape_pt_lon",
        "shape_distance"
    ])
    .sort([
        "shape_id",
        "shape_pt_sequence"
    ])
)

shape_points.write_parquet(
    "processed/shape_points.parquet"
)

In [ ]:
trip_shapes = (
    trips
    .select([
        "trip_id",
        "route_id",
        "direction_id",
        "shape_id"
    ])
)

trip_shapes.write_parquet(
    "processed/trip_shapes.parquet"
)

In [ ]:
vehicle = pl.read_parquet("raw/vehicle_positions/2026-04-06.parquet")

(
    vehicle
    .filter(pl.col("trip_id") == "MV_A6-Sunday-114600_M4_454")
    .sort("timestamp")
    .select([
        "timestamp",
        "vehicle_id",
        "trip_id",
        "stop_id",
        "latitude",
        "longitude"
    ])
    .head(100)
)

shape: (62, 6)
┌────────────┬───────────────┬────────────────────────────┬─────────┬───────────┬────────────┐
│ timestamp  ┆ vehicle_id    ┆ trip_id                    ┆ stop_id ┆ latitude  ┆ longitude  │
│ ---        ┆ ---           ┆ ---                        ┆ ---     ┆ ---       ┆ ---        │
│ u64        ┆ str           ┆ str                        ┆ str     ┆ f32       ┆ f32        │
╞════════════╪═══════════════╪════════════════════════════╪═════════╪═══════════╪════════════╡
│ 1775433585 ┆ MTA NYCT_9777 ┆ MV_A6-Sunday-114600_M4_454 ┆ 400614  ┆ 40.827335 ┆ -73.949661 │
│ 1775433613 ┆ MTA NYCT_9777 ┆ MV_A6-Sunday-114600_M4_454 ┆ 400614  ┆ 40.827431 ┆ -73.949593 │
│ 1775433641 ┆ MTA NYCT_9777 ┆ MV_A6-Sunday-114600_M4_454 ┆ 400615  ┆ 40.827991 ┆ -73.949181 │
│ 1775433668 ┆ MTA NYCT_9777 ┆ MV_A6-Sunday-114600_M4_454 ┆ 400615  ┆ 40.828377 ┆ -73.948898 │
│ 1775433695 ┆ MTA NYCT_9777 ┆ MV_A6-Sunday-114600_M4_454 ┆ 400615  ┆ 40.828835 ┆ -73.94857  │
│ 1775433751 ┆ MTA NYCT_9777 ┆ MV_A6-Sunday-114600_M4_454 ┆ 400616  ┆ 40.829315 ┆ -73.948219 │
│ 1775433751 ┆ MTA NYCT_9777 ┆ MV_A6-Sunday-114600_M4_454 ┆ 400616  ┆ 40.829971 ┆ -73.947739 │
│ 1775433779 ┆ MTA NYCT_9777 ┆ MV_A6-Sunday-114600_M4_454 ┆ 400616  ┆ 40.82988  ┆ -73.947807 │
│ 1775433807 ┆ MTA NYCT_9777 ┆ MV_A6-Sunday-114600_M4_454 ┆ 400617  ┆ 40.830727 ┆ -73.947189 │
│ 1775433862 ┆ MTA NYCT_9777 ┆ MV_A6-Sunday-114600_M4_454 ┆ 400617  ┆ 40.831463 ┆ -73.946648 │
│ …          ┆ …             ┆ …                          ┆ …       ┆ …         ┆ …          │
│ 1775435219 ┆ MTA NYCT_9777 ┆ MV_A6-Sunday-114600_M4_454 ┆ 400636  ┆ 40.858967 ┆ -73.93428  │
│ 1775435247 ┆ MTA NYCT_9777 ┆ MV_A6-Sunday-114600_M4_454 ┆ 400636  ┆ 40.859146 ┆ -73.934174 │
│ 1775435274 ┆ MTA NYCT_9777 ┆ MV_A6-Sunday-114600_M4_454 ┆ 400636  ┆ 40.859146 ┆ -73.934174 │
│ 1775435274 ┆ MTA NYCT_9777 ┆ MV_A6-Sunday-114600_M4_454 ┆ 400636  ┆ 40.859322 ┆ -73.934296 │
│ 1775435302 ┆ MTA NYCT_9777 ┆ MV_A6-Sunday-114600_M4_454 ┆ 400636  ┆ 40.859215 ┆ -73.934174 │
│ 1775435357 ┆ MTA NYCT_9777 ┆ MV_A6-Sunday-114600_M4_454 ┆ 400636  ┆ 40.859478 ┆ -73.934006 │
│ 1775435384 ┆ MTA NYCT_9777 ┆ MV_A6-Sunday-114600_M4_454 ┆ 400636  ┆ 40.859417 ┆ -73.933907 │
│ 1775435411 ┆ MTA NYCT_9777 ┆ MV_A6-Sunday-114600_M4_454 ┆ 400636  ┆ 40.859478 ┆ -73.934196 │
│ 1775435439 ┆ MTA NYCT_9777 ┆ MV_A6-Sunday-114600_M4_454 ┆ 400636  ┆ 40.859215 ┆ -73.934029 │
│ 1775435467 ┆ MTA NYCT_9777 ┆ MV_A6-Sunday-114600_M4_454 ┆ 400636  ┆ 40.859146 ┆ -73.934174 │
└────────────┴───────────────┴────────────────────────────┴─────────┴───────────┴────────────┘

In [ ]:
import polars as pl
import math
from pathlib import Path

pl.Config.set_tbl_cols(-1)
pl.Config.set_tbl_rows(20)
pl.Config.set_tbl_width_chars(250)

polars.config.Config

In [ ]:
import polars as pl
vehicle_positions = pl.read_parquet("raw/vehicle_positions/2026-04-06.parquet")
trip_updates = pl.read_parquet("raw/trip_updates/2026-04-06.parquet")

vehicle_positions.join(
        trip_updates.select([
            "trip_id",
            "stop_id",
            "stop_sequence",
            "arrival_time",
            "departure_time"
        ]),
        on=["trip_id", "stop_id"],
        how="left"
    )

shape: (277_044, 15)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ trip_id   ┆ route_id ┆ vehicle_i ┆ direction ┆ … ┆ timestamp ┆ stop_sequ ┆ arrival_t ┆ departure │
│ ---       ┆ ---      ┆ d         ┆ _id       ┆   ┆ ---       ┆ ence      ┆ ime       ┆ _time     │
│ str       ┆ str      ┆ ---       ┆ ---       ┆   ┆ u64       ┆ ---       ┆ ---       ┆ ---       │
│           ┆          ┆ str       ┆ u32       ┆   ┆           ┆ u32       ┆ i64       ┆ i64       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ MV_A6-Sun ┆ M4       ┆ MTA       ┆ 0         ┆ … ┆ 177543358 ┆ null      ┆ null      ┆ null      │
│ day-11460 ┆          ┆ NYCT_9777 ┆           ┆   ┆ 5         ┆           ┆           ┆           │
│ 0_M4_454  ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ UP_A6-Sun ┆ B6       ┆ MTA       ┆ 1         ┆ … ┆ 177543359 ┆ null      ┆ null      ┆ null      │
│ day-11580 ┆          ┆ NYCT_7174 ┆           ┆   ┆ 0         ┆           ┆           ┆           │
│ 0_B36_421 ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ MV_A6-Sun ┆ M4       ┆ MTA       ┆ 0         ┆ … ┆ 177543357 ┆ null      ┆ null      ┆ null      │
│ day-11780 ┆          ┆ NYCT_9715 ┆           ┆   ┆ 8         ┆           ┆           ┆           │
│ 0_M4_439  ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ UP_A6-Sun ┆ B6       ┆ MTA       ┆ 0         ┆ … ┆ 177543359 ┆ null      ┆ null      ┆ null      │
│ day-11550 ┆          ┆ NYCT_4872 ┆           ┆   ┆ 0         ┆           ┆           ┆           │
│ 0_B36_413 ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ UP_A6-Sun ┆ B6       ┆ MTA       ┆ 0         ┆ … ┆ 177543357 ┆ null      ┆ null      ┆ null      │
│ day-11460 ┆          ┆ NYCT_4865 ┆           ┆   ┆ 5         ┆           ┆           ┆           │
│ 0_B6_231  ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 44409259- ┆ Q25      ┆ MTABC_594 ┆ 1         ┆ … ┆ 177551995 ┆ null      ┆ null      ┆ null      │
│ CPPA6-CP_ ┆          ┆           ┆           ┆   ┆ 9         ┆           ┆           ┆           │
│ A6-Weekda ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ y-0…      ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 44409755- ┆ Q25      ┆ MTABC_191 ┆ 0         ┆ … ┆ 177551996 ┆ null      ┆ null      ┆ null      │
│ CPPA6-CP_ ┆          ┆           ┆           ┆   ┆ 0         ┆           ┆           ┆           │
│ A6-Weekda ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ y-0…      ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 44409801- ┆ Q25      ┆ MTABC_187 ┆ 0         ┆ … ┆ 177551993 ┆ null      ┆ null      ┆ null      │
│ CPPA6-CP_ ┆          ┆           ┆           ┆   ┆ 4         ┆           ┆           ┆           │
│ A6-Weekda ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ y-0…      ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 44409700- ┆ Q25      ┆ MTABC_213 ┆ 0         ┆ … ┆ 177551994 ┆ null      ┆ null      ┆ null      │
│ CPPA6-CP_ ┆          ┆           ┆           ┆   ┆ 4         ┆           ┆           ┆           │
│ A6-Weekda ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ y-0…      ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 44409784- ┆ Q25      ┆ MTABC_231 ┆ 0         ┆ … ┆ 177551994 ┆ null      ┆ null      ┆ null      │
│ CPPA6-CP_ ┆          ┆           ┆           ┆   ┆ 8         ┆           ┆           ┆           │
│ A6-Weekda ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ y-0…      ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
import polars as pl

trip = "MV_A6-Sunday-114600_M4_454"

vp = (
    pl.read_parquet("raw/vehicle_positions/2026-04-06.parquet")
    .filter(pl.col("trip_id") == trip)
    .sort("timestamp")
)

tu = (
    pl.read_parquet("raw/trip_updates/2026-04-06.parquet")
    .filter(pl.col("trip_id") == trip)
    .sort("stop_sequence")
)

print(vp.select([
    "timestamp",
    "stop_id"
]))

print()

print(tu.select([
    "stop_sequence",
    "stop_id",
    "arrival_time",
    "departure_time"
]))

shape: (62, 2)
┌────────────┬─────────┐
│ timestamp  ┆ stop_id │
│ ---        ┆ ---     │
│ u64        ┆ str     │
╞════════════╪═════════╡
│ 1775433585 ┆ 400614  │
│ 1775433613 ┆ 400614  │
│ 1775433641 ┆ 400615  │
│ 1775433668 ┆ 400615  │
│ 1775433695 ┆ 400615  │
│ …          ┆ …       │
│ 1775435357 ┆ 400636  │
│ 1775435384 ┆ 400636  │
│ 1775435411 ┆ 400636  │
│ 1775435439 ┆ 400636  │
│ 1775435467 ┆ 400636  │
└────────────┴─────────┘

shape: (618, 4)
┌───────────────┬─────────┬──────────────┬────────────────┐
│ stop_sequence ┆ stop_id ┆ arrival_time ┆ departure_time │
│ ---           ┆ ---     ┆ ---          ┆ ---            │
│ u32           ┆ str     ┆ i64          ┆ i64            │
╞═══════════════╪═════════╪══════════════╪════════════════╡
│ 55            ┆ 400614  ┆ 1775433645   ┆ 1775433645     │
│ 55            ┆ 400614  ┆ 1775433665   ┆ 1775433665     │
│ 55            ┆ 400614  ┆ 1775433646   ┆ 1775433646     │
│ 56            ┆ 400615  ┆ 1775433703   ┆ 1775433703     │
│ 56            ┆ 400615  ┆ 1775433723   ┆ 1775433723     │
│ …             ┆ …       ┆ …            ┆ …              │
│ 77            ┆ 903290  ┆ 1775435388   ┆ 1775435388     │
│ 77            ┆ 903290  ┆ 1775435415   ┆ 1775435415     │
│ 77            ┆ 903290  ┆ 1775435442   ┆ 1775435442     │
│ 77            ┆ 903290  ┆ 1775435470   ┆ 1775435470     │
│ 77            ┆ 903290  ┆ 1775435498   ┆ 1775435498     │
└───────────────┴─────────┴──────────────┴────────────────┘

In [ ]:
joined = (
    vp.join(
        tu.select([
            "trip_id",
            "stop_id",
            "stop_sequence",
            "arrival_time",
            "departure_time"
        ]),
        on=["trip_id", "stop_id"],
        how="left"
    )
)

print(
    joined.select([
        "timestamp",
        "stop_id",
        "stop_sequence",
        "arrival_time",
        "departure_time"
    ])
)

shape: (1_122, 5)
┌────────────┬─────────┬───────────────┬──────────────┬────────────────┐
│ timestamp  ┆ stop_id ┆ stop_sequence ┆ arrival_time ┆ departure_time │
│ ---        ┆ ---     ┆ ---           ┆ ---          ┆ ---            │
│ u64        ┆ str     ┆ u32           ┆ i64          ┆ i64            │
╞════════════╪═════════╪═══════════════╪══════════════╪════════════════╡
│ 1775433585 ┆ 400614  ┆ 55            ┆ 1775433645   ┆ 1775433645     │
│ 1775433585 ┆ 400614  ┆ 55            ┆ 1775433665   ┆ 1775433665     │
│ 1775433585 ┆ 400614  ┆ 55            ┆ 1775433646   ┆ 1775433646     │
│ 1775433613 ┆ 400614  ┆ 55            ┆ 1775433645   ┆ 1775433645     │
│ 1775433613 ┆ 400614  ┆ 55            ┆ 1775433665   ┆ 1775433665     │
│ …          ┆ …       ┆ …             ┆ …            ┆ …              │
│ 1775435357 ┆ 400636  ┆ null          ┆ null         ┆ null           │
│ 1775435384 ┆ 400636  ┆ null          ┆ null         ┆ null           │
│ 1775435411 ┆ 400636  ┆ null          ┆ null         ┆ null           │
│ 1775435439 ┆ 400636  ┆ null          ┆ null         ┆ null           │
│ 1775435467 ┆ 400636  ┆ null          ┆ null         ┆ null           │
└────────────┴─────────┴───────────────┴──────────────┴────────────────┘

In [ ]:
validation = (
    joined.with_columns(
        (
            pl.col("timestamp") - pl.col("arrival_time")
        ).alias("arrival_diff")
    )
)

print(
    validation.select([
        "timestamp",
        "stop_id",
        "arrival_time",
        "arrival_diff"
    ])
)

shape: (1_122, 4)
┌────────────┬─────────┬──────────────┬──────────────┐
│ timestamp  ┆ stop_id ┆ arrival_time ┆ arrival_diff │
│ ---        ┆ ---     ┆ ---          ┆ ---          │
│ u64        ┆ str     ┆ i64          ┆ f64          │
╞════════════╪═════════╪══════════════╪══════════════╡
│ 1775433585 ┆ 400614  ┆ 1775433645   ┆ -60.0        │
│ 1775433585 ┆ 400614  ┆ 1775433665   ┆ -80.0        │
│ 1775433585 ┆ 400614  ┆ 1775433646   ┆ -61.0        │
│ 1775433613 ┆ 400614  ┆ 1775433645   ┆ -32.0        │
│ 1775433613 ┆ 400614  ┆ 1775433665   ┆ -52.0        │
│ …          ┆ …       ┆ …            ┆ …            │
│ 1775435357 ┆ 400636  ┆ null         ┆ null         │
│ 1775435384 ┆ 400636  ┆ null         ┆ null         │
│ 1775435411 ┆ 400636  ┆ null         ┆ null         │
│ 1775435439 ┆ 400636  ┆ null         ┆ null         │
│ 1775435467 ┆ 400636  ┆ null         ┆ null         │
└────────────┴─────────┴──────────────┴──────────────┘

In [ ]:
# %%
import polars as pl
import re
from pathlib import Path

pl.Config.set_tbl_cols(-1)

RT = Path("raw")

trip_updates = pl.read_parquet(RT / "trip_updates/2026-07-01.parquet")
vehicle_positions = pl.read_parquet(RT / "vehicle_positions/2026-07-01.parquet")

routes = pl.read_parquet("raw/processed_gtfs/routes.parquet")
trips = pl.read_parquet("raw/processed_gtfs/trips.parquet")

# %%
# ============================================================
# Normalize realtime trip_id -> static trip_id
# Strips MTA direction-prefixes like MV_/UP_/DW_/SB_
# ============================================================

def normalize_trip_id(tid: str) -> str:
    return re.sub(r"^[A-Z]{2}_", "", tid)

trip_updates = trip_updates.with_columns(
    pl.col("trip_id")
      .map_elements(normalize_trip_id, return_dtype=pl.String)
      .alias("trip_id_norm")
)

# %%
# Quick sanity check on match rate before going further
match_rate = (
    trip_updates
    .select("trip_id_norm")
    .unique()
    .join(trips.select("trip_id"), left_on="trip_id_norm", right_on="trip_id", how="inner")
    .height
    /
    trip_updates.select("trip_id_norm").unique().height
)
print(f"trip_id match rate: {match_rate:.2%}")

trip_id match rate: 0.00%